// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_ "github.com/syzoj/protoc-gen-gotype/gotype"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	Error                *string  `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Data                 *any.Any `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *Response) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type LoginRequest struct {
	UserName             *string  `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	Password             *string  `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Test                 *UserRef `protobuf:"bytes,3,opt,name=test" json:"test,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *LoginRequest) GetTest() UserRef {
	if m != nil && m.Test != nil {
		return *m.Test
	}
	return ""
}

func init() {
	proto.RegisterType((*Response)(nil), "syzoj.api.Response")
	proto.RegisterType((*LoginRequest)(nil), "syzoj.api.LoginRequest")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x59, 0xad, 0xb8, 0x49, 0x7b, 0x0a, 0x3d, 0xac, 0xeb, 0xc1, 0xb2, 0x78, 0xd8, 0x4b,
	0xb3, 0xe0, 0x1b, 0xd8, 0xa3, 0x88, 0x87, 0x80, 0x07, 0xbd, 0x48, 0xea, 0x4e, 0xd3, 0x95, 0x6e,
	0x26, 0x66, 0xb2, 0x48, 0x7c, 0x04, 0xdf, 0xc0, 0xb7, 0x95, 0x26, 0xea, 0x65, 0xe0, 0xfb, 0xff,
	0x9f, 0x0f, 0x86, 0x33, 0xed, 0x06, 0xe9, 0x3c, 0x06, 0x14, 0x8c, 0xe2, 0x27, 0xbe, 0x49, 0xed,
	0x86, 0xfa, 0xc2, 0x20, 0x9a, 0x03, 0x74, 0xa9, 0xd8, 0x4e, 0xbb, 0x4e, 0xdb, 0x98, 0x57, 0xf5,
	0xc2, 0x60, 0x88, 0x0e, 0x32, 0x35, 0x77, 0xbc, 0x54, 0x40, 0x0e, 0x2d, 0x81, 0x58, 0xf2, 0x33,
	0xf0, 0x1e, 0x7d, 0x55, 0xac, 0x8a, 0x96, 0xa9, 0x0c, 0xa2, 0xe5, 0xb3, 0x5e, 0x07, 0x5d, 0x9d,
	0xac, 0x8a, 0x76, 0x7e, 0xb3, 0x94, 0xd9, 0x2c, 0xff, 0xcc, 0xf2, 0xd6, 0x46, 0x95, 0x16, 0xcd,
	0x9e, 0x2f, 0xee, 0xd1, 0x0c, 0x56, 0xc1, 0xfb, 0x04, 0x14, 0xc4, 0x25, 0x67, 0x13, 0x81, 0x7f,
	0xb1, 0x7a, 0x84, 0x5f, 0x67, 0x79, 0x0c, 0x1e, 0xf4, 0x08, 0xa2, 0xe6, 0xa5, 0xd3, 0x44, 0x1f,
	0xe8, 0xfb, 0xa4, 0x66, 0xea, 0x9f, 0xc5, 0x15, 0x9f, 0x05, 0xa0, 0x50, 0x9d, 0x1e, 0xf3, 0xcd,
	0xfc, 0xeb, 0xfb, 0xe9, 0xfc, 0x91, 0xc0, 0x2b, 0xd8, 0xa9, 0x54, 0x6c, 0xae, 0x9f, 0x1b, 0x33,
	0x84, 0xfd, 0xb4, 0x95, 0xaf, 0x38, 0x76, 0xe9, 0xed, 0x7c, 0xd7, 0xd6, 0xac, 0x0d, 0x76, 0x23,
	0xf6, 0x70, 0xf8, 0x09, 0x00, 0x00, 0xff, 0xff, 0x19, 0xd4, 0x7b, 0xb6, 0x1b, 0x01, 0x00, 0x00,
}
