// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/syzoj/protoc-gen-gotype/gotype"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Database models
type User struct {
	Id                   *UserRef  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserName             *string   `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	Auth                 *UserAuth `protobuf:"bytes,3,opt,name=auth" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() UserRef {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *User) GetAuth() *UserAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type Problem struct {
	Id                   *ProblemRef `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title                *string     `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Problem) Reset()         { *m = Problem{} }
func (m *Problem) String() string { return proto.CompactTextString(m) }
func (*Problem) ProtoMessage()    {}
func (*Problem) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *Problem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Problem.Unmarshal(m, b)
}
func (m *Problem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Problem.Marshal(b, m, deterministic)
}
func (m *Problem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Problem.Merge(m, src)
}
func (m *Problem) XXX_Size() int {
	return xxx_messageInfo_Problem.Size(m)
}
func (m *Problem) XXX_DiscardUnknown() {
	xxx_messageInfo_Problem.DiscardUnknown(m)
}

var xxx_messageInfo_Problem proto.InternalMessageInfo

func (m *Problem) GetId() ProblemRef {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Problem) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

type Submission struct {
	Id                   *SubmissionRef `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Submission) Reset()         { *m = Submission{} }
func (m *Submission) String() string { return proto.CompactTextString(m) }
func (*Submission) ProtoMessage()    {}
func (*Submission) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *Submission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Submission.Unmarshal(m, b)
}
func (m *Submission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Submission.Marshal(b, m, deterministic)
}
func (m *Submission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Submission.Merge(m, src)
}
func (m *Submission) XXX_Size() int {
	return xxx_messageInfo_Submission.Size(m)
}
func (m *Submission) XXX_DiscardUnknown() {
	xxx_messageInfo_Submission.DiscardUnknown(m)
}

var xxx_messageInfo_Submission proto.InternalMessageInfo

func (m *Submission) GetId() SubmissionRef {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

// Nested messages
type UserAuth struct {
	PasswordHash         []byte   `protobuf:"bytes,1,opt,name=password_hash,json=passwordHash" json:"password_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAuth) Reset()         { *m = UserAuth{} }
func (m *UserAuth) String() string { return proto.CompactTextString(m) }
func (*UserAuth) ProtoMessage()    {}
func (*UserAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

func (m *UserAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAuth.Unmarshal(m, b)
}
func (m *UserAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAuth.Marshal(b, m, deterministic)
}
func (m *UserAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAuth.Merge(m, src)
}
func (m *UserAuth) XXX_Size() int {
	return xxx_messageInfo_UserAuth.Size(m)
}
func (m *UserAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAuth.DiscardUnknown(m)
}

var xxx_messageInfo_UserAuth proto.InternalMessageInfo

func (m *UserAuth) GetPasswordHash() []byte {
	if m != nil {
		return m.PasswordHash
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "syzoj.server.User")
	proto.RegisterType((*Problem)(nil), "syzoj.server.Problem")
	proto.RegisterType((*Submission)(nil), "syzoj.server.Submission")
	proto.RegisterType((*UserAuth)(nil), "syzoj.server.UserAuth")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0x69, 0x9d, 0x6c, 0x3b, 0xed, 0x04, 0x83, 0x48, 0x71, 0x20, 0xb3, 0x7a, 0x31, 0x84,
	0xb5, 0xe0, 0x0b, 0x88, 0xbb, 0xf2, 0x4a, 0xa4, 0xe2, 0x45, 0xbd, 0x19, 0xa9, 0x8d, 0x4d, 0xa4,
	0x69, 0x4a, 0x4e, 0xaa, 0xcc, 0x47, 0xe8, 0x1b, 0xf4, 0x6d, 0xa5, 0xed, 0xca, 0x7a, 0x13, 0xc8,
	0xff, 0xff, 0xf9, 0xbf, 0x9c, 0x03, 0x8e, 0x54, 0x29, 0xcb, 0x83, 0x52, 0x2b, 0xa3, 0x88, 0x8b,
	0xfb, 0x3f, 0xf5, 0x1d, 0x20, 0xd3, 0x3f, 0x4c, 0x5f, 0xb9, 0x99, 0x32, 0xfb, 0x92, 0xf5, 0x9e,
	0x9f, 0xc3, 0xe4, 0x1d, 0x99, 0x26, 0x4b, 0xb0, 0x45, 0xea, 0x59, 0x2b, 0x6b, 0x3d, 0xdf, 0x3a,
	0x75, 0x13, 0x4f, 0x5b, 0x35, 0x62, 0x5f, 0x91, 0x2d, 0x52, 0xb2, 0x84, 0x79, 0x85, 0x4c, 0xef,
	0x0a, 0x2a, 0x99, 0x67, 0xb7, 0x99, 0x68, 0xd6, 0x0a, 0x2f, 0x54, 0x32, 0x72, 0x0f, 0x13, 0x5a,
	0x19, 0xee, 0x9d, 0xac, 0xac, 0xb5, 0xf3, 0x70, 0x19, 0x8c, 0x61, 0x41, 0xdb, 0xf2, 0x54, 0x19,
	0x1e, 0x75, 0x19, 0xff, 0x11, 0xa6, 0xaf, 0x5a, 0x25, 0x39, 0x93, 0xe4, 0x7a, 0x04, 0x3c, 0xab,
	0x9b, 0x18, 0x0e, 0xc6, 0xc0, 0xbc, 0x80, 0x53, 0x23, 0x4c, 0x3e, 0xf0, 0xfa, 0x8b, 0x1f, 0x02,
	0xbc, 0x55, 0x89, 0x14, 0x88, 0x42, 0x15, 0xe4, 0x66, 0xd4, 0x71, 0x5e, 0x37, 0xf1, 0xe2, 0xe8,
	0x1d, 0x6a, 0xfc, 0x10, 0x66, 0xc3, 0x1f, 0xc8, 0x2d, 0x2c, 0x4a, 0x8a, 0xf8, 0xab, 0x74, 0xba,
	0xe3, 0x14, 0x79, 0xf7, 0xd2, 0x8d, 0xdc, 0x41, 0x7c, 0xa6, 0xc8, 0xb7, 0x77, 0x1f, 0x7e, 0x26,
	0x0c, 0xaf, 0x92, 0xe0, 0x53, 0xc9, 0xb0, 0x1b, 0xa6, 0x3f, 0x37, 0x45, 0xb6, 0xc9, 0x54, 0xd8,
	0x2d, 0xf6, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x83, 0x80, 0x68, 0xd1, 0x60, 0x01, 0x00, 0x00,
}
