// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	duration "github.com/golang/protobuf/ptypes/duration"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	Session              *ResponseSession `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Error                *string          `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Data                 *any.Any         `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSession() *ResponseSession {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *Response) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *Response) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResponseSession struct {
	UserName             *string  `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	LoggedIn             *bool    `protobuf:"varint,2,opt,name=logged_in,json=loggedIn" json:"logged_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseSession) Reset()         { *m = ResponseSession{} }
func (m *ResponseSession) String() string { return proto.CompactTextString(m) }
func (*ResponseSession) ProtoMessage()    {}
func (*ResponseSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *ResponseSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSession.Unmarshal(m, b)
}
func (m *ResponseSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSession.Marshal(b, m, deterministic)
}
func (m *ResponseSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSession.Merge(m, src)
}
func (m *ResponseSession) XXX_Size() int {
	return xxx_messageInfo_ResponseSession.Size(m)
}
func (m *ResponseSession) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSession.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSession proto.InternalMessageInfo

func (m *ResponseSession) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *ResponseSession) GetLoggedIn() bool {
	if m != nil && m.LoggedIn != nil {
		return *m.LoggedIn
	}
	return false
}

type LoginRequest struct {
	Username             *string  `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password             *string  `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type RegisterRequest struct {
	Username             *string  `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password             *string  `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Email                *string  `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

type ProblemDbResponse struct {
	Problems             []*ProblemDbResponseProblemEntry `protobuf:"bytes,1,rep,name=problems" json:"problems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ProblemDbResponse) Reset()         { *m = ProblemDbResponse{} }
func (m *ProblemDbResponse) String() string { return proto.CompactTextString(m) }
func (*ProblemDbResponse) ProtoMessage()    {}
func (*ProblemDbResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *ProblemDbResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemDbResponse.Unmarshal(m, b)
}
func (m *ProblemDbResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemDbResponse.Marshal(b, m, deterministic)
}
func (m *ProblemDbResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemDbResponse.Merge(m, src)
}
func (m *ProblemDbResponse) XXX_Size() int {
	return xxx_messageInfo_ProblemDbResponse.Size(m)
}
func (m *ProblemDbResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemDbResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemDbResponse proto.InternalMessageInfo

func (m *ProblemDbResponse) GetProblems() []*ProblemDbResponseProblemEntry {
	if m != nil {
		return m.Problems
	}
	return nil
}

type ProblemDbResponseProblemEntry struct {
	ProblemId            *ObjectID `protobuf:"bytes,1,opt,name=problem_id,json=problemId" json:"problem_id,omitempty"`
	Title                *string   `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProblemDbResponseProblemEntry) Reset()         { *m = ProblemDbResponseProblemEntry{} }
func (m *ProblemDbResponseProblemEntry) String() string { return proto.CompactTextString(m) }
func (*ProblemDbResponseProblemEntry) ProtoMessage()    {}
func (*ProblemDbResponseProblemEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *ProblemDbResponseProblemEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemDbResponseProblemEntry.Unmarshal(m, b)
}
func (m *ProblemDbResponseProblemEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemDbResponseProblemEntry.Marshal(b, m, deterministic)
}
func (m *ProblemDbResponseProblemEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemDbResponseProblemEntry.Merge(m, src)
}
func (m *ProblemDbResponseProblemEntry) XXX_Size() int {
	return xxx_messageInfo_ProblemDbResponseProblemEntry.Size(m)
}
func (m *ProblemDbResponseProblemEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemDbResponseProblemEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemDbResponseProblemEntry proto.InternalMessageInfo

func (m *ProblemDbResponseProblemEntry) GetProblemId() *ObjectID {
	if m != nil {
		return m.ProblemId
	}
	return nil
}

func (m *ProblemDbResponseProblemEntry) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

type ProblemDbNewRequest struct {
	Title                *string  `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Statement            *string  `protobuf:"bytes,2,opt,name=statement" json:"statement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProblemDbNewRequest) Reset()         { *m = ProblemDbNewRequest{} }
func (m *ProblemDbNewRequest) String() string { return proto.CompactTextString(m) }
func (*ProblemDbNewRequest) ProtoMessage()    {}
func (*ProblemDbNewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *ProblemDbNewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemDbNewRequest.Unmarshal(m, b)
}
func (m *ProblemDbNewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemDbNewRequest.Marshal(b, m, deterministic)
}
func (m *ProblemDbNewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemDbNewRequest.Merge(m, src)
}
func (m *ProblemDbNewRequest) XXX_Size() int {
	return xxx_messageInfo_ProblemDbNewRequest.Size(m)
}
func (m *ProblemDbNewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemDbNewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemDbNewRequest proto.InternalMessageInfo

func (m *ProblemDbNewRequest) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *ProblemDbNewRequest) GetStatement() string {
	if m != nil && m.Statement != nil {
		return *m.Statement
	}
	return ""
}

type ProblemDbNewResponse struct {
	ProblemId            *ObjectID `protobuf:"bytes,1,opt,name=problem_id,json=problemId" json:"problem_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProblemDbNewResponse) Reset()         { *m = ProblemDbNewResponse{} }
func (m *ProblemDbNewResponse) String() string { return proto.CompactTextString(m) }
func (*ProblemDbNewResponse) ProtoMessage()    {}
func (*ProblemDbNewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *ProblemDbNewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemDbNewResponse.Unmarshal(m, b)
}
func (m *ProblemDbNewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemDbNewResponse.Marshal(b, m, deterministic)
}
func (m *ProblemDbNewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemDbNewResponse.Merge(m, src)
}
func (m *ProblemDbNewResponse) XXX_Size() int {
	return xxx_messageInfo_ProblemDbNewResponse.Size(m)
}
func (m *ProblemDbNewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemDbNewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemDbNewResponse proto.InternalMessageInfo

func (m *ProblemDbNewResponse) GetProblemId() *ObjectID {
	if m != nil {
		return m.ProblemId
	}
	return nil
}

type ProblemDbViewResponse struct {
	ProblemId            *ObjectID `protobuf:"bytes,1,opt,name=problem_id,json=problemId" json:"problem_id,omitempty"`
	Title                *string   `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Statement            *string   `protobuf:"bytes,3,opt,name=statement" json:"statement,omitempty"`
	CanSubmit            *bool     `protobuf:"varint,4,opt,name=can_submit,json=canSubmit" json:"can_submit,omitempty"`
	IsOwner              *bool     `protobuf:"varint,5,opt,name=is_owner,json=isOwner" json:"is_owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProblemDbViewResponse) Reset()         { *m = ProblemDbViewResponse{} }
func (m *ProblemDbViewResponse) String() string { return proto.CompactTextString(m) }
func (*ProblemDbViewResponse) ProtoMessage()    {}
func (*ProblemDbViewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *ProblemDbViewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemDbViewResponse.Unmarshal(m, b)
}
func (m *ProblemDbViewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemDbViewResponse.Marshal(b, m, deterministic)
}
func (m *ProblemDbViewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemDbViewResponse.Merge(m, src)
}
func (m *ProblemDbViewResponse) XXX_Size() int {
	return xxx_messageInfo_ProblemDbViewResponse.Size(m)
}
func (m *ProblemDbViewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemDbViewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemDbViewResponse proto.InternalMessageInfo

func (m *ProblemDbViewResponse) GetProblemId() *ObjectID {
	if m != nil {
		return m.ProblemId
	}
	return nil
}

func (m *ProblemDbViewResponse) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *ProblemDbViewResponse) GetStatement() string {
	if m != nil && m.Statement != nil {
		return *m.Statement
	}
	return ""
}

func (m *ProblemDbViewResponse) GetCanSubmit() bool {
	if m != nil && m.CanSubmit != nil {
		return *m.CanSubmit
	}
	return false
}

func (m *ProblemDbViewResponse) GetIsOwner() bool {
	if m != nil && m.IsOwner != nil {
		return *m.IsOwner
	}
	return false
}

type ProblemDbEditRequest struct {
	Title                *string  `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Statement            *string  `protobuf:"bytes,2,opt,name=statement" json:"statement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProblemDbEditRequest) Reset()         { *m = ProblemDbEditRequest{} }
func (m *ProblemDbEditRequest) String() string { return proto.CompactTextString(m) }
func (*ProblemDbEditRequest) ProtoMessage()    {}
func (*ProblemDbEditRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *ProblemDbEditRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemDbEditRequest.Unmarshal(m, b)
}
func (m *ProblemDbEditRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemDbEditRequest.Marshal(b, m, deterministic)
}
func (m *ProblemDbEditRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemDbEditRequest.Merge(m, src)
}
func (m *ProblemDbEditRequest) XXX_Size() int {
	return xxx_messageInfo_ProblemDbEditRequest.Size(m)
}
func (m *ProblemDbEditRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemDbEditRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemDbEditRequest proto.InternalMessageInfo

func (m *ProblemDbEditRequest) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *ProblemDbEditRequest) GetStatement() string {
	if m != nil && m.Statement != nil {
		return *m.Statement
	}
	return ""
}

type ProblemDbViewSubmitRequest struct {
	Content              *SubmissionContent `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProblemDbViewSubmitRequest) Reset()         { *m = ProblemDbViewSubmitRequest{} }
func (m *ProblemDbViewSubmitRequest) String() string { return proto.CompactTextString(m) }
func (*ProblemDbViewSubmitRequest) ProtoMessage()    {}
func (*ProblemDbViewSubmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *ProblemDbViewSubmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemDbViewSubmitRequest.Unmarshal(m, b)
}
func (m *ProblemDbViewSubmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemDbViewSubmitRequest.Marshal(b, m, deterministic)
}
func (m *ProblemDbViewSubmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemDbViewSubmitRequest.Merge(m, src)
}
func (m *ProblemDbViewSubmitRequest) XXX_Size() int {
	return xxx_messageInfo_ProblemDbViewSubmitRequest.Size(m)
}
func (m *ProblemDbViewSubmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemDbViewSubmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemDbViewSubmitRequest proto.InternalMessageInfo

func (m *ProblemDbViewSubmitRequest) GetContent() *SubmissionContent {
	if m != nil {
		return m.Content
	}
	return nil
}

type ProblemDbViewSubmitResponse struct {
	SubmissionId         *ObjectID `protobuf:"bytes,1,opt,name=submission_id,json=submissionId" json:"submission_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProblemDbViewSubmitResponse) Reset()         { *m = ProblemDbViewSubmitResponse{} }
func (m *ProblemDbViewSubmitResponse) String() string { return proto.CompactTextString(m) }
func (*ProblemDbViewSubmitResponse) ProtoMessage()    {}
func (*ProblemDbViewSubmitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *ProblemDbViewSubmitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemDbViewSubmitResponse.Unmarshal(m, b)
}
func (m *ProblemDbViewSubmitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemDbViewSubmitResponse.Marshal(b, m, deterministic)
}
func (m *ProblemDbViewSubmitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemDbViewSubmitResponse.Merge(m, src)
}
func (m *ProblemDbViewSubmitResponse) XXX_Size() int {
	return xxx_messageInfo_ProblemDbViewSubmitResponse.Size(m)
}
func (m *ProblemDbViewSubmitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemDbViewSubmitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemDbViewSubmitResponse proto.InternalMessageInfo

func (m *ProblemDbViewSubmitResponse) GetSubmissionId() *ObjectID {
	if m != nil {
		return m.SubmissionId
	}
	return nil
}

type SubmissionsResponse struct {
	Submissions          []*SubmissionsResponseSubmissionEntry `protobuf:"bytes,1,rep,name=submissions" json:"submissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *SubmissionsResponse) Reset()         { *m = SubmissionsResponse{} }
func (m *SubmissionsResponse) String() string { return proto.CompactTextString(m) }
func (*SubmissionsResponse) ProtoMessage()    {}
func (*SubmissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *SubmissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionsResponse.Unmarshal(m, b)
}
func (m *SubmissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionsResponse.Marshal(b, m, deterministic)
}
func (m *SubmissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionsResponse.Merge(m, src)
}
func (m *SubmissionsResponse) XXX_Size() int {
	return xxx_messageInfo_SubmissionsResponse.Size(m)
}
func (m *SubmissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionsResponse proto.InternalMessageInfo

func (m *SubmissionsResponse) GetSubmissions() []*SubmissionsResponseSubmissionEntry {
	if m != nil {
		return m.Submissions
	}
	return nil
}

type SubmissionsResponseSubmissionEntry struct {
	SubmissionId         *ObjectID `protobuf:"bytes,1,opt,name=submission_id,json=submissionId" json:"submission_id,omitempty"`
	ProblemId            *ObjectID `protobuf:"bytes,2,opt,name=problem_id,json=problemId" json:"problem_id,omitempty"`
	UserId               *ObjectID `protobuf:"bytes,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ProblemTitle         *string   `protobuf:"bytes,4,opt,name=problem_title,json=problemTitle" json:"problem_title,omitempty"`
	UserUsername         *string   `protobuf:"bytes,5,opt,name=user_username,json=userUsername" json:"user_username,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SubmissionsResponseSubmissionEntry) Reset()         { *m = SubmissionsResponseSubmissionEntry{} }
func (m *SubmissionsResponseSubmissionEntry) String() string { return proto.CompactTextString(m) }
func (*SubmissionsResponseSubmissionEntry) ProtoMessage()    {}
func (*SubmissionsResponseSubmissionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *SubmissionsResponseSubmissionEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionsResponseSubmissionEntry.Unmarshal(m, b)
}
func (m *SubmissionsResponseSubmissionEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionsResponseSubmissionEntry.Marshal(b, m, deterministic)
}
func (m *SubmissionsResponseSubmissionEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionsResponseSubmissionEntry.Merge(m, src)
}
func (m *SubmissionsResponseSubmissionEntry) XXX_Size() int {
	return xxx_messageInfo_SubmissionsResponseSubmissionEntry.Size(m)
}
func (m *SubmissionsResponseSubmissionEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionsResponseSubmissionEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionsResponseSubmissionEntry proto.InternalMessageInfo

func (m *SubmissionsResponseSubmissionEntry) GetSubmissionId() *ObjectID {
	if m != nil {
		return m.SubmissionId
	}
	return nil
}

func (m *SubmissionsResponseSubmissionEntry) GetProblemId() *ObjectID {
	if m != nil {
		return m.ProblemId
	}
	return nil
}

func (m *SubmissionsResponseSubmissionEntry) GetUserId() *ObjectID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *SubmissionsResponseSubmissionEntry) GetProblemTitle() string {
	if m != nil && m.ProblemTitle != nil {
		return *m.ProblemTitle
	}
	return ""
}

func (m *SubmissionsResponseSubmissionEntry) GetUserUsername() string {
	if m != nil && m.UserUsername != nil {
		return *m.UserUsername
	}
	return ""
}

type SubmissionViewResponse struct {
	SubmissionContent    *SubmissionContent `protobuf:"bytes,1,opt,name=submission_content,json=submissionContent" json:"submission_content,omitempty"`
	SubmissionResult     *SubmissionResult  `protobuf:"bytes,2,opt,name=submission_result,json=submissionResult" json:"submission_result,omitempty"`
	ProblemId            *ObjectID          `protobuf:"bytes,3,opt,name=problem_id,json=problemId" json:"problem_id,omitempty"`
	ProblemTitle         *string            `protobuf:"bytes,4,opt,name=problem_title,json=problemTitle" json:"problem_title,omitempty"`
	SubmitterId          *ObjectID          `protobuf:"bytes,5,opt,name=submitter_id,json=submitterId" json:"submitter_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SubmissionViewResponse) Reset()         { *m = SubmissionViewResponse{} }
func (m *SubmissionViewResponse) String() string { return proto.CompactTextString(m) }
func (*SubmissionViewResponse) ProtoMessage()    {}
func (*SubmissionViewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *SubmissionViewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionViewResponse.Unmarshal(m, b)
}
func (m *SubmissionViewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionViewResponse.Marshal(b, m, deterministic)
}
func (m *SubmissionViewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionViewResponse.Merge(m, src)
}
func (m *SubmissionViewResponse) XXX_Size() int {
	return xxx_messageInfo_SubmissionViewResponse.Size(m)
}
func (m *SubmissionViewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionViewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionViewResponse proto.InternalMessageInfo

func (m *SubmissionViewResponse) GetSubmissionContent() *SubmissionContent {
	if m != nil {
		return m.SubmissionContent
	}
	return nil
}

func (m *SubmissionViewResponse) GetSubmissionResult() *SubmissionResult {
	if m != nil {
		return m.SubmissionResult
	}
	return nil
}

func (m *SubmissionViewResponse) GetProblemId() *ObjectID {
	if m != nil {
		return m.ProblemId
	}
	return nil
}

func (m *SubmissionViewResponse) GetProblemTitle() string {
	if m != nil && m.ProblemTitle != nil {
		return *m.ProblemTitle
	}
	return ""
}

func (m *SubmissionViewResponse) GetSubmitterId() *ObjectID {
	if m != nil {
		return m.SubmitterId
	}
	return nil
}

type ContestsResponse struct {
	Contests             []*ContestsResponseContestEntry `protobuf:"bytes,1,rep,name=contests" json:"contests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ContestsResponse) Reset()         { *m = ContestsResponse{} }
func (m *ContestsResponse) String() string { return proto.CompactTextString(m) }
func (*ContestsResponse) ProtoMessage()    {}
func (*ContestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *ContestsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestsResponse.Unmarshal(m, b)
}
func (m *ContestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestsResponse.Marshal(b, m, deterministic)
}
func (m *ContestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestsResponse.Merge(m, src)
}
func (m *ContestsResponse) XXX_Size() int {
	return xxx_messageInfo_ContestsResponse.Size(m)
}
func (m *ContestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContestsResponse proto.InternalMessageInfo

func (m *ContestsResponse) GetContests() []*ContestsResponseContestEntry {
	if m != nil {
		return m.Contests
	}
	return nil
}

type ContestsResponseContestEntry struct {
	ContestTitle         *string   `protobuf:"bytes,1,opt,name=contest_title,json=contestTitle" json:"contest_title,omitempty"`
	Running              *bool     `protobuf:"varint,2,opt,name=running" json:"running,omitempty"`
	ContestId            *ObjectID `protobuf:"bytes,3,opt,name=contest_id,json=contestId" json:"contest_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ContestsResponseContestEntry) Reset()         { *m = ContestsResponseContestEntry{} }
func (m *ContestsResponseContestEntry) String() string { return proto.CompactTextString(m) }
func (*ContestsResponseContestEntry) ProtoMessage()    {}
func (*ContestsResponseContestEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}

func (m *ContestsResponseContestEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestsResponseContestEntry.Unmarshal(m, b)
}
func (m *ContestsResponseContestEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestsResponseContestEntry.Marshal(b, m, deterministic)
}
func (m *ContestsResponseContestEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestsResponseContestEntry.Merge(m, src)
}
func (m *ContestsResponseContestEntry) XXX_Size() int {
	return xxx_messageInfo_ContestsResponseContestEntry.Size(m)
}
func (m *ContestsResponseContestEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestsResponseContestEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ContestsResponseContestEntry proto.InternalMessageInfo

func (m *ContestsResponseContestEntry) GetContestTitle() string {
	if m != nil && m.ContestTitle != nil {
		return *m.ContestTitle
	}
	return ""
}

func (m *ContestsResponseContestEntry) GetRunning() bool {
	if m != nil && m.Running != nil {
		return *m.Running
	}
	return false
}

func (m *ContestsResponseContestEntry) GetContestId() *ObjectID {
	if m != nil {
		return m.ContestId
	}
	return nil
}

type ContestIndexResponse struct {
	ContestName          *string                        `protobuf:"bytes,1,opt,name=contest_name,json=contestName" json:"contest_name,omitempty"`
	ContestDescription   *string                        `protobuf:"bytes,2,opt,name=contest_description,json=contestDescription" json:"contest_description,omitempty"`
	Problems             []*ContestProblemEntryResponse `protobuf:"bytes,3,rep,name=problems" json:"problems,omitempty"`
	Running              *bool                          `protobuf:"varint,4,opt,name=running" json:"running,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ContestIndexResponse) Reset()         { *m = ContestIndexResponse{} }
func (m *ContestIndexResponse) String() string { return proto.CompactTextString(m) }
func (*ContestIndexResponse) ProtoMessage()    {}
func (*ContestIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}

func (m *ContestIndexResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestIndexResponse.Unmarshal(m, b)
}
func (m *ContestIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestIndexResponse.Marshal(b, m, deterministic)
}
func (m *ContestIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestIndexResponse.Merge(m, src)
}
func (m *ContestIndexResponse) XXX_Size() int {
	return xxx_messageInfo_ContestIndexResponse.Size(m)
}
func (m *ContestIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContestIndexResponse proto.InternalMessageInfo

func (m *ContestIndexResponse) GetContestName() string {
	if m != nil && m.ContestName != nil {
		return *m.ContestName
	}
	return ""
}

func (m *ContestIndexResponse) GetContestDescription() string {
	if m != nil && m.ContestDescription != nil {
		return *m.ContestDescription
	}
	return ""
}

func (m *ContestIndexResponse) GetProblems() []*ContestProblemEntryResponse {
	if m != nil {
		return m.Problems
	}
	return nil
}

func (m *ContestIndexResponse) GetRunning() bool {
	if m != nil && m.Running != nil {
		return *m.Running
	}
	return false
}

type ContestProblemEntryResponse struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ProblemTitle         *string  `protobuf:"bytes,2,opt,name=problem_title,json=problemTitle" json:"problem_title,omitempty"`
	ProblemStatement     *string  `protobuf:"bytes,3,opt,name=problem_statement,json=problemStatement" json:"problem_statement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContestProblemEntryResponse) Reset()         { *m = ContestProblemEntryResponse{} }
func (m *ContestProblemEntryResponse) String() string { return proto.CompactTextString(m) }
func (*ContestProblemEntryResponse) ProtoMessage()    {}
func (*ContestProblemEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{18}
}

func (m *ContestProblemEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestProblemEntryResponse.Unmarshal(m, b)
}
func (m *ContestProblemEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestProblemEntryResponse.Marshal(b, m, deterministic)
}
func (m *ContestProblemEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestProblemEntryResponse.Merge(m, src)
}
func (m *ContestProblemEntryResponse) XXX_Size() int {
	return xxx_messageInfo_ContestProblemEntryResponse.Size(m)
}
func (m *ContestProblemEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestProblemEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContestProblemEntryResponse proto.InternalMessageInfo

func (m *ContestProblemEntryResponse) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ContestProblemEntryResponse) GetProblemTitle() string {
	if m != nil && m.ProblemTitle != nil {
		return *m.ProblemTitle
	}
	return ""
}

func (m *ContestProblemEntryResponse) GetProblemStatement() string {
	if m != nil && m.ProblemStatement != nil {
		return *m.ProblemStatement
	}
	return ""
}

type ContestRanklistResponse struct {
	Ranklist             *ContestRanklist `protobuf:"bytes,1,opt,name=ranklist" json:"ranklist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ContestRanklistResponse) Reset()         { *m = ContestRanklistResponse{} }
func (m *ContestRanklistResponse) String() string { return proto.CompactTextString(m) }
func (*ContestRanklistResponse) ProtoMessage()    {}
func (*ContestRanklistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{19}
}

func (m *ContestRanklistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestRanklistResponse.Unmarshal(m, b)
}
func (m *ContestRanklistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestRanklistResponse.Marshal(b, m, deterministic)
}
func (m *ContestRanklistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestRanklistResponse.Merge(m, src)
}
func (m *ContestRanklistResponse) XXX_Size() int {
	return xxx_messageInfo_ContestRanklistResponse.Size(m)
}
func (m *ContestRanklistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestRanklistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContestRanklistResponse proto.InternalMessageInfo

func (m *ContestRanklistResponse) GetRanklist() *ContestRanklist {
	if m != nil {
		return m.Ranklist
	}
	return nil
}

type ContestRanklist struct {
	RanklistType         *string                 `protobuf:"bytes,1,opt,name=ranklist_type,json=ranklistType" json:"ranklist_type,omitempty"`
	Entries              []*ContestRanklistEntry `protobuf:"bytes,2,rep,name=entries" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ContestRanklist) Reset()         { *m = ContestRanklist{} }
func (m *ContestRanklist) String() string { return proto.CompactTextString(m) }
func (*ContestRanklist) ProtoMessage()    {}
func (*ContestRanklist) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{20}
}

func (m *ContestRanklist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestRanklist.Unmarshal(m, b)
}
func (m *ContestRanklist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestRanklist.Marshal(b, m, deterministic)
}
func (m *ContestRanklist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestRanklist.Merge(m, src)
}
func (m *ContestRanklist) XXX_Size() int {
	return xxx_messageInfo_ContestRanklist.Size(m)
}
func (m *ContestRanklist) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestRanklist.DiscardUnknown(m)
}

var xxx_messageInfo_ContestRanklist proto.InternalMessageInfo

func (m *ContestRanklist) GetRanklistType() string {
	if m != nil && m.RanklistType != nil {
		return *m.RanklistType
	}
	return ""
}

func (m *ContestRanklist) GetEntries() []*ContestRanklistEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type ContestRanklistEntry struct {
	UserId               *ObjectID          `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ScoreSum             *float64           `protobuf:"fixed64,2,opt,name=score_sum,json=scoreSum" json:"score_sum,omitempty"`
	PenaltyTime          *duration.Duration `protobuf:"bytes,3,opt,name=penalty_time,json=penaltyTime" json:"penalty_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ContestRanklistEntry) Reset()         { *m = ContestRanklistEntry{} }
func (m *ContestRanklistEntry) String() string { return proto.CompactTextString(m) }
func (*ContestRanklistEntry) ProtoMessage()    {}
func (*ContestRanklistEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{21}
}

func (m *ContestRanklistEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestRanklistEntry.Unmarshal(m, b)
}
func (m *ContestRanklistEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestRanklistEntry.Marshal(b, m, deterministic)
}
func (m *ContestRanklistEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestRanklistEntry.Merge(m, src)
}
func (m *ContestRanklistEntry) XXX_Size() int {
	return xxx_messageInfo_ContestRanklistEntry.Size(m)
}
func (m *ContestRanklistEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestRanklistEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ContestRanklistEntry proto.InternalMessageInfo

func (m *ContestRanklistEntry) GetUserId() *ObjectID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *ContestRanklistEntry) GetScoreSum() float64 {
	if m != nil && m.ScoreSum != nil {
		return *m.ScoreSum
	}
	return 0
}

func (m *ContestRanklistEntry) GetPenaltyTime() *duration.Duration {
	if m != nil {
		return m.PenaltyTime
	}
	return nil
}

type ContestProblemViewResponse struct {
	ProblemTitle         *string  `protobuf:"bytes,1,opt,name=problem_title,json=problemTitle" json:"problem_title,omitempty"`
	ProblemStatement     *string  `protobuf:"bytes,2,opt,name=problem_statement,json=problemStatement" json:"problem_statement,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContestProblemViewResponse) Reset()         { *m = ContestProblemViewResponse{} }
func (m *ContestProblemViewResponse) String() string { return proto.CompactTextString(m) }
func (*ContestProblemViewResponse) ProtoMessage()    {}
func (*ContestProblemViewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{22}
}

func (m *ContestProblemViewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestProblemViewResponse.Unmarshal(m, b)
}
func (m *ContestProblemViewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestProblemViewResponse.Marshal(b, m, deterministic)
}
func (m *ContestProblemViewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestProblemViewResponse.Merge(m, src)
}
func (m *ContestProblemViewResponse) XXX_Size() int {
	return xxx_messageInfo_ContestProblemViewResponse.Size(m)
}
func (m *ContestProblemViewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestProblemViewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContestProblemViewResponse proto.InternalMessageInfo

func (m *ContestProblemViewResponse) GetProblemTitle() string {
	if m != nil && m.ProblemTitle != nil {
		return *m.ProblemTitle
	}
	return ""
}

func (m *ContestProblemViewResponse) GetProblemStatement() string {
	if m != nil && m.ProblemStatement != nil {
		return *m.ProblemStatement
	}
	return ""
}

// Debug API
type DebugContestSubmitRequest struct {
	ContestId            *ObjectID `protobuf:"bytes,1,opt,name=contest_id,json=contestId" json:"contest_id,omitempty"`
	UserId               *ObjectID `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	SubmissionId         *ObjectID `protobuf:"bytes,3,opt,name=submission_id,json=submissionId" json:"submission_id,omitempty"`
	Name                 *string   `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DebugContestSubmitRequest) Reset()         { *m = DebugContestSubmitRequest{} }
func (m *DebugContestSubmitRequest) String() string { return proto.CompactTextString(m) }
func (*DebugContestSubmitRequest) ProtoMessage()    {}
func (*DebugContestSubmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{23}
}

func (m *DebugContestSubmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugContestSubmitRequest.Unmarshal(m, b)
}
func (m *DebugContestSubmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugContestSubmitRequest.Marshal(b, m, deterministic)
}
func (m *DebugContestSubmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugContestSubmitRequest.Merge(m, src)
}
func (m *DebugContestSubmitRequest) XXX_Size() int {
	return xxx_messageInfo_DebugContestSubmitRequest.Size(m)
}
func (m *DebugContestSubmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugContestSubmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DebugContestSubmitRequest proto.InternalMessageInfo

func (m *DebugContestSubmitRequest) GetContestId() *ObjectID {
	if m != nil {
		return m.ContestId
	}
	return nil
}

func (m *DebugContestSubmitRequest) GetUserId() *ObjectID {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *DebugContestSubmitRequest) GetSubmissionId() *ObjectID {
	if m != nil {
		return m.SubmissionId
	}
	return nil
}

func (m *DebugContestSubmitRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type ContestProblemSubmitRequest struct {
	Content              *SubmissionContent `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ContestProblemSubmitRequest) Reset()         { *m = ContestProblemSubmitRequest{} }
func (m *ContestProblemSubmitRequest) String() string { return proto.CompactTextString(m) }
func (*ContestProblemSubmitRequest) ProtoMessage()    {}
func (*ContestProblemSubmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{24}
}

func (m *ContestProblemSubmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestProblemSubmitRequest.Unmarshal(m, b)
}
func (m *ContestProblemSubmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestProblemSubmitRequest.Marshal(b, m, deterministic)
}
func (m *ContestProblemSubmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestProblemSubmitRequest.Merge(m, src)
}
func (m *ContestProblemSubmitRequest) XXX_Size() int {
	return xxx_messageInfo_ContestProblemSubmitRequest.Size(m)
}
func (m *ContestProblemSubmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestProblemSubmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContestProblemSubmitRequest proto.InternalMessageInfo

func (m *ContestProblemSubmitRequest) GetContent() *SubmissionContent {
	if m != nil {
		return m.Content
	}
	return nil
}

type ContestProblemSubmitResponse struct {
	SubmissionId         *ObjectID `protobuf:"bytes,1,opt,name=submission_id,json=submissionId" json:"submission_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ContestProblemSubmitResponse) Reset()         { *m = ContestProblemSubmitResponse{} }
func (m *ContestProblemSubmitResponse) String() string { return proto.CompactTextString(m) }
func (*ContestProblemSubmitResponse) ProtoMessage()    {}
func (*ContestProblemSubmitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{25}
}

func (m *ContestProblemSubmitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestProblemSubmitResponse.Unmarshal(m, b)
}
func (m *ContestProblemSubmitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestProblemSubmitResponse.Marshal(b, m, deterministic)
}
func (m *ContestProblemSubmitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestProblemSubmitResponse.Merge(m, src)
}
func (m *ContestProblemSubmitResponse) XXX_Size() int {
	return xxx_messageInfo_ContestProblemSubmitResponse.Size(m)
}
func (m *ContestProblemSubmitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestProblemSubmitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContestProblemSubmitResponse proto.InternalMessageInfo

func (m *ContestProblemSubmitResponse) GetSubmissionId() *ObjectID {
	if m != nil {
		return m.SubmissionId
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "syzoj.api.Response")
	proto.RegisterType((*ResponseSession)(nil), "syzoj.api.ResponseSession")
	proto.RegisterType((*LoginRequest)(nil), "syzoj.api.LoginRequest")
	proto.RegisterType((*RegisterRequest)(nil), "syzoj.api.RegisterRequest")
	proto.RegisterType((*ProblemDbResponse)(nil), "syzoj.api.ProblemDbResponse")
	proto.RegisterType((*ProblemDbResponseProblemEntry)(nil), "syzoj.api.ProblemDbResponseProblemEntry")
	proto.RegisterType((*ProblemDbNewRequest)(nil), "syzoj.api.ProblemDbNewRequest")
	proto.RegisterType((*ProblemDbNewResponse)(nil), "syzoj.api.ProblemDbNewResponse")
	proto.RegisterType((*ProblemDbViewResponse)(nil), "syzoj.api.ProblemDbViewResponse")
	proto.RegisterType((*ProblemDbEditRequest)(nil), "syzoj.api.ProblemDbEditRequest")
	proto.RegisterType((*ProblemDbViewSubmitRequest)(nil), "syzoj.api.ProblemDbViewSubmitRequest")
	proto.RegisterType((*ProblemDbViewSubmitResponse)(nil), "syzoj.api.ProblemDbViewSubmitResponse")
	proto.RegisterType((*SubmissionsResponse)(nil), "syzoj.api.SubmissionsResponse")
	proto.RegisterType((*SubmissionsResponseSubmissionEntry)(nil), "syzoj.api.SubmissionsResponseSubmissionEntry")
	proto.RegisterType((*SubmissionViewResponse)(nil), "syzoj.api.SubmissionViewResponse")
	proto.RegisterType((*ContestsResponse)(nil), "syzoj.api.ContestsResponse")
	proto.RegisterType((*ContestsResponseContestEntry)(nil), "syzoj.api.ContestsResponseContestEntry")
	proto.RegisterType((*ContestIndexResponse)(nil), "syzoj.api.ContestIndexResponse")
	proto.RegisterType((*ContestProblemEntryResponse)(nil), "syzoj.api.ContestProblemEntryResponse")
	proto.RegisterType((*ContestRanklistResponse)(nil), "syzoj.api.ContestRanklistResponse")
	proto.RegisterType((*ContestRanklist)(nil), "syzoj.api.ContestRanklist")
	proto.RegisterType((*ContestRanklistEntry)(nil), "syzoj.api.ContestRanklistEntry")
	proto.RegisterType((*ContestProblemViewResponse)(nil), "syzoj.api.ContestProblemViewResponse")
	proto.RegisterType((*DebugContestSubmitRequest)(nil), "syzoj.api.DebugContestSubmitRequest")
	proto.RegisterType((*ContestProblemSubmitRequest)(nil), "syzoj.api.ContestProblemSubmitRequest")
	proto.RegisterType((*ContestProblemSubmitResponse)(nil), "syzoj.api.ContestProblemSubmitResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 1075 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xd6, 0xda, 0x0e, 0xb6, 0x8f, 0x13, 0x25, 0xd9, 0x04, 0x70, 0x9c, 0xa6, 0x84, 0xa9, 0x54,
	0x2c, 0xa1, 0xd8, 0x52, 0x84, 0x50, 0x91, 0x10, 0x12, 0xad, 0x8b, 0xe4, 0x02, 0x4d, 0xd9, 0x84,
	0x56, 0x20, 0xc1, 0x6a, 0xed, 0x9d, 0x2e, 0x13, 0xbc, 0x33, 0xdb, 0x9d, 0x59, 0x82, 0xb9, 0x42,
	0xe2, 0x21, 0xb8, 0xe1, 0x96, 0xe7, 0xe0, 0x96, 0x4b, 0x5e, 0x80, 0x77, 0x41, 0x3b, 0x3f, 0xfb,
	0x67, 0x27, 0x75, 0x48, 0x6e, 0x2c, 0xcf, 0x39, 0xdf, 0x39, 0x73, 0xe6, 0x3b, 0x7f, 0x0b, 0x6d,
	0x2f, 0x22, 0x83, 0x28, 0x66, 0x82, 0xd9, 0x6d, 0x3e, 0xff, 0x85, 0x9d, 0x0f, 0xbc, 0x88, 0xf4,
	0xf6, 0x02, 0xc6, 0x82, 0x19, 0x1e, 0x4a, 0xc5, 0x24, 0x79, 0x39, 0xf4, 0xe8, 0x5c, 0xa1, 0x7a,
	0x77, 0xab, 0x2a, 0x3f, 0x89, 0x3d, 0x41, 0x18, 0xd5, 0xfa, 0xcd, 0x28, 0x26, 0x21, 0x11, 0xe4,
	0x27, 0xac, 0x05, 0x9d, 0xf3, 0xc4, 0x0f, 0xf4, 0x01, 0xfd, 0x6a, 0x41, 0xcb, 0xc1, 0x3c, 0x62,
	0x94, 0x63, 0xfb, 0x03, 0x68, 0x72, 0xcc, 0x39, 0x61, 0xb4, 0x6b, 0x1d, 0x5a, 0xfd, 0xce, 0x71,
	0x6f, 0x90, 0x85, 0x30, 0x30, 0xa8, 0x53, 0x85, 0x70, 0x0c, 0xd4, 0xde, 0x85, 0x35, 0x1c, 0xc7,
	0x2c, 0xee, 0xd6, 0x0e, 0xad, 0x7e, 0xdb, 0x51, 0x07, 0xbb, 0x0f, 0x0d, 0xdf, 0x13, 0x5e, 0xb7,
	0x2e, 0x1d, 0xed, 0x0e, 0x54, 0x94, 0x03, 0x13, 0xe5, 0xe0, 0x53, 0x3a, 0x77, 0x24, 0x02, 0x7d,
	0x0e, 0x9b, 0x15, 0xdf, 0xf6, 0x3e, 0xb4, 0x13, 0x8e, 0x63, 0x97, 0x7a, 0x21, 0x96, 0xa1, 0xb4,
	0x9d, 0x56, 0x2a, 0x78, 0xea, 0x85, 0x38, 0x55, 0xce, 0x58, 0x10, 0x60, 0xdf, 0x25, 0x54, 0xde,
	0xd9, 0x72, 0x5a, 0x4a, 0x30, 0xa6, 0xe8, 0x33, 0x58, 0xff, 0x82, 0x05, 0x84, 0x3a, 0xf8, 0x55,
	0x82, 0xb9, 0xb0, 0x7b, 0x20, 0x0d, 0xab, 0x8e, 0xd2, 0x73, 0xaa, 0x8b, 0x3c, 0xce, 0x2f, 0x58,
	0xec, 0xeb, 0xd8, 0xb3, 0x33, 0x72, 0xd3, 0xa0, 0x02, 0xc2, 0x05, 0x8e, 0x6f, 0xe8, 0x4a, 0xf2,
	0x13, 0x7a, 0x64, 0x26, 0xa9, 0x48, 0xf9, 0x49, 0x0f, 0xe8, 0x1b, 0xd8, 0x7e, 0x16, 0xb3, 0xc9,
	0x0c, 0x87, 0xa3, 0x49, 0x96, 0x80, 0x11, 0xb4, 0x22, 0x25, 0xe4, 0x5d, 0xeb, 0xb0, 0xde, 0xef,
	0x1c, 0xf7, 0x0b, 0x19, 0x58, 0xc0, 0x6b, 0xc1, 0x63, 0x2a, 0xe2, 0xb9, 0x93, 0x59, 0x22, 0x06,
	0x07, 0x57, 0x42, 0xed, 0x07, 0x00, 0x1a, 0xec, 0x12, 0x5f, 0xa7, 0x7a, 0x4f, 0x5f, 0x94, 0x57,
	0xcb, 0xc9, 0xe4, 0x1c, 0x4f, 0xc5, 0x78, 0xe4, 0xb4, 0x35, 0x78, 0x2c, 0xdf, 0x22, 0x88, 0x98,
	0x61, 0x93, 0x6b, 0x79, 0x40, 0x63, 0xd8, 0xc9, 0x2e, 0x7c, 0x8a, 0x2f, 0x0c, 0x61, 0x19, 0xd8,
	0x2a, 0x80, 0xed, 0x3b, 0xd0, 0xe6, 0xc2, 0x13, 0x38, 0xc4, 0x54, 0x68, 0x37, 0xb9, 0x00, 0x3d,
	0x83, 0xdd, 0xb2, 0x2b, 0xcd, 0xcc, 0xff, 0x0e, 0x19, 0xfd, 0x65, 0xc1, 0x9b, 0x99, 0xcb, 0xe7,
	0xe4, 0x36, 0x7c, 0x2e, 0xa7, 0xa1, 0xfc, 0xb2, 0x7a, 0xe5, 0x65, 0xf6, 0x01, 0xc0, 0xd4, 0xa3,
	0x2e, 0x4f, 0x26, 0x21, 0x11, 0xdd, 0x86, 0xac, 0xdb, 0xf6, 0xd4, 0xa3, 0xa7, 0x52, 0x60, 0xef,
	0x41, 0x8b, 0x70, 0x97, 0x5d, 0x50, 0x1c, 0x77, 0xd7, 0xa4, 0xb2, 0x49, 0xf8, 0x49, 0x7a, 0x44,
	0x4f, 0x0a, 0x9c, 0x3c, 0xf6, 0x89, 0xb8, 0x09, 0xbf, 0xcf, 0xa1, 0x57, 0x22, 0x43, 0xdd, 0x6e,
	0x3c, 0x3e, 0x80, 0xe6, 0x94, 0x51, 0x91, 0x5a, 0x2a, 0x3a, 0xee, 0x6a, 0x3a, 0xd4, 0xc8, 0x90,
	0x60, 0xd9, 0xa1, 0x8f, 0x14, 0xca, 0x31, 0x70, 0xf4, 0x1d, 0xec, 0x2f, 0xf5, 0xab, 0xa9, 0xfe,
	0x04, 0x36, 0x78, 0x66, 0xbc, 0x12, 0xdb, 0xeb, 0x39, 0x7e, 0xec, 0xa3, 0x97, 0xb0, 0x93, 0x5f,
	0xce, 0x33, 0xb7, 0x27, 0xd0, 0xc9, 0x61, 0xa6, 0x65, 0x8e, 0x0a, 0x2d, 0xb3, 0xc4, 0x28, 0x17,
	0xa9, 0xbe, 0x29, 0x7a, 0x40, 0x7f, 0xd4, 0x00, 0xbd, 0xde, 0xe6, 0xa6, 0xcf, 0xa9, 0x54, 0x5e,
	0xed, 0x1a, 0x95, 0x77, 0x0c, 0x4d, 0x39, 0x19, 0x89, 0xaf, 0x27, 0xeb, 0x15, 0x66, 0x6f, 0xa4,
	0xc8, 0xb1, 0x6f, 0xdf, 0x83, 0x0d, 0x73, 0x9b, 0xaa, 0x97, 0x86, 0xac, 0x8a, 0x75, 0x2d, 0x3c,
	0x93, 0x65, 0x73, 0x0f, 0x36, 0xa4, 0xe3, 0x6c, 0xc4, 0xad, 0x29, 0x50, 0x7a, 0xfe, 0x5a, 0xcb,
	0xd0, 0x3f, 0x35, 0x78, 0x2b, 0xe7, 0xa2, 0xd4, 0x4c, 0x5f, 0x82, 0x5d, 0xa0, 0xe4, 0x7a, 0x55,
	0xb4, 0xcd, 0xab, 0x22, 0xfb, 0x09, 0x14, 0x84, 0x6e, 0x8c, 0x79, 0x32, 0x13, 0x9a, 0xa8, 0x83,
	0x4b, 0xbc, 0x39, 0x12, 0xe4, 0x6c, 0xf1, 0x8a, 0xa4, 0xc2, 0x76, 0xfd, 0x1a, 0x6c, 0xaf, 0xc4,
	0xdc, 0xc7, 0xa0, 0x92, 0x2b, 0x84, 0xca, 0xcb, 0xda, 0xeb, 0x2e, 0xe8, 0x64, 0xf0, 0xb1, 0x8f,
	0x5e, 0xc0, 0x96, 0x7c, 0x33, 0x17, 0x79, 0x59, 0x3f, 0x82, 0xd6, 0x54, 0xcb, 0x74, 0x4d, 0xbf,
	0x57, 0xa8, 0xe9, 0x2a, 0x5c, 0x9f, 0xf5, 0x16, 0x30, 0x86, 0xe8, 0x77, 0x0b, 0xee, 0x5c, 0x05,
	0x4d, 0x1f, 0xa7, 0xc1, 0x6e, 0x71, 0x8c, 0xac, 0x6b, 0xa1, 0x7a, 0x5c, 0x17, 0x9a, 0x71, 0x42,
	0x29, 0xa1, 0x81, 0x5e, 0xb5, 0xe6, 0x98, 0xb2, 0x6a, 0xcc, 0x57, 0x62, 0x55, 0x83, 0xc7, 0x3e,
	0xfa, 0xdb, 0x82, 0x5d, 0x1d, 0xc9, 0x98, 0xfa, 0xf8, 0xe7, 0xec, 0xdd, 0xef, 0x82, 0xb9, 0xbc,
	0xb8, 0xf9, 0x3b, 0x5a, 0x26, 0x97, 0xff, 0x10, 0x76, 0x0c, 0xc4, 0xc7, 0x7c, 0x1a, 0x93, 0x28,
	0xfd, 0xd4, 0xd1, 0x73, 0xce, 0xd6, 0xaa, 0x51, 0xae, 0xb1, 0x1f, 0x16, 0x56, 0x6a, 0x5d, 0x72,
	0x79, 0x7f, 0x91, 0xcb, 0xd2, 0x22, 0xd5, 0xd1, 0xe4, 0x0b, 0xb5, 0x48, 0x42, 0xa3, 0x44, 0x02,
	0xfa, 0xcd, 0x82, 0xfd, 0x2b, 0x7c, 0xd8, 0x36, 0x34, 0x0a, 0x2f, 0x91, 0xff, 0x17, 0x8b, 0xaa,
	0xb6, 0xa4, 0xa8, 0xde, 0x87, 0x6d, 0x03, 0xaa, 0xee, 0x94, 0x2d, 0xad, 0x38, 0xcd, 0x86, 0xfa,
	0x57, 0xf0, 0xb6, 0x0e, 0xc2, 0xf1, 0xe8, 0x8f, 0x33, 0xc2, 0xf3, 0xc1, 0xfb, 0x21, 0xb4, 0x62,
	0x2d, 0x5b, 0xf2, 0x4d, 0x57, 0xb5, 0xca, 0xb0, 0xe8, 0x15, 0x6c, 0x56, 0x94, 0x69, 0xdc, 0x46,
	0xed, 0x8a, 0x79, 0x94, 0xd5, 0x8b, 0x11, 0x9e, 0xcd, 0x23, 0x6c, 0x7f, 0x04, 0x4d, 0x4c, 0x45,
	0x4c, 0x30, 0xef, 0xd6, 0x24, 0xdb, 0xef, 0x5c, 0x7e, 0x9d, 0xa2, 0xca, 0xe0, 0xd1, 0x9f, 0x79,
	0x59, 0x94, 0x10, 0xc5, 0x99, 0x67, 0xad, 0x3a, 0xf3, 0xf6, 0xa1, 0xcd, 0xa7, 0x2c, 0xc6, 0x2e,
	0x4f, 0x42, 0x49, 0xb0, 0xe5, 0xb4, 0xa4, 0xe0, 0x34, 0x09, 0xd3, 0x8e, 0x8d, 0x30, 0xf5, 0x66,
	0x62, 0xee, 0x0a, 0x12, 0xe2, 0xac, 0x78, 0xab, 0xdf, 0xa8, 0x23, 0xfd, 0x25, 0xed, 0x74, 0x34,
	0xfc, 0x8c, 0x84, 0x18, 0x51, 0xe8, 0x95, 0x53, 0x5e, 0x9a, 0x83, 0x0b, 0xd9, 0xb5, 0x56, 0xcd,
	0x6e, 0xed, 0x92, 0xec, 0xfe, 0x6b, 0xc1, 0xde, 0x08, 0x4f, 0x92, 0x40, 0xdf, 0x5a, 0x5d, 0xd9,
	0xc5, 0x36, 0xb4, 0x56, 0x6f, 0xc3, 0x22, 0xad, 0xb5, 0x55, 0x69, 0x5d, 0x58, 0x7c, 0xf5, 0xeb,
	0x2d, 0x3e, 0xd3, 0x0f, 0x8d, 0xbc, 0x1f, 0xd0, 0x8b, 0x6a, 0x0b, 0xdd, 0xd6, 0x37, 0xc9, 0xf7,
	0xd9, 0x00, 0xac, 0x38, 0xbe, 0x9d, 0x8f, 0x92, 0x87, 0xfd, 0x6f, 0xef, 0x07, 0x44, 0xfc, 0x90,
	0x4c, 0x06, 0x53, 0x16, 0x0e, 0xa5, 0x91, 0xfa, 0x3d, 0xa2, 0xc1, 0x51, 0xc0, 0x86, 0x5e, 0x14,
	0x0d, 0x43, 0xe6, 0xe3, 0xd9, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x2b, 0x12, 0xb9, 0xd5,
	0x0d, 0x00, 0x00,
}
