// Code generated by protoc-gen-go. DO NOT EDIT.
// source: judge.proto

package model

import (
	fmt "fmt"
	_ "github.com/amsokol/protoc-gen-gotag/tagger"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubmissionContent struct {
	Language             *string  `protobuf:"bytes,1,opt,name=language" json:"language,omitempty" bson:"language,omitempty"`
	Code                 *string  `protobuf:"bytes,2,opt,name=code" json:"code,omitempty" bson:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *SubmissionContent) Reset()         { *m = SubmissionContent{} }
func (m *SubmissionContent) String() string { return proto.CompactTextString(m) }
func (*SubmissionContent) ProtoMessage()    {}
func (*SubmissionContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{0}
}

func (m *SubmissionContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionContent.Unmarshal(m, b)
}
func (m *SubmissionContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionContent.Marshal(b, m, deterministic)
}
func (m *SubmissionContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionContent.Merge(m, src)
}
func (m *SubmissionContent) XXX_Size() int {
	return xxx_messageInfo_SubmissionContent.Size(m)
}
func (m *SubmissionContent) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionContent.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionContent proto.InternalMessageInfo

func (m *SubmissionContent) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

func (m *SubmissionContent) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

type SubmissionResult struct {
	Status               *string            `protobuf:"bytes,1,opt,name=status" json:"status,omitempty" bson:"status,omitempty"`
	Score                *float64           `protobuf:"fixed64,2,opt,name=score" json:"score,omitempty" bson:"score,omitempty"`
	MemoryUsage          *int64             `protobuf:"varint,3,opt,name=memory_usage,json=memoryUsage" json:"memory_usage,omitempty" bson:"memory_usage,omitempty"`
	TimeUsage            *duration.Duration `protobuf:"bytes,4,opt,name=time_usage,json=timeUsage" json:"time_usage,omitempty" bson:"time_usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-" bson:"-"`
	XXX_unrecognized     []byte             `json:"-" bson:"-"`
	XXX_sizecache        int32              `json:"-" bson:"-"`
}

func (m *SubmissionResult) Reset()         { *m = SubmissionResult{} }
func (m *SubmissionResult) String() string { return proto.CompactTextString(m) }
func (*SubmissionResult) ProtoMessage()    {}
func (*SubmissionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{1}
}

func (m *SubmissionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionResult.Unmarshal(m, b)
}
func (m *SubmissionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionResult.Marshal(b, m, deterministic)
}
func (m *SubmissionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionResult.Merge(m, src)
}
func (m *SubmissionResult) XXX_Size() int {
	return xxx_messageInfo_SubmissionResult.Size(m)
}
func (m *SubmissionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionResult.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionResult proto.InternalMessageInfo

func (m *SubmissionResult) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *SubmissionResult) GetScore() float64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *SubmissionResult) GetMemoryUsage() int64 {
	if m != nil && m.MemoryUsage != nil {
		return *m.MemoryUsage
	}
	return 0
}

func (m *SubmissionResult) GetTimeUsage() *duration.Duration {
	if m != nil {
		return m.TimeUsage
	}
	return nil
}

type ProblemConf struct {
	Type                 *string            `protobuf:"bytes,1,opt,name=type" json:"type,omitempty" yaml:"type,omitempty"`
	Cases                []*ProblemCase     `protobuf:"bytes,2,rep,name=cases" json:"cases,omitempty" yaml:"cases,omitempty"`
	CasesGlobal          *ProblemCase       `protobuf:"bytes,3,opt,name=cases_global,json=casesGlobal" json:"cases_global,omitempty" yaml:"cases_global,omitempty"`
	Subtasks             []*ProblemSubtask  `protobuf:"bytes,4,rep,name=subtasks" json:"subtasks,omitempty" yaml:"subtasks,omitempty"`
	Checker              *ProblemChecker    `protobuf:"bytes,5,opt,name=checker" json:"checker,omitempty" yaml:"checker,omitempty"`
	Languages            []*ProblemLanguage `protobuf:"bytes,6,rep,name=languages" json:"languages,omitempty" yaml:"languages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-" bson:"-"`
	XXX_unrecognized     []byte             `json:"-" bson:"-"`
	XXX_sizecache        int32              `json:"-" bson:"-"`
}

func (m *ProblemConf) Reset()         { *m = ProblemConf{} }
func (m *ProblemConf) String() string { return proto.CompactTextString(m) }
func (*ProblemConf) ProtoMessage()    {}
func (*ProblemConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{2}
}

func (m *ProblemConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemConf.Unmarshal(m, b)
}
func (m *ProblemConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemConf.Marshal(b, m, deterministic)
}
func (m *ProblemConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemConf.Merge(m, src)
}
func (m *ProblemConf) XXX_Size() int {
	return xxx_messageInfo_ProblemConf.Size(m)
}
func (m *ProblemConf) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemConf.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemConf proto.InternalMessageInfo

func (m *ProblemConf) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *ProblemConf) GetCases() []*ProblemCase {
	if m != nil {
		return m.Cases
	}
	return nil
}

func (m *ProblemConf) GetCasesGlobal() *ProblemCase {
	if m != nil {
		return m.CasesGlobal
	}
	return nil
}

func (m *ProblemConf) GetSubtasks() []*ProblemSubtask {
	if m != nil {
		return m.Subtasks
	}
	return nil
}

func (m *ProblemConf) GetChecker() *ProblemChecker {
	if m != nil {
		return m.Checker
	}
	return nil
}

func (m *ProblemConf) GetLanguages() []*ProblemLanguage {
	if m != nil {
		return m.Languages
	}
	return nil
}

type ProblemCase struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty" yaml:"name,omitempty"`
	InputData            *string  `protobuf:"bytes,2,opt,name=input_data,json=inputData" json:"input_data,omitempty" yaml:"input_data,omitempty"`
	AnswerData           *string  `protobuf:"bytes,3,opt,name=answer_data,json=answerData" json:"answer_data,omitempty" yaml:"answer_data,omitempty"`
	TimeLimit            *string  `protobuf:"bytes,4,opt,name=time_limit,json=timeLimit" json:"time_limit,omitempty" yaml:"time_limit,omitempty"`
	MemoryLimit          *string  `protobuf:"bytes,5,opt,name=memory_limit,json=memoryLimit" json:"memory_limit,omitempty" yaml:"memory_limit,omitempty"`
	InputFile            *string  `protobuf:"bytes,6,opt,name=input_file,json=inputFile" json:"input_file,omitempty" yaml:"input_file,omitempty"`
	OutputFile           *string  `protobuf:"bytes,7,opt,name=output_file,json=outputFile" json:"output_file,omitempty" yaml:"output_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ProblemCase) Reset()         { *m = ProblemCase{} }
func (m *ProblemCase) String() string { return proto.CompactTextString(m) }
func (*ProblemCase) ProtoMessage()    {}
func (*ProblemCase) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{3}
}

func (m *ProblemCase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemCase.Unmarshal(m, b)
}
func (m *ProblemCase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemCase.Marshal(b, m, deterministic)
}
func (m *ProblemCase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemCase.Merge(m, src)
}
func (m *ProblemCase) XXX_Size() int {
	return xxx_messageInfo_ProblemCase.Size(m)
}
func (m *ProblemCase) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemCase.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemCase proto.InternalMessageInfo

func (m *ProblemCase) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ProblemCase) GetInputData() string {
	if m != nil && m.InputData != nil {
		return *m.InputData
	}
	return ""
}

func (m *ProblemCase) GetAnswerData() string {
	if m != nil && m.AnswerData != nil {
		return *m.AnswerData
	}
	return ""
}

func (m *ProblemCase) GetTimeLimit() string {
	if m != nil && m.TimeLimit != nil {
		return *m.TimeLimit
	}
	return ""
}

func (m *ProblemCase) GetMemoryLimit() string {
	if m != nil && m.MemoryLimit != nil {
		return *m.MemoryLimit
	}
	return ""
}

func (m *ProblemCase) GetInputFile() string {
	if m != nil && m.InputFile != nil {
		return *m.InputFile
	}
	return ""
}

func (m *ProblemCase) GetOutputFile() string {
	if m != nil && m.OutputFile != nil {
		return *m.OutputFile
	}
	return ""
}

type ProblemSubtask struct {
	Score                *float64 `protobuf:"fixed64,1,opt,name=score" json:"score,omitempty" yaml:"score,omitempty"`
	Cases                []string `protobuf:"bytes,2,rep,name=cases" json:"cases,omitempty" yaml:"cases,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ProblemSubtask) Reset()         { *m = ProblemSubtask{} }
func (m *ProblemSubtask) String() string { return proto.CompactTextString(m) }
func (*ProblemSubtask) ProtoMessage()    {}
func (*ProblemSubtask) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{4}
}

func (m *ProblemSubtask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemSubtask.Unmarshal(m, b)
}
func (m *ProblemSubtask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemSubtask.Marshal(b, m, deterministic)
}
func (m *ProblemSubtask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemSubtask.Merge(m, src)
}
func (m *ProblemSubtask) XXX_Size() int {
	return xxx_messageInfo_ProblemSubtask.Size(m)
}
func (m *ProblemSubtask) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemSubtask.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemSubtask proto.InternalMessageInfo

func (m *ProblemSubtask) GetScore() float64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *ProblemSubtask) GetCases() []string {
	if m != nil {
		return m.Cases
	}
	return nil
}

type ProblemChecker struct {
	Type                 *string  `protobuf:"bytes,1,opt,name=type" json:"type,omitempty" yaml:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ProblemChecker) Reset()         { *m = ProblemChecker{} }
func (m *ProblemChecker) String() string { return proto.CompactTextString(m) }
func (*ProblemChecker) ProtoMessage()    {}
func (*ProblemChecker) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{5}
}

func (m *ProblemChecker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemChecker.Unmarshal(m, b)
}
func (m *ProblemChecker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemChecker.Marshal(b, m, deterministic)
}
func (m *ProblemChecker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemChecker.Merge(m, src)
}
func (m *ProblemChecker) XXX_Size() int {
	return xxx_messageInfo_ProblemChecker.Size(m)
}
func (m *ProblemChecker) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemChecker.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemChecker proto.InternalMessageInfo

func (m *ProblemChecker) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

type ProblemLanguage struct {
	Extension            *string  `protobuf:"bytes,1,opt,name=extension" json:"extension,omitempty" yaml:"extension,omitempty"`
	Flags                []string `protobuf:"bytes,2,rep,name=flags" json:"flags,omitempty" yaml:"flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ProblemLanguage) Reset()         { *m = ProblemLanguage{} }
func (m *ProblemLanguage) String() string { return proto.CompactTextString(m) }
func (*ProblemLanguage) ProtoMessage()    {}
func (*ProblemLanguage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{6}
}

func (m *ProblemLanguage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemLanguage.Unmarshal(m, b)
}
func (m *ProblemLanguage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemLanguage.Marshal(b, m, deterministic)
}
func (m *ProblemLanguage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemLanguage.Merge(m, src)
}
func (m *ProblemLanguage) XXX_Size() int {
	return xxx_messageInfo_ProblemLanguage.Size(m)
}
func (m *ProblemLanguage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemLanguage.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemLanguage proto.InternalMessageInfo

func (m *ProblemLanguage) GetExtension() string {
	if m != nil && m.Extension != nil {
		return *m.Extension
	}
	return ""
}

func (m *ProblemLanguage) GetFlags() []string {
	if m != nil {
		return m.Flags
	}
	return nil
}

func init() {
	proto.RegisterType((*SubmissionContent)(nil), "syzoj.judge.SubmissionContent")
	proto.RegisterType((*SubmissionResult)(nil), "syzoj.judge.SubmissionResult")
	proto.RegisterType((*ProblemConf)(nil), "syzoj.judge.ProblemConf")
	proto.RegisterType((*ProblemCase)(nil), "syzoj.judge.ProblemCase")
	proto.RegisterType((*ProblemSubtask)(nil), "syzoj.judge.ProblemSubtask")
	proto.RegisterType((*ProblemChecker)(nil), "syzoj.judge.ProblemChecker")
	proto.RegisterType((*ProblemLanguage)(nil), "syzoj.judge.ProblemLanguage")
}

func init() { proto.RegisterFile("judge.proto", fileDescriptor_a2b4fa635fb2baaa) }

var fileDescriptor_a2b4fa635fb2baaa = []byte{
	// 724 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x95, 0x75, 0xdd, 0x56, 0x67, 0xe2, 0x87, 0x25, 0x20, 0xeb, 0x7e, 0x50, 0x72, 0x40,
	0x3d, 0xb0, 0x54, 0x9b, 0x38, 0x4d, 0x42, 0x43, 0xd9, 0x80, 0x03, 0x3b, 0xa0, 0x0d, 0x84, 0x34,
	0x0e, 0x95, 0xd3, 0xba, 0x59, 0xb6, 0x24, 0xae, 0x62, 0x07, 0x28, 0x17, 0x0e, 0xf0, 0x57, 0x70,
	0xd8, 0xbf, 0xc4, 0x9f, 0xc3, 0x15, 0xd9, 0xcf, 0x49, 0x6d, 0x9a, 0x21, 0xb8, 0x4c, 0xeb, 0xf7,
	0xbd, 0xf7, 0x89, 0xfd, 0x7d, 0xef, 0x19, 0xb9, 0x97, 0xe5, 0x38, 0xa6, 0xc1, 0xb4, 0x60, 0x82,
	0x61, 0x97, 0xcf, 0xbe, 0xb0, 0xcb, 0x40, 0x49, 0xdd, 0x9d, 0x98, 0xb1, 0x38, 0xa5, 0x03, 0x15,
	0x8a, 0xca, 0xc9, 0x60, 0x5c, 0x16, 0x44, 0x24, 0x2c, 0x87, 0xe4, 0xee, 0xba, 0x20, 0x71, 0x4c,
	0x0b, 0xf8, 0xe5, 0x7f, 0x45, 0x77, 0xcf, 0xca, 0x28, 0x4b, 0x38, 0x4f, 0x58, 0x7e, 0xc4, 0x72,
	0x41, 0x73, 0x81, 0x0f, 0xd0, 0x5a, 0x4a, 0xf2, 0xb8, 0x24, 0x31, 0xf5, 0x9c, 0x9e, 0xd3, 0xef,
	0x84, 0x3b, 0x3f, 0xbe, 0x5f, 0xb7, 0x36, 0x22, 0xce, 0xf2, 0x03, 0xbf, 0x0a, 0x3d, 0x61, 0x59,
	0x22, 0x68, 0x36, 0x15, 0x33, 0xff, 0xb4, 0xce, 0xc7, 0x01, 0x5a, 0x1e, 0xb1, 0x31, 0xf5, 0x96,
	0x54, 0x5d, 0x57, 0xd6, 0xdd, 0x83, 0x3a, 0x29, 0x9b, 0x35, 0x2a, 0xcf, 0xbf, 0x5e, 0x42, 0x77,
	0xe6, 0x27, 0x38, 0xa5, 0xbc, 0x4c, 0x05, 0x7e, 0x8a, 0x56, 0xb8, 0x20, 0xa2, 0xe4, 0xfa, 0xf3,
	0x5b, 0x12, 0xf3, 0x00, 0x30, 0x10, 0x30, 0x41, 0x3a, 0x17, 0xef, 0xa1, 0x36, 0x1f, 0xb1, 0x02,
	0xbe, 0xed, 0x84, 0x9b, 0xb2, 0xe8, 0xbe, 0x2e, 0x92, 0xba, 0x59, 0x03, 0x99, 0xf8, 0x05, 0x5a,
	0xcf, 0x68, 0xc6, 0x8a, 0xd9, 0xb0, 0xe4, 0xf2, 0xb6, 0xad, 0x9e, 0xd3, 0x6f, 0x85, 0xbe, 0xac,
	0xdc, 0x86, 0x4a, 0x33, 0x6c, 0x02, 0x5c, 0x08, 0xbc, 0x93, 0x3a, 0x3e, 0x47, 0x48, 0x24, 0x19,
	0xd5, 0x90, 0xe5, 0x9e, 0xd3, 0x77, 0xf7, 0x37, 0x02, 0x68, 0x44, 0x50, 0x35, 0x22, 0x38, 0xd6,
	0x8d, 0x08, 0x7b, 0x92, 0xbf, 0x09, 0xfc, 0x79, 0x9d, 0x49, 0xef, 0x48, 0x59, 0xb1, 0xfd, 0x5f,
	0x2d, 0xe4, 0xbe, 0x29, 0x58, 0x94, 0xd2, 0xec, 0x88, 0xe5, 0x13, 0x69, 0xb0, 0x98, 0x4d, 0xab,
	0xc6, 0x80, 0xc1, 0x33, 0x92, 0xa5, 0x07, 0xbe, 0x94, 0x2d, 0x83, 0xa5, 0x80, 0x5f, 0xa3, 0xf6,
	0x88, 0x70, 0xca, 0xbd, 0xa5, 0x5e, 0xab, 0xef, 0xee, 0x7b, 0x81, 0x31, 0x2c, 0x41, 0x05, 0x26,
	0x9c, 0x6a, 0xbf, 0x00, 0xa5, 0x2a, 0x2c, 0xbf, 0x94, 0x82, 0x87, 0x68, 0x5d, 0xfd, 0x33, 0x8c,
	0x53, 0x16, 0x91, 0x54, 0xf9, 0xf5, 0x37, 0x26, 0x38, 0x69, 0x30, 0x75, 0xa1, 0xe5, 0xa4, 0x0a,
	0xbc, 0x52, 0x3a, 0x7e, 0x8f, 0xd6, 0x78, 0x19, 0x09, 0xc2, 0xaf, 0xb8, 0xb7, 0xac, 0x0e, 0xbc,
	0xd9, 0x04, 0x3f, 0x83, 0x1c, 0x3d, 0x97, 0xc0, 0xaf, 0xea, 0xac, 0xb9, 0xac, 0x44, 0xfc, 0x16,
	0xad, 0x8e, 0x2e, 0xe8, 0xe8, 0x8a, 0x16, 0x5e, 0x5b, 0x1d, 0xba, 0x91, 0x7b, 0x04, 0x29, 0xe1,
	0xb6, 0xe4, 0x7a, 0xfa, 0xdc, 0xa0, 0x99, 0xd8, 0x0a, 0x85, 0x3f, 0xa0, 0x4e, 0x35, 0xf9, 0xdc,
	0x5b, 0x51, 0xe7, 0xdd, 0x6a, 0xe2, 0x9e, 0xe8, 0xa4, 0xf0, 0xa1, 0x04, 0x77, 0x01, 0x5c, 0x57,
	0x5a, 0x9d, 0xaf, 0x55, 0xff, 0xa7, 0xd1, 0x79, 0xc2, 0xd5, 0x6a, 0xe5, 0x24, 0x6b, 0xea, 0xbc,
	0x94, 0xad, 0xce, 0x4b, 0x01, 0x1f, 0x22, 0x94, 0xe4, 0xd3, 0x52, 0x0c, 0xc7, 0x44, 0x10, 0xbd,
	0x90, 0x30, 0x7a, 0x50, 0x35, 0x0f, 0x5a, 0x07, 0x50, 0xf2, 0x31, 0x11, 0x04, 0x87, 0xc8, 0x25,
	0x39, 0xff, 0x44, 0x0b, 0x20, 0xb4, 0x14, 0xe1, 0x91, 0x24, 0x6c, 0x01, 0xc1, 0x88, 0x9a, 0x08,
	0x04, 0xba, 0x62, 0x1c, 0xea, 0xd5, 0x48, 0x93, 0x2c, 0x11, 0x6a, 0x35, 0xec, 0x43, 0xcc, 0x83,
	0x0b, 0xf3, 0x7f, 0x22, 0x55, 0x63, 0x45, 0x01, 0xd1, 0x56, 0x08, 0x73, 0xb0, 0xcc, 0x70, 0xc3,
	0x8a, 0x02, 0xa6, 0x36, 0x63, 0x92, 0xa4, 0xd4, 0x5b, 0xb9, 0xc1, 0x0c, 0x19, 0x5c, 0x34, 0xe3,
	0x65, 0x92, 0x52, 0x69, 0x06, 0x2b, 0x45, 0x4d, 0x58, 0x5d, 0x30, 0xc3, 0x88, 0x5a, 0x66, 0x80,
	0x2e, 0x19, 0xfe, 0x47, 0x74, 0xcb, 0x1e, 0xe0, 0xf9, 0x9b, 0xe5, 0x18, 0x6f, 0x96, 0x9e, 0xe7,
	0x1b, 0xde, 0xac, 0x3d, 0x73, 0xa1, 0x3b, 0xff, 0xb2, 0xb6, 0xfe, 0xf3, 0xfa, 0xbb, 0x7a, 0xc0,
	0xff, 0xf7, 0x15, 0xf1, 0xbf, 0x39, 0xe8, 0xf6, 0x1f, 0xb3, 0x8c, 0x9f, 0xa1, 0x0e, 0xfd, 0x2c,
	0x68, 0x2e, 0x1f, 0x6e, 0x0d, 0x32, 0xc7, 0xbb, 0x8e, 0x59, 0x86, 0xd6, 0xaa, 0xbc, 0xc7, 0x24,
	0x25, 0x71, 0xd3, 0x3d, 0x94, 0x6e, 0xdd, 0x43, 0x29, 0x61, 0xff, 0xfc, 0x71, 0x9c, 0x88, 0x8b,
	0x32, 0x0a, 0x46, 0x2c, 0x1b, 0xa8, 0x3d, 0x83, 0xbf, 0xbb, 0x79, 0xbc, 0x1b, 0xb3, 0x01, 0x99,
	0x4e, 0x07, 0x19, 0x1b, 0xd3, 0xf4, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x85, 0x7e, 0x3a,
	0x20, 0x07, 0x00, 0x00,
}
