// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package model

import (
	fmt "fmt"
	_ "github.com/amsokol/protoc-gen-gotag/tagger"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ObjectID struct {
	Id                   *string  `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ObjectID) Reset()         { *m = ObjectID{} }
func (m *ObjectID) String() string { return proto.CompactTextString(m) }
func (*ObjectID) ProtoMessage()    {}
func (*ObjectID) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *ObjectID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectID.Unmarshal(m, b)
}
func (m *ObjectID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectID.Marshal(b, m, deterministic)
}
func (m *ObjectID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectID.Merge(m, src)
}
func (m *ObjectID) XXX_Size() int {
	return xxx_messageInfo_ObjectID.Size(m)
}
func (m *ObjectID) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectID.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectID proto.InternalMessageInfo

func (m *ObjectID) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type User struct {
	Id                   *ObjectID            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty" bson:"_id,omitempty"`
	Username             *string              `protobuf:"bytes,2,opt,name=username" json:"username,omitempty" bson:"username,omitempty"`
	Email                *string              `protobuf:"bytes,3,opt,name=email" json:"email,omitempty" bson:"email,omitempty"`
	RegisterTime         *timestamp.Timestamp `protobuf:"bytes,4,opt,name=register_time,json=registerTime" json:"register_time,omitempty" bson:"register_time,omitempty"`
	Auth                 *UserAuth            `protobuf:"bytes,5,opt,name=auth" json:"auth,omitempty" bson:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() *ObjectID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *User) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *User) GetRegisterTime() *timestamp.Timestamp {
	if m != nil {
		return m.RegisterTime
	}
	return nil
}

func (m *User) GetAuth() *UserAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type UserAuth struct {
	Method               *int64   `protobuf:"varint,1,opt,name=method" json:"method,omitempty" bson:"method,omitempty"`
	Password             []byte   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty" bson:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *UserAuth) Reset()         { *m = UserAuth{} }
func (m *UserAuth) String() string { return proto.CompactTextString(m) }
func (*UserAuth) ProtoMessage()    {}
func (*UserAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *UserAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAuth.Unmarshal(m, b)
}
func (m *UserAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAuth.Marshal(b, m, deterministic)
}
func (m *UserAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAuth.Merge(m, src)
}
func (m *UserAuth) XXX_Size() int {
	return xxx_messageInfo_UserAuth.Size(m)
}
func (m *UserAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAuth.DiscardUnknown(m)
}

var xxx_messageInfo_UserAuth proto.InternalMessageInfo

func (m *UserAuth) GetMethod() int64 {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return 0
}

func (m *UserAuth) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type Submission struct {
	Id                   *ObjectID            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty" bson:"_id,omitempty"`
	Type                 *string              `protobuf:"bytes,2,opt,name=type" json:"type,omitempty" bson:"type,omitempty"`
	User                 *ObjectID            `protobuf:"bytes,3,opt,name=user" json:"user,omitempty" bson:"user,omitempty"`
	Owner                []*ObjectID          `protobuf:"bytes,4,rep,name=owner" json:"owner,omitempty" bson:"owner,omitempty"`
	Problem              *ObjectID            `protobuf:"bytes,5,opt,name=problem" json:"problem,omitempty" bson:"problem,omitempty"`
	SubmitTime           *timestamp.Timestamp `protobuf:"bytes,6,opt,name=submit_time,json=submitTime" json:"submit_time,omitempty" bson:"submit_time,omitempty"`
	Content              *SubmissionContent   `protobuf:"bytes,7,opt,name=content" json:"content,omitempty" bson:"content,omitempty"`
	Result               *SubmissionResult    `protobuf:"bytes,8,opt,name=result" json:"result,omitempty" bson:"result,omitempty"`
	JudgeQueueStatus     *JudgeQueueStatus    `protobuf:"bytes,9,opt,name=judge_queue_status,json=judgeQueueStatus" json:"judge_queue_status,omitempty" bson:"judge_queue_status,omitempty"`
	Public               *bool                `protobuf:"varint,10,opt,name=public" json:"public,omitempty" bson:"public,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *Submission) Reset()         { *m = Submission{} }
func (m *Submission) String() string { return proto.CompactTextString(m) }
func (*Submission) ProtoMessage()    {}
func (*Submission) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

func (m *Submission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Submission.Unmarshal(m, b)
}
func (m *Submission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Submission.Marshal(b, m, deterministic)
}
func (m *Submission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Submission.Merge(m, src)
}
func (m *Submission) XXX_Size() int {
	return xxx_messageInfo_Submission.Size(m)
}
func (m *Submission) XXX_DiscardUnknown() {
	xxx_messageInfo_Submission.DiscardUnknown(m)
}

var xxx_messageInfo_Submission proto.InternalMessageInfo

func (m *Submission) GetId() *ObjectID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Submission) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Submission) GetUser() *ObjectID {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Submission) GetOwner() []*ObjectID {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Submission) GetProblem() *ObjectID {
	if m != nil {
		return m.Problem
	}
	return nil
}

func (m *Submission) GetSubmitTime() *timestamp.Timestamp {
	if m != nil {
		return m.SubmitTime
	}
	return nil
}

func (m *Submission) GetContent() *SubmissionContent {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Submission) GetResult() *SubmissionResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Submission) GetJudgeQueueStatus() *JudgeQueueStatus {
	if m != nil {
		return m.JudgeQueueStatus
	}
	return nil
}

func (m *Submission) GetPublic() bool {
	if m != nil && m.Public != nil {
		return *m.Public
	}
	return false
}

type SubmissionContent struct {
	Language             *string  `protobuf:"bytes,1,opt,name=language" json:"language,omitempty" bson:"language,omitempty"`
	Code                 *string  `protobuf:"bytes,2,opt,name=code" json:"code,omitempty" bson:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *SubmissionContent) Reset()         { *m = SubmissionContent{} }
func (m *SubmissionContent) String() string { return proto.CompactTextString(m) }
func (*SubmissionContent) ProtoMessage()    {}
func (*SubmissionContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{4}
}

func (m *SubmissionContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionContent.Unmarshal(m, b)
}
func (m *SubmissionContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionContent.Marshal(b, m, deterministic)
}
func (m *SubmissionContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionContent.Merge(m, src)
}
func (m *SubmissionContent) XXX_Size() int {
	return xxx_messageInfo_SubmissionContent.Size(m)
}
func (m *SubmissionContent) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionContent.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionContent proto.InternalMessageInfo

func (m *SubmissionContent) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

func (m *SubmissionContent) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

type SubmissionResult struct {
	Status               *string            `protobuf:"bytes,1,opt,name=status" json:"status,omitempty" bson:"status,omitempty"`
	Score                *float64           `protobuf:"fixed64,2,opt,name=score" json:"score,omitempty" bson:"score,omitempty"`
	MemoryUsage          *int64             `protobuf:"varint,3,opt,name=memory_usage,json=memoryUsage" json:"memory_usage,omitempty" bson:"memory_usage,omitempty"`
	TimeUsage            *duration.Duration `protobuf:"bytes,4,opt,name=time_usage,json=timeUsage" json:"time_usage,omitempty" bson:"time_usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-" bson:"-"`
	XXX_unrecognized     []byte             `json:"-" bson:"-"`
	XXX_sizecache        int32              `json:"-" bson:"-"`
}

func (m *SubmissionResult) Reset()         { *m = SubmissionResult{} }
func (m *SubmissionResult) String() string { return proto.CompactTextString(m) }
func (*SubmissionResult) ProtoMessage()    {}
func (*SubmissionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{5}
}

func (m *SubmissionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionResult.Unmarshal(m, b)
}
func (m *SubmissionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionResult.Marshal(b, m, deterministic)
}
func (m *SubmissionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionResult.Merge(m, src)
}
func (m *SubmissionResult) XXX_Size() int {
	return xxx_messageInfo_SubmissionResult.Size(m)
}
func (m *SubmissionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionResult.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionResult proto.InternalMessageInfo

func (m *SubmissionResult) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *SubmissionResult) GetScore() float64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *SubmissionResult) GetMemoryUsage() int64 {
	if m != nil && m.MemoryUsage != nil {
		return *m.MemoryUsage
	}
	return 0
}

func (m *SubmissionResult) GetTimeUsage() *duration.Duration {
	if m != nil {
		return m.TimeUsage
	}
	return nil
}

type JudgeQueueStatus struct {
	InQueue              *bool    `protobuf:"varint,1,opt,name=in_queue,json=inQueue" json:"in_queue,omitempty" bson:"in_queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *JudgeQueueStatus) Reset()         { *m = JudgeQueueStatus{} }
func (m *JudgeQueueStatus) String() string { return proto.CompactTextString(m) }
func (*JudgeQueueStatus) ProtoMessage()    {}
func (*JudgeQueueStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{6}
}

func (m *JudgeQueueStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeQueueStatus.Unmarshal(m, b)
}
func (m *JudgeQueueStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeQueueStatus.Marshal(b, m, deterministic)
}
func (m *JudgeQueueStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeQueueStatus.Merge(m, src)
}
func (m *JudgeQueueStatus) XXX_Size() int {
	return xxx_messageInfo_JudgeQueueStatus.Size(m)
}
func (m *JudgeQueueStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeQueueStatus.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeQueueStatus proto.InternalMessageInfo

func (m *JudgeQueueStatus) GetInQueue() bool {
	if m != nil && m.InQueue != nil {
		return *m.InQueue
	}
	return false
}

type Session struct {
	Id                   *ObjectID `protobuf:"bytes,1,opt,name=id" json:"id,omitempty" bson:"_id,omitempty"`
	SessionToken         *string   `protobuf:"bytes,2,opt,name=session_token,json=sessionToken" json:"session_token,omitempty" bson:"session_token,omitempty"`
	SessionUser          *ObjectID `protobuf:"bytes,3,opt,name=session_user,json=sessionUser" json:"session_user,omitempty" bson:"session_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" bson:"-"`
	XXX_unrecognized     []byte    `json:"-" bson:"-"`
	XXX_sizecache        int32     `json:"-" bson:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{7}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() *ObjectID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Session) GetSessionToken() string {
	if m != nil && m.SessionToken != nil {
		return *m.SessionToken
	}
	return ""
}

func (m *Session) GetSessionUser() *ObjectID {
	if m != nil {
		return m.SessionUser
	}
	return nil
}

type Problem struct {
	Id                   *ObjectID            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty" bson:"_id,omitempty"`
	Title                *string              `protobuf:"bytes,2,opt,name=title" json:"title,omitempty" bson:"title,omitempty"`
	Statement            *string              `protobuf:"bytes,3,opt,name=statement" json:"statement,omitempty" bson:"statement,omitempty"`
	Owner                []*ObjectID          `protobuf:"bytes,4,rep,name=owner" json:"owner,omitempty" bson:"owner,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime" json:"create_time,omitempty" bson:"create_time,omitempty"`
	ShortName            *string              `protobuf:"bytes,6,opt,name=short_name,json=shortName" json:"short_name,omitempty" bson:"short_name,omitempty"`
	Public               *bool                `protobuf:"varint,7,opt,name=public" json:"public,omitempty" bson:"public,omitempty"`
	PublicStats          *ProblemStats        `protobuf:"bytes,8,opt,name=public_stats,json=publicStats" json:"public_stats,omitempty" bson:"public_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *Problem) Reset()         { *m = Problem{} }
func (m *Problem) String() string { return proto.CompactTextString(m) }
func (*Problem) ProtoMessage()    {}
func (*Problem) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{8}
}

func (m *Problem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Problem.Unmarshal(m, b)
}
func (m *Problem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Problem.Marshal(b, m, deterministic)
}
func (m *Problem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Problem.Merge(m, src)
}
func (m *Problem) XXX_Size() int {
	return xxx_messageInfo_Problem.Size(m)
}
func (m *Problem) XXX_DiscardUnknown() {
	xxx_messageInfo_Problem.DiscardUnknown(m)
}

var xxx_messageInfo_Problem proto.InternalMessageInfo

func (m *Problem) GetId() *ObjectID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Problem) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Problem) GetStatement() string {
	if m != nil && m.Statement != nil {
		return *m.Statement
	}
	return ""
}

func (m *Problem) GetOwner() []*ObjectID {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Problem) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Problem) GetShortName() string {
	if m != nil && m.ShortName != nil {
		return *m.ShortName
	}
	return ""
}

func (m *Problem) GetPublic() bool {
	if m != nil && m.Public != nil {
		return *m.Public
	}
	return false
}

func (m *Problem) GetPublicStats() *ProblemStats {
	if m != nil {
		return m.PublicStats
	}
	return nil
}

type ProblemStats struct {
	Accept               *int64   `protobuf:"varint,1,opt,name=accept" json:"accept,omitempty" bson:"accept,omitempty"`
	Submission           *int64   `protobuf:"varint,2,opt,name=submission" json:"submission,omitempty" bson:"submission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ProblemStats) Reset()         { *m = ProblemStats{} }
func (m *ProblemStats) String() string { return proto.CompactTextString(m) }
func (*ProblemStats) ProtoMessage()    {}
func (*ProblemStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{9}
}

func (m *ProblemStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemStats.Unmarshal(m, b)
}
func (m *ProblemStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemStats.Marshal(b, m, deterministic)
}
func (m *ProblemStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemStats.Merge(m, src)
}
func (m *ProblemStats) XXX_Size() int {
	return xxx_messageInfo_ProblemStats.Size(m)
}
func (m *ProblemStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemStats.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemStats proto.InternalMessageInfo

func (m *ProblemStats) GetAccept() int64 {
	if m != nil && m.Accept != nil {
		return *m.Accept
	}
	return 0
}

func (m *ProblemStats) GetSubmission() int64 {
	if m != nil && m.Submission != nil {
		return *m.Submission
	}
	return 0
}

type Contest struct {
	Id                   *ObjectID     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty" bson:"_id,omitempty"`
	Name                 *string       `protobuf:"bytes,2,opt,name=name" json:"name,omitempty" bson:"name,omitempty"`
	Description          *string       `protobuf:"bytes,3,opt,name=description" json:"description,omitempty" bson:"description,omitempty"`
	Owner                *ObjectID     `protobuf:"bytes,4,opt,name=owner" json:"owner,omitempty" bson:"owner,omitempty"`
	State                *ContestState `protobuf:"bytes,5,opt,name=state" json:"state,omitempty" bson:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-" bson:"-"`
	XXX_unrecognized     []byte        `json:"-" bson:"-"`
	XXX_sizecache        int32         `json:"-" bson:"-"`
}

func (m *Contest) Reset()         { *m = Contest{} }
func (m *Contest) String() string { return proto.CompactTextString(m) }
func (*Contest) ProtoMessage()    {}
func (*Contest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{10}
}

func (m *Contest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contest.Unmarshal(m, b)
}
func (m *Contest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contest.Marshal(b, m, deterministic)
}
func (m *Contest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contest.Merge(m, src)
}
func (m *Contest) XXX_Size() int {
	return xxx_messageInfo_Contest.Size(m)
}
func (m *Contest) XXX_DiscardUnknown() {
	xxx_messageInfo_Contest.DiscardUnknown(m)
}

var xxx_messageInfo_Contest proto.InternalMessageInfo

func (m *Contest) GetId() *ObjectID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Contest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Contest) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *Contest) GetOwner() *ObjectID {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Contest) GetState() *ContestState {
	if m != nil {
		return m.State
	}
	return nil
}

type ContestState struct {
	Running              *bool                   `protobuf:"varint,1,opt,name=running" json:"running,omitempty" bson:"running,omitempty"`
	StartTime            *timestamp.Timestamp    `protobuf:"bytes,2,opt,name=start_time,json=startTime" json:"start_time,omitempty" bson:"start_time,omitempty"`
	Problems             []*ProblemEntry         `protobuf:"bytes,3,rep,name=problems" json:"problems,omitempty" bson:"problems,omitempty"`
	Schedule             []*ContestSchedule      `protobuf:"bytes,4,rep,name=schedule" json:"schedule,omitempty" bson:"schedule,omitempty"`
	RanklistType         *string                 `protobuf:"bytes,5,opt,name=ranklist_type,json=ranklistType" json:"ranklist_type,omitempty" bson:"ranklist_type,omitempty"`
	RanklistComp         *string                 `protobuf:"bytes,6,opt,name=ranklist_comp,json=ranklistComp" json:"ranklist_comp,omitempty" bson:"ranklist_comp,omitempty"`
	RanklistVisibility   *string                 `protobuf:"bytes,7,opt,name=ranklist_visibility,json=ranklistVisibility" json:"ranklist_visibility,omitempty" bson:"ranklist_visibility,omitempty"`
	JudgeInContest       *bool                   `protobuf:"varint,8,opt,name=judge_in_contest,json=judgeInContest" json:"judge_in_contest,omitempty" bson:"judge_in_contest,omitempty"`
	SubmissionPerProblem *int32                  `protobuf:"varint,9,opt,name=submission_per_problem,json=submissionPerProblem" json:"submission_per_problem,omitempty" bson:"submission_per_problem,omitempty"`
	Clarifications       []*ContestClarification `protobuf:"bytes,10,rep,name=clarifications" json:"clarifications,omitempty" bson:"clarifications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-" bson:"-"`
	XXX_unrecognized     []byte                  `json:"-" bson:"-"`
	XXX_sizecache        int32                   `json:"-" bson:"-"`
}

func (m *ContestState) Reset()         { *m = ContestState{} }
func (m *ContestState) String() string { return proto.CompactTextString(m) }
func (*ContestState) ProtoMessage()    {}
func (*ContestState) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{11}
}

func (m *ContestState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestState.Unmarshal(m, b)
}
func (m *ContestState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestState.Marshal(b, m, deterministic)
}
func (m *ContestState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestState.Merge(m, src)
}
func (m *ContestState) XXX_Size() int {
	return xxx_messageInfo_ContestState.Size(m)
}
func (m *ContestState) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestState.DiscardUnknown(m)
}

var xxx_messageInfo_ContestState proto.InternalMessageInfo

func (m *ContestState) GetRunning() bool {
	if m != nil && m.Running != nil {
		return *m.Running
	}
	return false
}

func (m *ContestState) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *ContestState) GetProblems() []*ProblemEntry {
	if m != nil {
		return m.Problems
	}
	return nil
}

func (m *ContestState) GetSchedule() []*ContestSchedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

func (m *ContestState) GetRanklistType() string {
	if m != nil && m.RanklistType != nil {
		return *m.RanklistType
	}
	return ""
}

func (m *ContestState) GetRanklistComp() string {
	if m != nil && m.RanklistComp != nil {
		return *m.RanklistComp
	}
	return ""
}

func (m *ContestState) GetRanklistVisibility() string {
	if m != nil && m.RanklistVisibility != nil {
		return *m.RanklistVisibility
	}
	return ""
}

func (m *ContestState) GetJudgeInContest() bool {
	if m != nil && m.JudgeInContest != nil {
		return *m.JudgeInContest
	}
	return false
}

func (m *ContestState) GetSubmissionPerProblem() int32 {
	if m != nil && m.SubmissionPerProblem != nil {
		return *m.SubmissionPerProblem
	}
	return 0
}

func (m *ContestState) GetClarifications() []*ContestClarification {
	if m != nil {
		return m.Clarifications
	}
	return nil
}

type ProblemEntry struct {
	Name                 *string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty" bson:"name,omitempty"`
	ProblemId            *ObjectID `protobuf:"bytes,2,opt,name=problem_id,json=problemId" json:"problem_id,omitempty" bson:"problem_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" bson:"-"`
	XXX_unrecognized     []byte    `json:"-" bson:"-"`
	XXX_sizecache        int32     `json:"-" bson:"-"`
}

func (m *ProblemEntry) Reset()         { *m = ProblemEntry{} }
func (m *ProblemEntry) String() string { return proto.CompactTextString(m) }
func (*ProblemEntry) ProtoMessage()    {}
func (*ProblemEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{12}
}

func (m *ProblemEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemEntry.Unmarshal(m, b)
}
func (m *ProblemEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemEntry.Marshal(b, m, deterministic)
}
func (m *ProblemEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemEntry.Merge(m, src)
}
func (m *ProblemEntry) XXX_Size() int {
	return xxx_messageInfo_ProblemEntry.Size(m)
}
func (m *ProblemEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemEntry proto.InternalMessageInfo

func (m *ProblemEntry) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ProblemEntry) GetProblemId() *ObjectID {
	if m != nil {
		return m.ProblemId
	}
	return nil
}

type ContestSchedule struct {
	Type                 *string              `protobuf:"bytes,1,opt,name=type" json:"type,omitempty" bson:"type,omitempty"`
	Done                 *bool                `protobuf:"varint,2,opt,name=done" json:"done,omitempty" bson:"done,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime" json:"start_time,omitempty" bson:"start_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *ContestSchedule) Reset()         { *m = ContestSchedule{} }
func (m *ContestSchedule) String() string { return proto.CompactTextString(m) }
func (*ContestSchedule) ProtoMessage()    {}
func (*ContestSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{13}
}

func (m *ContestSchedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestSchedule.Unmarshal(m, b)
}
func (m *ContestSchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestSchedule.Marshal(b, m, deterministic)
}
func (m *ContestSchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestSchedule.Merge(m, src)
}
func (m *ContestSchedule) XXX_Size() int {
	return xxx_messageInfo_ContestSchedule.Size(m)
}
func (m *ContestSchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestSchedule.DiscardUnknown(m)
}

var xxx_messageInfo_ContestSchedule proto.InternalMessageInfo

func (m *ContestSchedule) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *ContestSchedule) GetDone() bool {
	if m != nil && m.Done != nil {
		return *m.Done
	}
	return false
}

func (m *ContestSchedule) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

type ContestClarification struct {
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,1,opt,name=create_time,json=createTime" json:"create_time,omitempty" bson:"create_time,omitempty"`
	Title                *string              `protobuf:"bytes,2,opt,name=title" json:"title,omitempty" bson:"title,omitempty"`
	ProblemName          *string              `protobuf:"bytes,3,opt,name=problem_name,json=problemName" json:"problem_name,omitempty" bson:"problem_name,omitempty"`
	Content              *string              `protobuf:"bytes,4,opt,name=content" json:"content,omitempty" bson:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *ContestClarification) Reset()         { *m = ContestClarification{} }
func (m *ContestClarification) String() string { return proto.CompactTextString(m) }
func (*ContestClarification) ProtoMessage()    {}
func (*ContestClarification) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{14}
}

func (m *ContestClarification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestClarification.Unmarshal(m, b)
}
func (m *ContestClarification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestClarification.Marshal(b, m, deterministic)
}
func (m *ContestClarification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestClarification.Merge(m, src)
}
func (m *ContestClarification) XXX_Size() int {
	return xxx_messageInfo_ContestClarification.Size(m)
}
func (m *ContestClarification) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestClarification.DiscardUnknown(m)
}

var xxx_messageInfo_ContestClarification proto.InternalMessageInfo

func (m *ContestClarification) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *ContestClarification) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *ContestClarification) GetProblemName() string {
	if m != nil && m.ProblemName != nil {
		return *m.ProblemName
	}
	return ""
}

func (m *ContestClarification) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

type ContestPlayer struct {
	Id                   *ObjectID                             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty" bson:"_id,omitempty"`
	Contest              *ObjectID                             `protobuf:"bytes,2,opt,name=contest" json:"contest,omitempty" bson:"contest,omitempty"`
	User                 *ObjectID                             `protobuf:"bytes,3,opt,name=user" json:"user,omitempty" bson:"user,omitempty"`
	RegisterTime         *timestamp.Timestamp                  `protobuf:"bytes,4,opt,name=register_time,json=registerTime" json:"register_time,omitempty" bson:"register_time,omitempty"`
	Problems             map[string]*ContestPlayerProblemEntry `protobuf:"bytes,5,rep,name=problems" json:"problems,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" bson:"problems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-" bson:"-"`
	XXX_unrecognized     []byte                                `json:"-" bson:"-"`
	XXX_sizecache        int32                                 `json:"-" bson:"-"`
}

func (m *ContestPlayer) Reset()         { *m = ContestPlayer{} }
func (m *ContestPlayer) String() string { return proto.CompactTextString(m) }
func (*ContestPlayer) ProtoMessage()    {}
func (*ContestPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{15}
}

func (m *ContestPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestPlayer.Unmarshal(m, b)
}
func (m *ContestPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestPlayer.Marshal(b, m, deterministic)
}
func (m *ContestPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestPlayer.Merge(m, src)
}
func (m *ContestPlayer) XXX_Size() int {
	return xxx_messageInfo_ContestPlayer.Size(m)
}
func (m *ContestPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_ContestPlayer proto.InternalMessageInfo

func (m *ContestPlayer) GetId() *ObjectID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ContestPlayer) GetContest() *ObjectID {
	if m != nil {
		return m.Contest
	}
	return nil
}

func (m *ContestPlayer) GetUser() *ObjectID {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ContestPlayer) GetRegisterTime() *timestamp.Timestamp {
	if m != nil {
		return m.RegisterTime
	}
	return nil
}

func (m *ContestPlayer) GetProblems() map[string]*ContestPlayerProblemEntry {
	if m != nil {
		return m.Problems
	}
	return nil
}

type ContestPlayerProblemEntry struct {
	Submissions          []*ContestPlayerProblemSubmissionEntry `protobuf:"bytes,1,rep,name=submissions" json:"submissions,omitempty" bson:"submissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-" bson:"-"`
	XXX_unrecognized     []byte                                 `json:"-" bson:"-"`
	XXX_sizecache        int32                                  `json:"-" bson:"-"`
}

func (m *ContestPlayerProblemEntry) Reset()         { *m = ContestPlayerProblemEntry{} }
func (m *ContestPlayerProblemEntry) String() string { return proto.CompactTextString(m) }
func (*ContestPlayerProblemEntry) ProtoMessage()    {}
func (*ContestPlayerProblemEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{16}
}

func (m *ContestPlayerProblemEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestPlayerProblemEntry.Unmarshal(m, b)
}
func (m *ContestPlayerProblemEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestPlayerProblemEntry.Marshal(b, m, deterministic)
}
func (m *ContestPlayerProblemEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestPlayerProblemEntry.Merge(m, src)
}
func (m *ContestPlayerProblemEntry) XXX_Size() int {
	return xxx_messageInfo_ContestPlayerProblemEntry.Size(m)
}
func (m *ContestPlayerProblemEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestPlayerProblemEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ContestPlayerProblemEntry proto.InternalMessageInfo

func (m *ContestPlayerProblemEntry) GetSubmissions() []*ContestPlayerProblemSubmissionEntry {
	if m != nil {
		return m.Submissions
	}
	return nil
}

type ContestPlayerProblemSubmissionEntry struct {
	SubmissionId         *ObjectID            `protobuf:"bytes,1,opt,name=submission_id,json=submissionId" json:"submission_id,omitempty" bson:"submission_id,omitempty"`
	PenaltyTime          *duration.Duration   `protobuf:"bytes,2,opt,name=penalty_time,json=penaltyTime" json:"penalty_time,omitempty" bson:"penalty_time,omitempty"`
	SubmitTime           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=submit_time,json=submitTime" json:"submit_time,omitempty" bson:"submit_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *ContestPlayerProblemSubmissionEntry) Reset()         { *m = ContestPlayerProblemSubmissionEntry{} }
func (m *ContestPlayerProblemSubmissionEntry) String() string { return proto.CompactTextString(m) }
func (*ContestPlayerProblemSubmissionEntry) ProtoMessage()    {}
func (*ContestPlayerProblemSubmissionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{17}
}

func (m *ContestPlayerProblemSubmissionEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestPlayerProblemSubmissionEntry.Unmarshal(m, b)
}
func (m *ContestPlayerProblemSubmissionEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestPlayerProblemSubmissionEntry.Marshal(b, m, deterministic)
}
func (m *ContestPlayerProblemSubmissionEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestPlayerProblemSubmissionEntry.Merge(m, src)
}
func (m *ContestPlayerProblemSubmissionEntry) XXX_Size() int {
	return xxx_messageInfo_ContestPlayerProblemSubmissionEntry.Size(m)
}
func (m *ContestPlayerProblemSubmissionEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestPlayerProblemSubmissionEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ContestPlayerProblemSubmissionEntry proto.InternalMessageInfo

func (m *ContestPlayerProblemSubmissionEntry) GetSubmissionId() *ObjectID {
	if m != nil {
		return m.SubmissionId
	}
	return nil
}

func (m *ContestPlayerProblemSubmissionEntry) GetPenaltyTime() *duration.Duration {
	if m != nil {
		return m.PenaltyTime
	}
	return nil
}

func (m *ContestPlayerProblemSubmissionEntry) GetSubmitTime() *timestamp.Timestamp {
	if m != nil {
		return m.SubmitTime
	}
	return nil
}

type Article struct {
	Id                   *ObjectID            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty" bson:"_id,omitempty"`
	Title                *string              `protobuf:"bytes,2,opt,name=title" json:"title,omitempty" bson:"title,omitempty"`
	Owner                *ObjectID            `protobuf:"bytes,3,opt,name=owner" json:"owner,omitempty" bson:"owner,omitempty"`
	Text                 *string              `protobuf:"bytes,4,opt,name=text" json:"text,omitempty" bson:"text,omitempty"`
	Reply                []*Reply             `protobuf:"bytes,5,rep,name=reply" json:"reply,omitempty" bson:"reply,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime" json:"create_time,omitempty" bson:"create_time,omitempty"`
	LastEditTime         *timestamp.Timestamp `protobuf:"bytes,7,opt,name=last_edit_time,json=lastEditTime" json:"last_edit_time,omitempty" bson:"last_edit_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{18}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetId() *ObjectID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Article) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Article) GetOwner() *ObjectID {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Article) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *Article) GetReply() []*Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *Article) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Article) GetLastEditTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastEditTime
	}
	return nil
}

type Reply struct {
	Owner                *ObjectID            `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty" bson:"owner,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,2,opt,name=create_time,json=createTime" json:"create_time,omitempty" bson:"create_time,omitempty"`
	LastEditTime         *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_edit_time,json=lastEditTime" json:"last_edit_time,omitempty" bson:"last_edit_time,omitempty"`
	Text                 *string              `protobuf:"bytes,4,opt,name=text" json:"text,omitempty" bson:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{19}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetOwner() *ObjectID {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Reply) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Reply) GetLastEditTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastEditTime
	}
	return nil
}

func (m *Reply) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

// API part
type Response struct {
	Session              *ResponseSession `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Error                *string          `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Data                 *any.Any         `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-" bson:"-"`
	XXX_unrecognized     []byte           `json:"-" bson:"-"`
	XXX_sizecache        int32            `json:"-" bson:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{20}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSession() *ResponseSession {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *Response) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *Response) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResponseSession struct {
	UserName             *string  `protobuf:"bytes,1,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	LoggedIn             *bool    `protobuf:"varint,2,opt,name=logged_in,json=loggedIn" json:"logged_in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ResponseSession) Reset()         { *m = ResponseSession{} }
func (m *ResponseSession) String() string { return proto.CompactTextString(m) }
func (*ResponseSession) ProtoMessage()    {}
func (*ResponseSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{21}
}

func (m *ResponseSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSession.Unmarshal(m, b)
}
func (m *ResponseSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSession.Marshal(b, m, deterministic)
}
func (m *ResponseSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSession.Merge(m, src)
}
func (m *ResponseSession) XXX_Size() int {
	return xxx_messageInfo_ResponseSession.Size(m)
}
func (m *ResponseSession) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSession.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSession proto.InternalMessageInfo

func (m *ResponseSession) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *ResponseSession) GetLoggedIn() bool {
	if m != nil && m.LoggedIn != nil {
		return *m.LoggedIn
	}
	return false
}

type LoginRequest struct {
	Username             *string  `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password             *string  `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{22}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type RegisterRequest struct {
	Username             *string  `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password             *string  `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Email                *string  `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{23}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

type ProblemDbResponse struct {
	Problems             []*Problem `protobuf:"bytes,1,rep,name=problems" json:"problems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-" bson:"-"`
	XXX_unrecognized     []byte     `json:"-" bson:"-"`
	XXX_sizecache        int32      `json:"-" bson:"-"`
}

func (m *ProblemDbResponse) Reset()         { *m = ProblemDbResponse{} }
func (m *ProblemDbResponse) String() string { return proto.CompactTextString(m) }
func (*ProblemDbResponse) ProtoMessage()    {}
func (*ProblemDbResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{24}
}

func (m *ProblemDbResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemDbResponse.Unmarshal(m, b)
}
func (m *ProblemDbResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemDbResponse.Marshal(b, m, deterministic)
}
func (m *ProblemDbResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemDbResponse.Merge(m, src)
}
func (m *ProblemDbResponse) XXX_Size() int {
	return xxx_messageInfo_ProblemDbResponse.Size(m)
}
func (m *ProblemDbResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemDbResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemDbResponse proto.InternalMessageInfo

func (m *ProblemDbResponse) GetProblems() []*Problem {
	if m != nil {
		return m.Problems
	}
	return nil
}

type ProblemDbNewRequest struct {
	Problem              *Problem `protobuf:"bytes,1,opt,name=problem" json:"problem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ProblemDbNewRequest) Reset()         { *m = ProblemDbNewRequest{} }
func (m *ProblemDbNewRequest) String() string { return proto.CompactTextString(m) }
func (*ProblemDbNewRequest) ProtoMessage()    {}
func (*ProblemDbNewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{25}
}

func (m *ProblemDbNewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemDbNewRequest.Unmarshal(m, b)
}
func (m *ProblemDbNewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemDbNewRequest.Marshal(b, m, deterministic)
}
func (m *ProblemDbNewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemDbNewRequest.Merge(m, src)
}
func (m *ProblemDbNewRequest) XXX_Size() int {
	return xxx_messageInfo_ProblemDbNewRequest.Size(m)
}
func (m *ProblemDbNewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemDbNewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemDbNewRequest proto.InternalMessageInfo

func (m *ProblemDbNewRequest) GetProblem() *Problem {
	if m != nil {
		return m.Problem
	}
	return nil
}

type ProblemDbNewResponse struct {
	Problem              *Problem `protobuf:"bytes,1,opt,name=problem" json:"problem,omitempty"`
	CanSubmit            *bool    `protobuf:"varint,2,opt,name=can_submit,json=canSubmit" json:"can_submit,omitempty"`
	IsOwner              *bool    `protobuf:"varint,3,opt,name=is_owner,json=isOwner" json:"is_owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ProblemDbNewResponse) Reset()         { *m = ProblemDbNewResponse{} }
func (m *ProblemDbNewResponse) String() string { return proto.CompactTextString(m) }
func (*ProblemDbNewResponse) ProtoMessage()    {}
func (*ProblemDbNewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{26}
}

func (m *ProblemDbNewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemDbNewResponse.Unmarshal(m, b)
}
func (m *ProblemDbNewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemDbNewResponse.Marshal(b, m, deterministic)
}
func (m *ProblemDbNewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemDbNewResponse.Merge(m, src)
}
func (m *ProblemDbNewResponse) XXX_Size() int {
	return xxx_messageInfo_ProblemDbNewResponse.Size(m)
}
func (m *ProblemDbNewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemDbNewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemDbNewResponse proto.InternalMessageInfo

func (m *ProblemDbNewResponse) GetProblem() *Problem {
	if m != nil {
		return m.Problem
	}
	return nil
}

func (m *ProblemDbNewResponse) GetCanSubmit() bool {
	if m != nil && m.CanSubmit != nil {
		return *m.CanSubmit
	}
	return false
}

func (m *ProblemDbNewResponse) GetIsOwner() bool {
	if m != nil && m.IsOwner != nil {
		return *m.IsOwner
	}
	return false
}

type ProblemDbEditRequest struct {
	Problem              *Problem `protobuf:"bytes,1,opt,name=problem" json:"problem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ProblemDbEditRequest) Reset()         { *m = ProblemDbEditRequest{} }
func (m *ProblemDbEditRequest) String() string { return proto.CompactTextString(m) }
func (*ProblemDbEditRequest) ProtoMessage()    {}
func (*ProblemDbEditRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{27}
}

func (m *ProblemDbEditRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemDbEditRequest.Unmarshal(m, b)
}
func (m *ProblemDbEditRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemDbEditRequest.Marshal(b, m, deterministic)
}
func (m *ProblemDbEditRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemDbEditRequest.Merge(m, src)
}
func (m *ProblemDbEditRequest) XXX_Size() int {
	return xxx_messageInfo_ProblemDbEditRequest.Size(m)
}
func (m *ProblemDbEditRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemDbEditRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemDbEditRequest proto.InternalMessageInfo

func (m *ProblemDbEditRequest) GetProblem() *Problem {
	if m != nil {
		return m.Problem
	}
	return nil
}

type ProblemDbViewSubmitRequest struct {
	Code                 *SubmissionContent `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-" bson:"-"`
	XXX_unrecognized     []byte             `json:"-" bson:"-"`
	XXX_sizecache        int32              `json:"-" bson:"-"`
}

func (m *ProblemDbViewSubmitRequest) Reset()         { *m = ProblemDbViewSubmitRequest{} }
func (m *ProblemDbViewSubmitRequest) String() string { return proto.CompactTextString(m) }
func (*ProblemDbViewSubmitRequest) ProtoMessage()    {}
func (*ProblemDbViewSubmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{28}
}

func (m *ProblemDbViewSubmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemDbViewSubmitRequest.Unmarshal(m, b)
}
func (m *ProblemDbViewSubmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemDbViewSubmitRequest.Marshal(b, m, deterministic)
}
func (m *ProblemDbViewSubmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemDbViewSubmitRequest.Merge(m, src)
}
func (m *ProblemDbViewSubmitRequest) XXX_Size() int {
	return xxx_messageInfo_ProblemDbViewSubmitRequest.Size(m)
}
func (m *ProblemDbViewSubmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemDbViewSubmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemDbViewSubmitRequest proto.InternalMessageInfo

func (m *ProblemDbViewSubmitRequest) GetCode() *SubmissionContent {
	if m != nil {
		return m.Code
	}
	return nil
}

type ProblemDbViewSubmitResponse struct {
	Submission           *Submission `protobuf:"bytes,1,opt,name=submission" json:"submission,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-" bson:"-"`
	XXX_unrecognized     []byte      `json:"-" bson:"-"`
	XXX_sizecache        int32       `json:"-" bson:"-"`
}

func (m *ProblemDbViewSubmitResponse) Reset()         { *m = ProblemDbViewSubmitResponse{} }
func (m *ProblemDbViewSubmitResponse) String() string { return proto.CompactTextString(m) }
func (*ProblemDbViewSubmitResponse) ProtoMessage()    {}
func (*ProblemDbViewSubmitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{29}
}

func (m *ProblemDbViewSubmitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemDbViewSubmitResponse.Unmarshal(m, b)
}
func (m *ProblemDbViewSubmitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemDbViewSubmitResponse.Marshal(b, m, deterministic)
}
func (m *ProblemDbViewSubmitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemDbViewSubmitResponse.Merge(m, src)
}
func (m *ProblemDbViewSubmitResponse) XXX_Size() int {
	return xxx_messageInfo_ProblemDbViewSubmitResponse.Size(m)
}
func (m *ProblemDbViewSubmitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemDbViewSubmitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemDbViewSubmitResponse proto.InternalMessageInfo

func (m *ProblemDbViewSubmitResponse) GetSubmission() *Submission {
	if m != nil {
		return m.Submission
	}
	return nil
}

type SubmissionsResponse struct {
	Submissions          []*SubmissionsResponseSubmissionEntry `protobuf:"bytes,1,rep,name=submissions" json:"submissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-" bson:"-"`
	XXX_unrecognized     []byte                                `json:"-" bson:"-"`
	XXX_sizecache        int32                                 `json:"-" bson:"-"`
}

func (m *SubmissionsResponse) Reset()         { *m = SubmissionsResponse{} }
func (m *SubmissionsResponse) String() string { return proto.CompactTextString(m) }
func (*SubmissionsResponse) ProtoMessage()    {}
func (*SubmissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{30}
}

func (m *SubmissionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionsResponse.Unmarshal(m, b)
}
func (m *SubmissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionsResponse.Marshal(b, m, deterministic)
}
func (m *SubmissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionsResponse.Merge(m, src)
}
func (m *SubmissionsResponse) XXX_Size() int {
	return xxx_messageInfo_SubmissionsResponse.Size(m)
}
func (m *SubmissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionsResponse proto.InternalMessageInfo

func (m *SubmissionsResponse) GetSubmissions() []*SubmissionsResponseSubmissionEntry {
	if m != nil {
		return m.Submissions
	}
	return nil
}

type SubmissionsResponseSubmissionEntry struct {
	Submission           *Submission `protobuf:"bytes,1,opt,name=submission" json:"submission,omitempty"`
	Problem              *Problem    `protobuf:"bytes,2,opt,name=problem" json:"problem,omitempty"`
	SubmitUser           *User       `protobuf:"bytes,3,opt,name=submit_user,json=submitUser" json:"submit_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-" bson:"-"`
	XXX_unrecognized     []byte      `json:"-" bson:"-"`
	XXX_sizecache        int32       `json:"-" bson:"-"`
}

func (m *SubmissionsResponseSubmissionEntry) Reset()         { *m = SubmissionsResponseSubmissionEntry{} }
func (m *SubmissionsResponseSubmissionEntry) String() string { return proto.CompactTextString(m) }
func (*SubmissionsResponseSubmissionEntry) ProtoMessage()    {}
func (*SubmissionsResponseSubmissionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{31}
}

func (m *SubmissionsResponseSubmissionEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionsResponseSubmissionEntry.Unmarshal(m, b)
}
func (m *SubmissionsResponseSubmissionEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionsResponseSubmissionEntry.Marshal(b, m, deterministic)
}
func (m *SubmissionsResponseSubmissionEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionsResponseSubmissionEntry.Merge(m, src)
}
func (m *SubmissionsResponseSubmissionEntry) XXX_Size() int {
	return xxx_messageInfo_SubmissionsResponseSubmissionEntry.Size(m)
}
func (m *SubmissionsResponseSubmissionEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionsResponseSubmissionEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionsResponseSubmissionEntry proto.InternalMessageInfo

func (m *SubmissionsResponseSubmissionEntry) GetSubmission() *Submission {
	if m != nil {
		return m.Submission
	}
	return nil
}

func (m *SubmissionsResponseSubmissionEntry) GetProblem() *Problem {
	if m != nil {
		return m.Problem
	}
	return nil
}

func (m *SubmissionsResponseSubmissionEntry) GetSubmitUser() *User {
	if m != nil {
		return m.SubmitUser
	}
	return nil
}

type SubmissionViewResponse struct {
	Submission           *Submission `protobuf:"bytes,1,opt,name=submission" json:"submission,omitempty"`
	Problem              *Problem    `protobuf:"bytes,2,opt,name=problem" json:"problem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-" bson:"-"`
	XXX_unrecognized     []byte      `json:"-" bson:"-"`
	XXX_sizecache        int32       `json:"-" bson:"-"`
}

func (m *SubmissionViewResponse) Reset()         { *m = SubmissionViewResponse{} }
func (m *SubmissionViewResponse) String() string { return proto.CompactTextString(m) }
func (*SubmissionViewResponse) ProtoMessage()    {}
func (*SubmissionViewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{32}
}

func (m *SubmissionViewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionViewResponse.Unmarshal(m, b)
}
func (m *SubmissionViewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionViewResponse.Marshal(b, m, deterministic)
}
func (m *SubmissionViewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionViewResponse.Merge(m, src)
}
func (m *SubmissionViewResponse) XXX_Size() int {
	return xxx_messageInfo_SubmissionViewResponse.Size(m)
}
func (m *SubmissionViewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionViewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionViewResponse proto.InternalMessageInfo

func (m *SubmissionViewResponse) GetSubmission() *Submission {
	if m != nil {
		return m.Submission
	}
	return nil
}

func (m *SubmissionViewResponse) GetProblem() *Problem {
	if m != nil {
		return m.Problem
	}
	return nil
}

type ContestsResponse struct {
	Contests             []*ContestsResponseContestEntry `protobuf:"bytes,1,rep,name=contests" json:"contests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-" bson:"-"`
	XXX_unrecognized     []byte                          `json:"-" bson:"-"`
	XXX_sizecache        int32                           `json:"-" bson:"-"`
}

func (m *ContestsResponse) Reset()         { *m = ContestsResponse{} }
func (m *ContestsResponse) String() string { return proto.CompactTextString(m) }
func (*ContestsResponse) ProtoMessage()    {}
func (*ContestsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{33}
}

func (m *ContestsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestsResponse.Unmarshal(m, b)
}
func (m *ContestsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestsResponse.Marshal(b, m, deterministic)
}
func (m *ContestsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestsResponse.Merge(m, src)
}
func (m *ContestsResponse) XXX_Size() int {
	return xxx_messageInfo_ContestsResponse.Size(m)
}
func (m *ContestsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContestsResponse proto.InternalMessageInfo

func (m *ContestsResponse) GetContests() []*ContestsResponseContestEntry {
	if m != nil {
		return m.Contests
	}
	return nil
}

type ContestsResponseContestEntry struct {
	Contest              *Contest `protobuf:"bytes,1,opt,name=contest" json:"contest,omitempty"`
	Running              *bool    `protobuf:"varint,2,opt,name=running" json:"running,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ContestsResponseContestEntry) Reset()         { *m = ContestsResponseContestEntry{} }
func (m *ContestsResponseContestEntry) String() string { return proto.CompactTextString(m) }
func (*ContestsResponseContestEntry) ProtoMessage()    {}
func (*ContestsResponseContestEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{34}
}

func (m *ContestsResponseContestEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestsResponseContestEntry.Unmarshal(m, b)
}
func (m *ContestsResponseContestEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestsResponseContestEntry.Marshal(b, m, deterministic)
}
func (m *ContestsResponseContestEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestsResponseContestEntry.Merge(m, src)
}
func (m *ContestsResponseContestEntry) XXX_Size() int {
	return xxx_messageInfo_ContestsResponseContestEntry.Size(m)
}
func (m *ContestsResponseContestEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestsResponseContestEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ContestsResponseContestEntry proto.InternalMessageInfo

func (m *ContestsResponseContestEntry) GetContest() *Contest {
	if m != nil {
		return m.Contest
	}
	return nil
}

func (m *ContestsResponseContestEntry) GetRunning() bool {
	if m != nil && m.Running != nil {
		return *m.Running
	}
	return false
}

func init() {
	proto.RegisterType((*ObjectID)(nil), "ObjectID")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*UserAuth)(nil), "UserAuth")
	proto.RegisterType((*Submission)(nil), "Submission")
	proto.RegisterType((*SubmissionContent)(nil), "SubmissionContent")
	proto.RegisterType((*SubmissionResult)(nil), "SubmissionResult")
	proto.RegisterType((*JudgeQueueStatus)(nil), "JudgeQueueStatus")
	proto.RegisterType((*Session)(nil), "Session")
	proto.RegisterType((*Problem)(nil), "Problem")
	proto.RegisterType((*ProblemStats)(nil), "ProblemStats")
	proto.RegisterType((*Contest)(nil), "Contest")
	proto.RegisterType((*ContestState)(nil), "ContestState")
	proto.RegisterType((*ProblemEntry)(nil), "ProblemEntry")
	proto.RegisterType((*ContestSchedule)(nil), "ContestSchedule")
	proto.RegisterType((*ContestClarification)(nil), "ContestClarification")
	proto.RegisterType((*ContestPlayer)(nil), "ContestPlayer")
	proto.RegisterMapType((map[string]*ContestPlayerProblemEntry)(nil), "ContestPlayer.ProblemsEntry")
	proto.RegisterType((*ContestPlayerProblemEntry)(nil), "ContestPlayerProblemEntry")
	proto.RegisterType((*ContestPlayerProblemSubmissionEntry)(nil), "ContestPlayerProblemSubmissionEntry")
	proto.RegisterType((*Article)(nil), "Article")
	proto.RegisterType((*Reply)(nil), "Reply")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*ResponseSession)(nil), "ResponseSession")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*ProblemDbResponse)(nil), "ProblemDbResponse")
	proto.RegisterType((*ProblemDbNewRequest)(nil), "ProblemDbNewRequest")
	proto.RegisterType((*ProblemDbNewResponse)(nil), "ProblemDbNewResponse")
	proto.RegisterType((*ProblemDbEditRequest)(nil), "ProblemDbEditRequest")
	proto.RegisterType((*ProblemDbViewSubmitRequest)(nil), "ProblemDbViewSubmitRequest")
	proto.RegisterType((*ProblemDbViewSubmitResponse)(nil), "ProblemDbViewSubmitResponse")
	proto.RegisterType((*SubmissionsResponse)(nil), "SubmissionsResponse")
	proto.RegisterType((*SubmissionsResponseSubmissionEntry)(nil), "SubmissionsResponseSubmissionEntry")
	proto.RegisterType((*SubmissionViewResponse)(nil), "SubmissionViewResponse")
	proto.RegisterType((*ContestsResponse)(nil), "ContestsResponse")
	proto.RegisterType((*ContestsResponseContestEntry)(nil), "ContestsResponseContestEntry")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 2116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x59, 0x5b, 0x6f, 0x1c, 0x49,
	0x15, 0xd6, 0xdc, 0x3c, 0x3d, 0xc7, 0xe3, 0xac, 0x53, 0xf1, 0x86, 0xf1, 0x38, 0x17, 0x6f, 0x27,
	0x0a, 0x06, 0x76, 0xc7, 0x2c, 0x5a, 0x69, 0x71, 0x04, 0x62, 0x33, 0x89, 0x01, 0x67, 0x6f, 0x66,
	0x92, 0x5d, 0x50, 0x58, 0x6d, 0xd3, 0xd3, 0x5d, 0x19, 0x77, 0xd2, 0xd3, 0x3d, 0xdb, 0x55, 0x9d,
	0x64, 0x10, 0x12, 0x2f, 0x88, 0x07, 0x7e, 0x02, 0x82, 0x7d, 0xe7, 0x9d, 0x47, 0x78, 0x45, 0x3c,
	0x20, 0xfe, 0x00, 0xe2, 0x89, 0x3f, 0x82, 0x4e, 0x5d, 0xba, 0xab, 0x7a, 0x26, 0x1b, 0xdb, 0xf1,
	0xe6, 0xc5, 0x72, 0x9f, 0xcb, 0x57, 0x55, 0xa7, 0x4e, 0x7d, 0xe7, 0x54, 0x0d, 0xac, 0x4e, 0xd3,
	0x90, 0xc6, 0x83, 0x59, 0x96, 0xf2, 0xb4, 0x7f, 0x75, 0x92, 0xa6, 0x93, 0x98, 0xee, 0x8a, 0xaf,
	0x71, 0xfe, 0x70, 0x97, 0x47, 0x53, 0xca, 0xb8, 0x3f, 0x9d, 0x29, 0x83, 0x2b, 0x55, 0x83, 0x30,
	0xcf, 0x7c, 0x1e, 0xa5, 0x89, 0xd2, 0x6f, 0x56, 0xf5, 0x7e, 0x32, 0x57, 0xaa, 0x2e, 0xf7, 0x27,
	0x13, 0x9a, 0xc9, 0x2f, 0xb7, 0x0f, 0xce, 0xc7, 0xe3, 0x47, 0x34, 0xe0, 0x07, 0x77, 0xc8, 0x39,
	0xa8, 0x47, 0x61, 0xaf, 0xb6, 0x5d, 0xdf, 0xe9, 0x8c, 0xea, 0x51, 0xe8, 0xfe, 0xab, 0x0e, 0xcd,
	0x4f, 0x18, 0xcd, 0xc8, 0x3b, 0x4a, 0x51, 0xdb, 0x59, 0xfd, 0x5e, 0x67, 0xa0, 0xed, 0x87, 0x9b,
	0x7f, 0xfc, 0xdd, 0x97, 0x8d, 0x8d, 0x31, 0x4b, 0x93, 0x9b, 0xae, 0x17, 0x85, 0x6f, 0xa6, 0xd3,
	0x88, 0xd3, 0xe9, 0x8c, 0xcf, 0x5d, 0x74, 0x27, 0x37, 0xc1, 0xc9, 0x19, 0xcd, 0x12, 0x7f, 0x4a,
	0x7b, 0xf5, 0xed, 0xda, 0x4e, 0x67, 0x78, 0x05, 0x1d, 0x36, 0xa5, 0x83, 0x56, 0x99, 0x5e, 0x85,
	0x3d, 0x79, 0x1b, 0x5a, 0x74, 0xea, 0x47, 0x71, 0xaf, 0x21, 0x1c, 0xb7, 0xd0, 0xf1, 0xa2, 0x74,
	0x14, 0x72, 0xd3, 0x4b, 0x5a, 0x92, 0x10, 0xd6, 0x32, 0x3a, 0x89, 0x18, 0xa7, 0x99, 0x87, 0xe1,
	0xea, 0x35, 0xc5, 0x7c, 0xfb, 0x03, 0x19, 0x8a, 0x81, 0x0e, 0xc5, 0xe0, 0xbe, 0x8e, 0xe5, 0xf0,
	0x1a, 0xc2, 0x5e, 0x91, 0xb0, 0x96, 0xaf, 0x09, 0xdf, 0xd5, 0x1a, 0xf4, 0x23, 0x7b, 0xd0, 0xf4,
	0x73, 0x7e, 0xd4, 0x6b, 0xa9, 0x60, 0x60, 0x7c, 0x6e, 0xe5, 0xfc, 0x68, 0xd8, 0x47, 0xac, 0xd7,
	0x25, 0x16, 0x5a, 0x98, 0x10, 0xc2, 0xc5, 0xfd, 0x0d, 0x38, 0xda, 0x9a, 0xbc, 0x03, 0x2b, 0x53,
	0xca, 0x8f, 0x52, 0x19, 0xd5, 0xc6, 0xf0, 0x12, 0x7a, 0x7f, 0x43, 0x7a, 0x4b, 0x85, 0xe9, 0xaf,
	0x6c, 0x31, 0xa2, 0x33, 0x9f, 0xb1, 0xa7, 0x69, 0x16, 0x8a, 0x88, 0x76, 0xad, 0x88, 0x6a, 0x95,
	0x15, 0x51, 0x2d, 0x74, 0xff, 0xd1, 0x02, 0xb8, 0x97, 0x8f, 0xa7, 0x11, 0x63, 0x51, 0x9a, 0x9c,
	0x72, 0x4b, 0x07, 0xd0, 0xe4, 0xf3, 0x99, 0xde, 0x4e, 0x73, 0xc9, 0x28, 0xb6, 0x96, 0x8c, 0x02,
	0x8c, 0x16, 0x6e, 0xa9, 0xd8, 0x45, 0x6b, 0x1c, 0xd3, 0x15, 0x2d, 0x2c, 0x57, 0x14, 0x90, 0x1f,
	0x40, 0x2b, 0x7d, 0x9a, 0xd0, 0xac, 0xd7, 0xdc, 0x6e, 0xd8, 0xbe, 0x66, 0x32, 0x08, 0x13, 0x2b,
	0x19, 0x84, 0x84, 0x0c, 0xa1, 0x3d, 0xcb, 0xd2, 0x71, 0x4c, 0xa7, 0xc5, 0x4e, 0x15, 0xfe, 0x97,
	0xd1, 0xbf, 0xa7, 0x62, 0x26, 0x8d, 0x4c, 0x04, 0xed, 0x48, 0x3e, 0x87, 0x55, 0x86, 0x01, 0xe3,
	0x32, 0x9d, 0x56, 0x5e, 0x98, 0x4e, 0x6f, 0x20, 0xf0, 0x25, 0x09, 0x6c, 0x78, 0x9a, 0xe0, 0x20,
	0xe5, 0x22, 0x95, 0xde, 0x87, 0x76, 0x90, 0x26, 0x9c, 0x26, 0xbc, 0xd7, 0x16, 0xd8, 0x64, 0x50,
	0x6e, 0xd0, 0x6d, 0xa9, 0xb1, 0x26, 0xab, 0xac, 0xad, 0xc9, 0x2a, 0x19, 0xf9, 0x09, 0xac, 0x64,
	0x94, 0xe5, 0x31, 0xef, 0x39, 0x02, 0xeb, 0xbc, 0x81, 0x35, 0x12, 0x0a, 0x2b, 0xc7, 0xa4, 0xad,
	0x95, 0x63, 0x52, 0x44, 0x22, 0x20, 0x8f, 0xf2, 0x70, 0x42, 0xbd, 0x2f, 0x72, 0x9a, 0x53, 0x8f,
	0x71, 0x9f, 0xe7, 0xac, 0xd7, 0x51, 0xa0, 0x77, 0x51, 0xf5, 0x33, 0xd4, 0xdc, 0x13, 0x8a, 0xe1,
	0x0e, 0x82, 0x5e, 0x93, 0xa0, 0x8b, 0x7e, 0xe6, 0x00, 0xeb, 0x8f, 0x2a, 0xbe, 0x78, 0x08, 0x66,
	0xf9, 0x38, 0x8e, 0x82, 0x1e, 0x6c, 0xd7, 0x76, 0x1c, 0x6b, 0x82, 0x52, 0x61, 0x4d, 0x50, 0x8a,
	0xdc, 0xdf, 0xc2, 0xf9, 0x85, 0x30, 0xe1, 0xc9, 0x88, 0xfd, 0x64, 0x92, 0xfb, 0x13, 0x2a, 0x92,
	0xda, 0xe6, 0x1a, 0xad, 0xb2, 0x4e, 0x86, 0x16, 0x62, 0x52, 0x07, 0x69, 0xb8, 0x2c, 0xa9, 0x51,
	0x6c, 0x65, 0x26, 0x0a, 0xdc, 0x2f, 0xeb, 0xb0, 0x5e, 0x0d, 0x2e, 0xae, 0x45, 0x85, 0x4a, 0x0e,
	0x6f, 0xae, 0x65, 0x31, 0x16, 0xca, 0x16, 0x69, 0x8e, 0x05, 0x69, 0x26, 0xc7, 0xae, 0x59, 0x99,
	0x2d, 0xe4, 0x56, 0x66, 0x0b, 0x09, 0xd9, 0x87, 0xee, 0x94, 0x4e, 0xd3, 0x6c, 0xee, 0xe5, 0x0c,
	0x57, 0xdb, 0x10, 0xfc, 0xe1, 0xa2, 0xe7, 0x65, 0xcd, 0x1f, 0xa5, 0xda, 0x04, 0x58, 0x95, 0x8a,
	0x4f, 0x50, 0x4e, 0x1e, 0x00, 0x60, 0x6e, 0x2a, 0x10, 0x49, 0x95, 0x9b, 0x0b, 0xb9, 0x7d, 0x47,
	0x55, 0x95, 0xe1, 0x36, 0xe2, 0x6f, 0xa9, 0xa3, 0x5e, 0xf8, 0x99, 0xe8, 0x1d, 0x14, 0x0b, 0x6c,
	0xf7, 0x43, 0x58, 0xaf, 0xe6, 0x09, 0xd9, 0x03, 0x27, 0x4a, 0x64, 0x6e, 0x88, 0x08, 0x39, 0xd6,
	0x06, 0x69, 0x95, 0x95, 0xda, 0x51, 0x22, 0x00, 0xdc, 0xff, 0xd4, 0xa0, 0x7d, 0x8f, 0xbe, 0x0c,
	0x6d, 0xfd, 0x14, 0xd6, 0x98, 0x04, 0xf0, 0x78, 0xfa, 0x98, 0x26, 0x6a, 0xab, 0x4d, 0xfa, 0xb7,
	0xf4, 0x16, 0xfd, 0x2b, 0xcd, 0x7d, 0x54, 0x90, 0x43, 0xd0, 0xdf, 0xde, 0x72, 0x62, 0x33, 0x37,
	0xc2, 0xb4, 0xb4, 0x36, 0x42, 0x29, 0xb0, 0x1a, 0xb8, 0x7f, 0x6a, 0x42, 0xfb, 0x50, 0x31, 0xce,
	0xe9, 0x56, 0xf7, 0x36, 0xb4, 0x78, 0xc4, 0x63, 0x9d, 0xc0, 0x66, 0x12, 0x09, 0xb9, 0x95, 0x44,
	0x42, 0x42, 0x7e, 0x08, 0x1d, 0xcc, 0x40, 0x3a, 0x45, 0xf2, 0x91, 0x25, 0xf6, 0x2a, 0xba, 0xf5,
	0xcb, 0x84, 0x15, 0x3a, 0x6b, 0x83, 0x0b, 0xe9, 0x4b, 0x72, 0xf3, 0xe7, 0xb0, 0x1a, 0x64, 0xd4,
	0xe7, 0x54, 0xf2, 0x6a, 0xeb, 0x44, 0xbc, 0x6a, 0x78, 0x5a, 0xbc, 0x2a, 0xe5, 0x82, 0x57, 0x7f,
	0x04, 0xc0, 0x8e, 0xd2, 0x8c, 0x7b, 0xa2, 0xf3, 0x58, 0x11, 0xab, 0x33, 0xf3, 0xb7, 0x54, 0xda,
	0xcb, 0x43, 0xf1, 0x47, 0xd8, 0x7c, 0x94, 0xbc, 0xd4, 0x3e, 0x3e, 0x2f, 0x91, 0xfb, 0xd0, 0x95,
	0xff, 0x09, 0xee, 0x63, 0x8a, 0x87, 0xd7, 0x06, 0x6a, 0x73, 0xf1, 0x1c, 0x30, 0x2b, 0x3d, 0x4c,
	0x6b, 0x2b, 0x3d, 0xa4, 0x42, 0x38, 0xb8, 0xbf, 0xaf, 0x41, 0xd7, 0x44, 0xc0, 0xc9, 0xf9, 0x41,
	0x40, 0x67, 0x7c, 0x49, 0xe7, 0x20, 0x15, 0xd6, 0xe4, 0xa4, 0x88, 0xbc, 0x07, 0xb2, 0xf2, 0x88,
	0xbc, 0x13, 0x89, 0xd2, 0xb0, 0x63, 0x52, 0x28, 0x17, 0xab, 0x95, 0x10, 0xbb, 0x7f, 0xad, 0x43,
	0x5b, 0xb0, 0x2d, 0xe3, 0xa7, 0x6f, 0x1e, 0x8c, 0x5e, 0xd0, 0xe4, 0xd9, 0xea, 0x5e, 0x08, 0x3b,
	0x72, 0x1b, 0x56, 0x43, 0xca, 0x82, 0x2c, 0x9a, 0x21, 0x05, 0xa9, 0x34, 0x35, 0x73, 0xc1, 0xd0,
	0x5a, 0xf1, 0x33, 0xe4, 0x66, 0xaa, 0xd6, 0x4e, 0x9e, 0xaa, 0xef, 0x41, 0x4b, 0x64, 0xbd, 0x4a,
	0xd2, 0xb5, 0x81, 0x8a, 0x00, 0x6e, 0x05, 0xb5, 0xe9, 0x1a, 0x25, 0x36, 0x5d, 0xa3, 0xc4, 0xfd,
	0xe7, 0x0a, 0x74, 0x4d, 0x27, 0xf2, 0x2e, 0xb4, 0xb3, 0x3c, 0x49, 0xa2, 0x64, 0xa2, 0x78, 0xd0,
	0xac, 0xf0, 0x4a, 0x63, 0xd1, 0xa0, 0x92, 0x91, 0x5f, 0x02, 0x30, 0xee, 0x67, 0xaa, 0x1b, 0xa9,
	0xbf, 0xf0, 0xd4, 0x58, 0xdb, 0x5b, 0x38, 0x56, 0x4f, 0x74, 0x26, 0x7b, 0x91, 0x03, 0x70, 0x54,
	0xdb, 0xc3, 0x7a, 0x0d, 0x71, 0xa8, 0x8b, 0xc4, 0xdd, 0x4f, 0x78, 0x36, 0xb7, 0x1b, 0x4d, 0x65,
	0x69, 0x37, 0x9a, 0x4a, 0x48, 0x3e, 0x00, 0x87, 0x05, 0x47, 0x34, 0xcc, 0x63, 0xaa, 0xf8, 0x61,
	0xbd, 0x08, 0x9b, 0x92, 0x5b, 0x68, 0xda, 0xd8, 0x42, 0xd3, 0x42, 0xa4, 0xee, 0xcc, 0x4f, 0x1e,
	0xc7, 0x11, 0xe3, 0x9e, 0x68, 0x3d, 0x5b, 0x0b, 0xd4, 0x6d, 0xe9, 0xed, 0xce, 0x5d, 0x69, 0xee,
	0x63, 0x2f, 0x6a, 0x22, 0x05, 0xe9, 0x74, 0xa6, 0x98, 0x61, 0x29, 0x12, 0xea, 0x97, 0x22, 0xdd,
	0x4e, 0xa7, 0x33, 0xf2, 0x00, 0x2e, 0x14, 0x96, 0x4f, 0x22, 0x16, 0x8d, 0xa3, 0x38, 0xe2, 0x73,
	0x41, 0x16, 0x9d, 0xe1, 0xb7, 0x10, 0xef, 0x7a, 0x05, 0xaf, 0xb4, 0x32, 0x51, 0x89, 0xd6, 0x7f,
	0x5a, 0xa8, 0xc9, 0x21, 0xc8, 0x3e, 0xc9, 0x8b, 0x12, 0x2f, 0x90, 0x51, 0x13, 0x4c, 0xe2, 0x0c,
	0x6f, 0x20, 0xf0, 0x1b, 0x66, 0xa7, 0x55, 0x9a, 0x98, 0xa8, 0xe7, 0x84, 0xf2, 0x20, 0xd1, 0x87,
	0x75, 0x0c, 0x17, 0xcb, 0x63, 0xec, 0xcd, 0x68, 0xe6, 0xe9, 0xce, 0x18, 0x9b, 0xba, 0xd6, 0xf0,
	0x4d, 0xc4, 0xfd, 0x66, 0x95, 0x06, 0x4c, 0x43, 0x13, 0x7d, 0xa3, 0x34, 0x39, 0xa4, 0x99, 0x2e,
	0x5c, 0x01, 0x9c, 0x0b, 0x62, 0x3f, 0x8b, 0x1e, 0x46, 0x81, 0xe8, 0x17, 0x58, 0x0f, 0xc4, 0xce,
	0xbf, 0xae, 0x77, 0xfe, 0xb6, 0xa9, 0x1d, 0x5e, 0xc7, 0x21, 0xaf, 0x2a, 0x42, 0xb7, 0xfc, 0xac,
	0x85, 0xd8, 0x2a, 0xf7, 0x0f, 0x25, 0x15, 0x8a, 0x9c, 0x2c, 0x08, 0xa5, 0x76, 0x4c, 0x42, 0xb9,
	0x0b, 0xa0, 0x56, 0xe4, 0x45, 0xa1, 0x3a, 0x41, 0x06, 0x21, 0x98, 0x07, 0xa6, 0xb4, 0xb3, 0x0e,
	0x8c, 0x12, 0x1f, 0x84, 0xee, 0xbf, 0x6b, 0xf0, 0x5a, 0x25, 0xab, 0x8b, 0xdb, 0x51, 0xed, 0x98,
	0xb7, 0xa3, 0x01, 0x34, 0xc3, 0x34, 0x91, 0x67, 0xd9, 0xb1, 0xec, 0x51, 0x6c, 0xd9, 0xa3, 0xa0,
	0xc2, 0x00, 0x8d, 0x33, 0x65, 0x00, 0xf7, 0x2f, 0x75, 0xd8, 0x58, 0xb6, 0x59, 0xd5, 0x72, 0x5d,
	0x3b, 0xeb, 0x72, 0x7d, 0x8a, 0xf6, 0x65, 0x1f, 0xba, 0x7a, 0x83, 0x44, 0x02, 0xc8, 0xd2, 0x60,
	0xd5, 0x56, 0x43, 0x6d, 0xd7, 0x56, 0xa9, 0x10, 0x75, 0xfe, 0xdd, 0xf2, 0x02, 0xd6, 0x14, 0x08,
	0xc7, 0xbc, 0x6c, 0xb9, 0xff, 0x6d, 0xc0, 0x9a, 0x8a, 0xd5, 0x61, 0xec, 0xcf, 0x4f, 0xfd, 0x42,
	0x32, 0x54, 0x13, 0x60, 0x7c, 0x31, 0x1b, 0x17, 0xe6, 0xc2, 0x96, 0xcc, 0x85, 0xf1, 0x97, 0xb9,
	0x62, 0xbf, 0x9a, 0x17, 0x93, 0x5f, 0x18, 0xa5, 0xa5, 0x25, 0x58, 0xe1, 0xd2, 0xc0, 0x0a, 0x9e,
	0x2e, 0x34, 0xec, 0x84, 0x95, 0xa6, 0xff, 0x73, 0x58, 0xb3, 0x5c, 0xc9, 0x3a, 0x34, 0x1e, 0xd3,
	0xb9, 0x3c, 0x7f, 0x23, 0xfc, 0x97, 0x7c, 0x17, 0x5a, 0x4f, 0xfc, 0x38, 0x2f, 0xeb, 0xa5, 0x35,
	0xb2, 0xc9, 0x26, 0x23, 0x69, 0x78, 0xb3, 0xfe, 0xfd, 0x1a, 0x36, 0x5d, 0x9b, 0xcf, 0x35, 0x24,
	0x91, 0x7a, 0x17, 0x10, 0x24, 0x88, 0xf7, 0x3d, 0x5c, 0xd3, 0xf5, 0xa5, 0xc8, 0xe5, 0x35, 0x51,
	0xae, 0x6d, 0xe1, 0x85, 0x40, 0x62, 0xd8, 0x97, 0x83, 0x52, 0xee, 0xfe, 0xad, 0x0e, 0xd7, 0x8e,
	0x81, 0x4b, 0xee, 0xc1, 0x9a, 0x41, 0xdd, 0xcb, 0x32, 0xd1, 0xba, 0xeb, 0x98, 0xa6, 0xf6, 0x5d,
	0xa7, 0xd0, 0x1c, 0x84, 0xe4, 0x57, 0xd0, 0x9d, 0xd1, 0xc4, 0x8f, 0xf9, 0xdc, 0x6c, 0x39, 0xbe,
	0xe2, 0x92, 0x68, 0x1d, 0x40, 0xc3, 0xd3, 0x3e, 0x80, 0x52, 0x21, 0x52, 0xa3, 0xf2, 0xc2, 0xd2,
	0x38, 0xe3, 0x17, 0x16, 0xf7, 0x7f, 0x0d, 0x68, 0xdf, 0xca, 0x78, 0x14, 0xc4, 0xf4, 0xd5, 0xdd,
	0xad, 0x8a, 0x8e, 0xb3, 0x71, 0x9a, 0x8e, 0x13, 0x6b, 0x08, 0x7d, 0xa6, 0x09, 0xc9, 0xaa, 0x21,
	0xf4, 0x19, 0xb7, 0x6b, 0x08, 0x7d, 0x86, 0xc7, 0xbf, 0x95, 0xd1, 0x59, 0x3c, 0x57, 0x47, 0x6b,
	0x65, 0x30, 0xc2, 0x2f, 0x6b, 0x28, 0xa1, 0xb7, 0x86, 0x12, 0x92, 0x2a, 0xb1, 0xaf, 0x9c, 0x35,
	0xb1, 0x3f, 0x84, 0x73, 0xb1, 0xcf, 0xb8, 0x47, 0x43, 0xbd, 0xc1, 0xed, 0x17, 0x0e, 0x61, 0x76,
	0x06, 0xb6, 0xb3, 0x95, 0xa7, 0xa8, 0xda, 0x0f, 0xd5, 0x2e, 0xff, 0xbd, 0x0e, 0x2d, 0xb1, 0xea,
	0x32, 0xf4, 0xb5, 0xd3, 0x84, 0xbe, 0x12, 0x8f, 0xfa, 0xd7, 0x1f, 0x8f, 0xc6, 0xd7, 0x11, 0x8f,
	0x93, 0xa6, 0x90, 0xfb, 0x04, 0x9c, 0x11, 0x65, 0xb3, 0x34, 0x61, 0x94, 0x7c, 0x1b, 0xda, 0xea,
	0x71, 0x42, 0xc5, 0x70, 0x7d, 0xa0, 0x75, 0xea, 0x09, 0x66, 0xa4, 0x0d, 0xc8, 0x06, 0xb4, 0x68,
	0x96, 0xa5, 0x99, 0x3c, 0x1b, 0x23, 0xf9, 0x41, 0x76, 0xa0, 0x19, 0xfa, 0xdc, 0x57, 0x6b, 0xdb,
	0x58, 0x58, 0xdb, 0xad, 0x64, 0x3e, 0x12, 0x16, 0xee, 0xfb, 0xf0, 0x5a, 0x05, 0x9b, 0x6c, 0x41,
	0x07, 0x2b, 0x93, 0x57, 0xb6, 0x75, 0xf2, 0x37, 0x01, 0x51, 0xae, 0xb7, 0xa0, 0x13, 0xa7, 0x93,
	0x09, 0x0d, 0xbd, 0x48, 0x5e, 0x61, 0x9d, 0x91, 0x23, 0x05, 0x07, 0x89, 0xfb, 0x63, 0xe8, 0x7e,
	0x90, 0x4e, 0xa2, 0x64, 0x44, 0xbf, 0xc8, 0xb1, 0x2c, 0xf6, 0x8d, 0x1f, 0x1f, 0x0c, 0x20, 0xd1,
	0x07, 0xf6, 0x2b, 0xcf, 0xe8, 0x1d, 0xe3, 0x99, 0xdc, 0xc3, 0x49, 0xc9, 0xea, 0xf5, 0x92, 0x50,
	0x22, 0x3e, 0xe5, 0x6f, 0x18, 0xea, 0x67, 0x0a, 0x77, 0x0f, 0xce, 0x2b, 0x12, 0xbf, 0x33, 0x2e,
	0xc2, 0x7e, 0xdd, 0xa8, 0x91, 0xb2, 0x9e, 0x38, 0xba, 0x2a, 0x96, 0xf5, 0xce, 0xdd, 0x83, 0x0b,
	0x85, 0xeb, 0x47, 0xf4, 0xa9, 0x9e, 0x9f, 0x5b, 0xbe, 0x75, 0xcb, 0x3d, 0x2b, 0x7d, 0xb5, 0xc2,
	0xe5, 0xb0, 0x61, 0xbb, 0xaa, 0x81, 0x8f, 0xe1, 0x4b, 0x2e, 0x03, 0x04, 0x7e, 0xe2, 0x49, 0x5e,
	0x55, 0x81, 0xef, 0x04, 0x7e, 0x22, 0x8a, 0x10, 0x27, 0x9b, 0xe0, 0x44, 0xcc, 0x2b, 0x29, 0xcf,
	0x19, 0xb5, 0x23, 0xf6, 0x31, 0x7e, 0xba, 0x37, 0x8d, 0x51, 0x31, 0x3d, 0x4f, 0x32, 0xe3, 0x3b,
	0xd0, 0x2f, 0x7c, 0x3f, 0x8d, 0xe8, 0x53, 0x39, 0x9a, 0x46, 0xb8, 0xa1, 0xde, 0x6c, 0x6b, 0xcf,
	0x7b, 0x38, 0x57, 0x6f, 0xb5, 0x77, 0x61, 0x6b, 0x29, 0x8a, 0x5a, 0xfe, 0x77, 0xac, 0x67, 0x11,
	0x09, 0xb6, 0x6a, 0xbe, 0x9c, 0x9b, 0x2f, 0x20, 0x9f, 0xc1, 0x85, 0x52, 0xc3, 0x0a, 0x8c, 0xfd,
	0x65, 0xed, 0xc0, 0xb5, 0xc1, 0x12, 0xd3, 0x4a, 0xd5, 0xb6, 0x4b, 0xfd, 0x9f, 0x6b, 0xe0, 0xbe,
	0xd8, 0xe7, 0x44, 0x33, 0x36, 0xe3, 0x5c, 0x7f, 0xde, 0xee, 0xde, 0x28, 0x6a, 0xb0, 0xd1, 0x46,
	0xb6, 0xc4, 0xef, 0x5a, 0xba, 0x96, 0x8a, 0x77, 0xca, 0x08, 0x2e, 0x96, 0xa3, 0x60, 0x28, 0x4f,
	0x15, 0xc4, 0xe3, 0x4c, 0xc9, 0xfd, 0x10, 0xd6, 0x55, 0xd3, 0x53, 0x46, 0x79, 0x0f, 0x1c, 0xd5,
	0xf1, 0xea, 0x10, 0x5f, 0x1e, 0x54, 0x8d, 0xd4, 0xb7, 0x0c, 0x6e, 0x61, 0xee, 0x7e, 0x06, 0x97,
	0xbe, 0xca, 0x12, 0xa7, 0xa4, 0xbb, 0x70, 0x9d, 0x8d, 0x4a, 0x5f, 0x76, 0xd9, 0xbd, 0xf2, 0xd5,
	0x46, 0x1e, 0x00, 0xfd, 0x39, 0xdc, 0x79, 0x70, 0x63, 0x12, 0xf1, 0xa3, 0x7c, 0x3c, 0x08, 0xd2,
	0xe9, 0x2e, 0x9b, 0xff, 0x3a, 0x7d, 0x24, 0xff, 0xbe, 0x95, 0x4c, 0xde, 0x9a, 0xa4, 0xbb, 0xfe,
	0x6c, 0xb6, 0x2b, 0x7e, 0xda, 0xfd, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xa0, 0x92, 0x32,
	0xe2, 0x1d, 0x00, 0x00,
}
