// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package model

import (
	fmt "fmt"
	_ "github.com/amsokol/protoc-gen-gotag/tagger"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   *ObjectID            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty" bson:"_id,omitempty"`
	Username             *string              `protobuf:"bytes,2,opt,name=username" json:"username,omitempty" bson:"username,omitempty"`
	Email                *string              `protobuf:"bytes,3,opt,name=email" json:"email,omitempty" bson:"email,omitempty"`
	RegisterTime         *timestamp.Timestamp `protobuf:"bytes,4,opt,name=register_time,json=registerTime" json:"register_time,omitempty" bson:"register_time,omitempty"`
	Auth                 *UserAuth            `protobuf:"bytes,5,opt,name=auth" json:"auth,omitempty" bson:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() *ObjectID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *User) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *User) GetRegisterTime() *timestamp.Timestamp {
	if m != nil {
		return m.RegisterTime
	}
	return nil
}

func (m *User) GetAuth() *UserAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type UserAuth struct {
	Method               *int64   `protobuf:"varint,1,opt,name=method" json:"method,omitempty" bson:"method,omitempty"`
	Password             []byte   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty" bson:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *UserAuth) Reset()         { *m = UserAuth{} }
func (m *UserAuth) String() string { return proto.CompactTextString(m) }
func (*UserAuth) ProtoMessage()    {}
func (*UserAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *UserAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAuth.Unmarshal(m, b)
}
func (m *UserAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAuth.Marshal(b, m, deterministic)
}
func (m *UserAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAuth.Merge(m, src)
}
func (m *UserAuth) XXX_Size() int {
	return xxx_messageInfo_UserAuth.Size(m)
}
func (m *UserAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAuth.DiscardUnknown(m)
}

var xxx_messageInfo_UserAuth proto.InternalMessageInfo

func (m *UserAuth) GetMethod() int64 {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return 0
}

func (m *UserAuth) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type Submission struct {
	Id                   *ObjectID            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty" bson:"_id,omitempty"`
	Type                 *string              `protobuf:"bytes,2,opt,name=type" json:"type,omitempty" bson:"type,omitempty"`
	User                 *ObjectID            `protobuf:"bytes,3,opt,name=user" json:"user,omitempty" bson:"user,omitempty"`
	Owner                []*ObjectID          `protobuf:"bytes,4,rep,name=owner" json:"owner,omitempty" bson:"owner,omitempty"`
	Problem              *ObjectID            `protobuf:"bytes,5,opt,name=problem" json:"problem,omitempty" bson:"problem,omitempty"`
	SubmitTime           *timestamp.Timestamp `protobuf:"bytes,6,opt,name=submit_time,json=submitTime" json:"submit_time,omitempty" bson:"submit_time,omitempty"`
	Content              *SubmissionContent   `protobuf:"bytes,7,opt,name=content" json:"content,omitempty" bson:"content,omitempty"`
	Result               *SubmissionResult    `protobuf:"bytes,8,opt,name=result" json:"result,omitempty" bson:"result,omitempty"`
	JudgeQueueStatus     *JudgeQueueStatus    `protobuf:"bytes,9,opt,name=judge_queue_status,json=judgeQueueStatus" json:"judge_queue_status,omitempty" bson:"judge_queue_status,omitempty"`
	Public               *bool                `protobuf:"varint,10,opt,name=public" json:"public,omitempty" bson:"public,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *Submission) Reset()         { *m = Submission{} }
func (m *Submission) String() string { return proto.CompactTextString(m) }
func (*Submission) ProtoMessage()    {}
func (*Submission) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *Submission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Submission.Unmarshal(m, b)
}
func (m *Submission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Submission.Marshal(b, m, deterministic)
}
func (m *Submission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Submission.Merge(m, src)
}
func (m *Submission) XXX_Size() int {
	return xxx_messageInfo_Submission.Size(m)
}
func (m *Submission) XXX_DiscardUnknown() {
	xxx_messageInfo_Submission.DiscardUnknown(m)
}

var xxx_messageInfo_Submission proto.InternalMessageInfo

func (m *Submission) GetId() *ObjectID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Submission) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Submission) GetUser() *ObjectID {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Submission) GetOwner() []*ObjectID {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Submission) GetProblem() *ObjectID {
	if m != nil {
		return m.Problem
	}
	return nil
}

func (m *Submission) GetSubmitTime() *timestamp.Timestamp {
	if m != nil {
		return m.SubmitTime
	}
	return nil
}

func (m *Submission) GetContent() *SubmissionContent {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Submission) GetResult() *SubmissionResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Submission) GetJudgeQueueStatus() *JudgeQueueStatus {
	if m != nil {
		return m.JudgeQueueStatus
	}
	return nil
}

func (m *Submission) GetPublic() bool {
	if m != nil && m.Public != nil {
		return *m.Public
	}
	return false
}

type JudgeQueueStatus struct {
	InQueue              *bool    `protobuf:"varint,1,opt,name=in_queue,json=inQueue" json:"in_queue,omitempty" bson:"in_queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *JudgeQueueStatus) Reset()         { *m = JudgeQueueStatus{} }
func (m *JudgeQueueStatus) String() string { return proto.CompactTextString(m) }
func (*JudgeQueueStatus) ProtoMessage()    {}
func (*JudgeQueueStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

func (m *JudgeQueueStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeQueueStatus.Unmarshal(m, b)
}
func (m *JudgeQueueStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeQueueStatus.Marshal(b, m, deterministic)
}
func (m *JudgeQueueStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeQueueStatus.Merge(m, src)
}
func (m *JudgeQueueStatus) XXX_Size() int {
	return xxx_messageInfo_JudgeQueueStatus.Size(m)
}
func (m *JudgeQueueStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeQueueStatus.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeQueueStatus proto.InternalMessageInfo

func (m *JudgeQueueStatus) GetInQueue() bool {
	if m != nil && m.InQueue != nil {
		return *m.InQueue
	}
	return false
}

type Session struct {
	Id                   *ObjectID `protobuf:"bytes,1,opt,name=id" json:"id,omitempty" bson:"_id,omitempty"`
	SessionToken         *string   `protobuf:"bytes,2,opt,name=session_token,json=sessionToken" json:"session_token,omitempty" bson:"session_token,omitempty"`
	SessionUser          *ObjectID `protobuf:"bytes,3,opt,name=session_user,json=sessionUser" json:"session_user,omitempty" bson:"session_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" bson:"-"`
	XXX_unrecognized     []byte    `json:"-" bson:"-"`
	XXX_sizecache        int32     `json:"-" bson:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{4}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() *ObjectID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Session) GetSessionToken() string {
	if m != nil && m.SessionToken != nil {
		return *m.SessionToken
	}
	return ""
}

func (m *Session) GetSessionUser() *ObjectID {
	if m != nil {
		return m.SessionUser
	}
	return nil
}

type Problem struct {
	Id                   *ObjectID            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty" bson:"_id,omitempty"`
	Title                *string              `protobuf:"bytes,2,opt,name=title" json:"title,omitempty" bson:"title,omitempty"`
	Statement            *string              `protobuf:"bytes,3,opt,name=statement" json:"statement,omitempty" bson:"statement,omitempty"`
	Owner                []*ObjectID          `protobuf:"bytes,4,rep,name=owner" json:"owner,omitempty" bson:"owner,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime" json:"create_time,omitempty" bson:"create_time,omitempty"`
	ShortName            *string              `protobuf:"bytes,6,opt,name=short_name,json=shortName" json:"short_name,omitempty" bson:"short_name,omitempty"`
	Public               *bool                `protobuf:"varint,7,opt,name=public" json:"public,omitempty" bson:"public,omitempty"`
	PublicStats          *ProblemStats        `protobuf:"bytes,8,opt,name=public_stats,json=publicStats" json:"public_stats,omitempty" bson:"public_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *Problem) Reset()         { *m = Problem{} }
func (m *Problem) String() string { return proto.CompactTextString(m) }
func (*Problem) ProtoMessage()    {}
func (*Problem) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{5}
}

func (m *Problem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Problem.Unmarshal(m, b)
}
func (m *Problem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Problem.Marshal(b, m, deterministic)
}
func (m *Problem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Problem.Merge(m, src)
}
func (m *Problem) XXX_Size() int {
	return xxx_messageInfo_Problem.Size(m)
}
func (m *Problem) XXX_DiscardUnknown() {
	xxx_messageInfo_Problem.DiscardUnknown(m)
}

var xxx_messageInfo_Problem proto.InternalMessageInfo

func (m *Problem) GetId() *ObjectID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Problem) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Problem) GetStatement() string {
	if m != nil && m.Statement != nil {
		return *m.Statement
	}
	return ""
}

func (m *Problem) GetOwner() []*ObjectID {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Problem) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Problem) GetShortName() string {
	if m != nil && m.ShortName != nil {
		return *m.ShortName
	}
	return ""
}

func (m *Problem) GetPublic() bool {
	if m != nil && m.Public != nil {
		return *m.Public
	}
	return false
}

func (m *Problem) GetPublicStats() *ProblemStats {
	if m != nil {
		return m.PublicStats
	}
	return nil
}

type ProblemStats struct {
	Accept               *int64   `protobuf:"varint,1,opt,name=accept" json:"accept,omitempty" bson:"accept,omitempty"`
	Submission           *int64   `protobuf:"varint,2,opt,name=submission" json:"submission,omitempty" bson:"submission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ProblemStats) Reset()         { *m = ProblemStats{} }
func (m *ProblemStats) String() string { return proto.CompactTextString(m) }
func (*ProblemStats) ProtoMessage()    {}
func (*ProblemStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{6}
}

func (m *ProblemStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemStats.Unmarshal(m, b)
}
func (m *ProblemStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemStats.Marshal(b, m, deterministic)
}
func (m *ProblemStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemStats.Merge(m, src)
}
func (m *ProblemStats) XXX_Size() int {
	return xxx_messageInfo_ProblemStats.Size(m)
}
func (m *ProblemStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemStats.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemStats proto.InternalMessageInfo

func (m *ProblemStats) GetAccept() int64 {
	if m != nil && m.Accept != nil {
		return *m.Accept
	}
	return 0
}

func (m *ProblemStats) GetSubmission() int64 {
	if m != nil && m.Submission != nil {
		return *m.Submission
	}
	return 0
}

type Contest struct {
	Id                   *ObjectID     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty" bson:"_id,omitempty"`
	Name                 *string       `protobuf:"bytes,2,opt,name=name" json:"name,omitempty" bson:"name,omitempty"`
	Description          *string       `protobuf:"bytes,3,opt,name=description" json:"description,omitempty" bson:"description,omitempty"`
	Owner                *ObjectID     `protobuf:"bytes,4,opt,name=owner" json:"owner,omitempty" bson:"owner,omitempty"`
	State                *ContestState `protobuf:"bytes,5,opt,name=state" json:"state,omitempty" bson:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-" bson:"-"`
	XXX_unrecognized     []byte        `json:"-" bson:"-"`
	XXX_sizecache        int32         `json:"-" bson:"-"`
}

func (m *Contest) Reset()         { *m = Contest{} }
func (m *Contest) String() string { return proto.CompactTextString(m) }
func (*Contest) ProtoMessage()    {}
func (*Contest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{7}
}

func (m *Contest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contest.Unmarshal(m, b)
}
func (m *Contest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contest.Marshal(b, m, deterministic)
}
func (m *Contest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contest.Merge(m, src)
}
func (m *Contest) XXX_Size() int {
	return xxx_messageInfo_Contest.Size(m)
}
func (m *Contest) XXX_DiscardUnknown() {
	xxx_messageInfo_Contest.DiscardUnknown(m)
}

var xxx_messageInfo_Contest proto.InternalMessageInfo

func (m *Contest) GetId() *ObjectID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Contest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Contest) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *Contest) GetOwner() *ObjectID {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Contest) GetState() *ContestState {
	if m != nil {
		return m.State
	}
	return nil
}

type ContestState struct {
	Running              *bool                   `protobuf:"varint,1,opt,name=running" json:"running,omitempty" bson:"running,omitempty"`
	StartTime            *timestamp.Timestamp    `protobuf:"bytes,2,opt,name=start_time,json=startTime" json:"start_time,omitempty" bson:"start_time,omitempty"`
	Problems             []*ContestProblem       `protobuf:"bytes,3,rep,name=problems" json:"problems,omitempty" bson:"problems,omitempty"`
	Schedule             []*ContestSchedule      `protobuf:"bytes,4,rep,name=schedule" json:"schedule,omitempty" bson:"schedule,omitempty"`
	RanklistType         *string                 `protobuf:"bytes,5,opt,name=ranklist_type,json=ranklistType" json:"ranklist_type,omitempty" bson:"ranklist_type,omitempty"`
	RanklistComp         *string                 `protobuf:"bytes,6,opt,name=ranklist_comp,json=ranklistComp" json:"ranklist_comp,omitempty" bson:"ranklist_comp,omitempty"`
	RanklistVisibility   *string                 `protobuf:"bytes,7,opt,name=ranklist_visibility,json=ranklistVisibility" json:"ranklist_visibility,omitempty" bson:"ranklist_visibility,omitempty"`
	JudgeInContest       *bool                   `protobuf:"varint,8,opt,name=judge_in_contest,json=judgeInContest" json:"judge_in_contest,omitempty" bson:"judge_in_contest,omitempty"`
	SubmissionPerProblem *int32                  `protobuf:"varint,9,opt,name=submission_per_problem,json=submissionPerProblem" json:"submission_per_problem,omitempty" bson:"submission_per_problem,omitempty"`
	Clarifications       []*ContestClarification `protobuf:"bytes,10,rep,name=clarifications" json:"clarifications,omitempty" bson:"clarifications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-" bson:"-"`
	XXX_unrecognized     []byte                  `json:"-" bson:"-"`
	XXX_sizecache        int32                   `json:"-" bson:"-"`
}

func (m *ContestState) Reset()         { *m = ContestState{} }
func (m *ContestState) String() string { return proto.CompactTextString(m) }
func (*ContestState) ProtoMessage()    {}
func (*ContestState) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{8}
}

func (m *ContestState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestState.Unmarshal(m, b)
}
func (m *ContestState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestState.Marshal(b, m, deterministic)
}
func (m *ContestState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestState.Merge(m, src)
}
func (m *ContestState) XXX_Size() int {
	return xxx_messageInfo_ContestState.Size(m)
}
func (m *ContestState) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestState.DiscardUnknown(m)
}

var xxx_messageInfo_ContestState proto.InternalMessageInfo

func (m *ContestState) GetRunning() bool {
	if m != nil && m.Running != nil {
		return *m.Running
	}
	return false
}

func (m *ContestState) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *ContestState) GetProblems() []*ContestProblem {
	if m != nil {
		return m.Problems
	}
	return nil
}

func (m *ContestState) GetSchedule() []*ContestSchedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

func (m *ContestState) GetRanklistType() string {
	if m != nil && m.RanklistType != nil {
		return *m.RanklistType
	}
	return ""
}

func (m *ContestState) GetRanklistComp() string {
	if m != nil && m.RanklistComp != nil {
		return *m.RanklistComp
	}
	return ""
}

func (m *ContestState) GetRanklistVisibility() string {
	if m != nil && m.RanklistVisibility != nil {
		return *m.RanklistVisibility
	}
	return ""
}

func (m *ContestState) GetJudgeInContest() bool {
	if m != nil && m.JudgeInContest != nil {
		return *m.JudgeInContest
	}
	return false
}

func (m *ContestState) GetSubmissionPerProblem() int32 {
	if m != nil && m.SubmissionPerProblem != nil {
		return *m.SubmissionPerProblem
	}
	return 0
}

func (m *ContestState) GetClarifications() []*ContestClarification {
	if m != nil {
		return m.Clarifications
	}
	return nil
}

type ContestProblem struct {
	Name                 *string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty" bson:"name,omitempty"`
	Problem              *ObjectID `protobuf:"bytes,2,opt,name=problem" json:"problem,omitempty" bson:"problem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" bson:"-"`
	XXX_unrecognized     []byte    `json:"-" bson:"-"`
	XXX_sizecache        int32     `json:"-" bson:"-"`
}

func (m *ContestProblem) Reset()         { *m = ContestProblem{} }
func (m *ContestProblem) String() string { return proto.CompactTextString(m) }
func (*ContestProblem) ProtoMessage()    {}
func (*ContestProblem) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{9}
}

func (m *ContestProblem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestProblem.Unmarshal(m, b)
}
func (m *ContestProblem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestProblem.Marshal(b, m, deterministic)
}
func (m *ContestProblem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestProblem.Merge(m, src)
}
func (m *ContestProblem) XXX_Size() int {
	return xxx_messageInfo_ContestProblem.Size(m)
}
func (m *ContestProblem) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestProblem.DiscardUnknown(m)
}

var xxx_messageInfo_ContestProblem proto.InternalMessageInfo

func (m *ContestProblem) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ContestProblem) GetProblem() *ObjectID {
	if m != nil {
		return m.Problem
	}
	return nil
}

type ContestSchedule struct {
	Type                 *string              `protobuf:"bytes,1,opt,name=type" json:"type,omitempty" bson:"type,omitempty"`
	Done                 *bool                `protobuf:"varint,2,opt,name=done" json:"done,omitempty" bson:"done,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime" json:"start_time,omitempty" bson:"start_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *ContestSchedule) Reset()         { *m = ContestSchedule{} }
func (m *ContestSchedule) String() string { return proto.CompactTextString(m) }
func (*ContestSchedule) ProtoMessage()    {}
func (*ContestSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{10}
}

func (m *ContestSchedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestSchedule.Unmarshal(m, b)
}
func (m *ContestSchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestSchedule.Marshal(b, m, deterministic)
}
func (m *ContestSchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestSchedule.Merge(m, src)
}
func (m *ContestSchedule) XXX_Size() int {
	return xxx_messageInfo_ContestSchedule.Size(m)
}
func (m *ContestSchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestSchedule.DiscardUnknown(m)
}

var xxx_messageInfo_ContestSchedule proto.InternalMessageInfo

func (m *ContestSchedule) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *ContestSchedule) GetDone() bool {
	if m != nil && m.Done != nil {
		return *m.Done
	}
	return false
}

func (m *ContestSchedule) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

type ContestClarification struct {
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,1,opt,name=create_time,json=createTime" json:"create_time,omitempty" bson:"create_time,omitempty"`
	Title                *string              `protobuf:"bytes,2,opt,name=title" json:"title,omitempty" bson:"title,omitempty"`
	ProblemName          *string              `protobuf:"bytes,3,opt,name=problem_name,json=problemName" json:"problem_name,omitempty" bson:"problem_name,omitempty"`
	Content              *string              `protobuf:"bytes,4,opt,name=content" json:"content,omitempty" bson:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *ContestClarification) Reset()         { *m = ContestClarification{} }
func (m *ContestClarification) String() string { return proto.CompactTextString(m) }
func (*ContestClarification) ProtoMessage()    {}
func (*ContestClarification) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{11}
}

func (m *ContestClarification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestClarification.Unmarshal(m, b)
}
func (m *ContestClarification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestClarification.Marshal(b, m, deterministic)
}
func (m *ContestClarification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestClarification.Merge(m, src)
}
func (m *ContestClarification) XXX_Size() int {
	return xxx_messageInfo_ContestClarification.Size(m)
}
func (m *ContestClarification) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestClarification.DiscardUnknown(m)
}

var xxx_messageInfo_ContestClarification proto.InternalMessageInfo

func (m *ContestClarification) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *ContestClarification) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *ContestClarification) GetProblemName() string {
	if m != nil && m.ProblemName != nil {
		return *m.ProblemName
	}
	return ""
}

func (m *ContestClarification) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

type ContestPlayer struct {
	Id                   *ObjectID                    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty" bson:"_id,omitempty"`
	Contest              *ObjectID                    `protobuf:"bytes,2,opt,name=contest" json:"contest,omitempty" bson:"contest,omitempty"`
	User                 *ObjectID                    `protobuf:"bytes,3,opt,name=user" json:"user,omitempty" bson:"user,omitempty"`
	RegisterTime         *timestamp.Timestamp         `protobuf:"bytes,4,opt,name=register_time,json=registerTime" json:"register_time,omitempty" bson:"register_time,omitempty"`
	Problems             []*ContestPlayerProblemEntry `protobuf:"bytes,5,rep,name=problems" json:"problems,omitempty" bson:"problems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-" bson:"-"`
	XXX_unrecognized     []byte                       `json:"-" bson:"-"`
	XXX_sizecache        int32                        `json:"-" bson:"-"`
}

func (m *ContestPlayer) Reset()         { *m = ContestPlayer{} }
func (m *ContestPlayer) String() string { return proto.CompactTextString(m) }
func (*ContestPlayer) ProtoMessage()    {}
func (*ContestPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{12}
}

func (m *ContestPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestPlayer.Unmarshal(m, b)
}
func (m *ContestPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestPlayer.Marshal(b, m, deterministic)
}
func (m *ContestPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestPlayer.Merge(m, src)
}
func (m *ContestPlayer) XXX_Size() int {
	return xxx_messageInfo_ContestPlayer.Size(m)
}
func (m *ContestPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_ContestPlayer proto.InternalMessageInfo

func (m *ContestPlayer) GetId() *ObjectID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ContestPlayer) GetContest() *ObjectID {
	if m != nil {
		return m.Contest
	}
	return nil
}

func (m *ContestPlayer) GetUser() *ObjectID {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ContestPlayer) GetRegisterTime() *timestamp.Timestamp {
	if m != nil {
		return m.RegisterTime
	}
	return nil
}

func (m *ContestPlayer) GetProblems() []*ContestPlayerProblemEntry {
	if m != nil {
		return m.Problems
	}
	return nil
}

type ContestPlayerProblemEntry struct {
	Name                 *string                                `protobuf:"bytes,5,opt,name=name" json:"name,omitempty" bson:"problems,omitempty"`
	Submissions          []*ContestPlayerProblemSubmissionEntry `protobuf:"bytes,1,rep,name=submissions" json:"submissions,omitempty" bson:"submissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-" bson:"-"`
	XXX_unrecognized     []byte                                 `json:"-" bson:"-"`
	XXX_sizecache        int32                                  `json:"-" bson:"-"`
}

func (m *ContestPlayerProblemEntry) Reset()         { *m = ContestPlayerProblemEntry{} }
func (m *ContestPlayerProblemEntry) String() string { return proto.CompactTextString(m) }
func (*ContestPlayerProblemEntry) ProtoMessage()    {}
func (*ContestPlayerProblemEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{13}
}

func (m *ContestPlayerProblemEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestPlayerProblemEntry.Unmarshal(m, b)
}
func (m *ContestPlayerProblemEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestPlayerProblemEntry.Marshal(b, m, deterministic)
}
func (m *ContestPlayerProblemEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestPlayerProblemEntry.Merge(m, src)
}
func (m *ContestPlayerProblemEntry) XXX_Size() int {
	return xxx_messageInfo_ContestPlayerProblemEntry.Size(m)
}
func (m *ContestPlayerProblemEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestPlayerProblemEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ContestPlayerProblemEntry proto.InternalMessageInfo

func (m *ContestPlayerProblemEntry) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ContestPlayerProblemEntry) GetSubmissions() []*ContestPlayerProblemSubmissionEntry {
	if m != nil {
		return m.Submissions
	}
	return nil
}

type ContestPlayerProblemSubmissionEntry struct {
	SubmissionId         *ObjectID            `protobuf:"bytes,1,opt,name=submission_id,json=submissionId" json:"submission_id,omitempty" bson:"submission_id,omitempty"`
	PenaltyTime          *duration.Duration   `protobuf:"bytes,2,opt,name=penalty_time,json=penaltyTime" json:"penalty_time,omitempty" bson:"penalty_time,omitempty"`
	SubmitTime           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=submit_time,json=submitTime" json:"submit_time,omitempty" bson:"submit_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *ContestPlayerProblemSubmissionEntry) Reset()         { *m = ContestPlayerProblemSubmissionEntry{} }
func (m *ContestPlayerProblemSubmissionEntry) String() string { return proto.CompactTextString(m) }
func (*ContestPlayerProblemSubmissionEntry) ProtoMessage()    {}
func (*ContestPlayerProblemSubmissionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{14}
}

func (m *ContestPlayerProblemSubmissionEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContestPlayerProblemSubmissionEntry.Unmarshal(m, b)
}
func (m *ContestPlayerProblemSubmissionEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContestPlayerProblemSubmissionEntry.Marshal(b, m, deterministic)
}
func (m *ContestPlayerProblemSubmissionEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContestPlayerProblemSubmissionEntry.Merge(m, src)
}
func (m *ContestPlayerProblemSubmissionEntry) XXX_Size() int {
	return xxx_messageInfo_ContestPlayerProblemSubmissionEntry.Size(m)
}
func (m *ContestPlayerProblemSubmissionEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ContestPlayerProblemSubmissionEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ContestPlayerProblemSubmissionEntry proto.InternalMessageInfo

func (m *ContestPlayerProblemSubmissionEntry) GetSubmissionId() *ObjectID {
	if m != nil {
		return m.SubmissionId
	}
	return nil
}

func (m *ContestPlayerProblemSubmissionEntry) GetPenaltyTime() *duration.Duration {
	if m != nil {
		return m.PenaltyTime
	}
	return nil
}

func (m *ContestPlayerProblemSubmissionEntry) GetSubmitTime() *timestamp.Timestamp {
	if m != nil {
		return m.SubmitTime
	}
	return nil
}

type Article struct {
	Id                   *ObjectID            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty" bson:"_id,omitempty"`
	Title                *string              `protobuf:"bytes,2,opt,name=title" json:"title,omitempty" bson:"title,omitempty"`
	Owner                *ObjectID            `protobuf:"bytes,3,opt,name=owner" json:"owner,omitempty" bson:"owner,omitempty"`
	Text                 *string              `protobuf:"bytes,4,opt,name=text" json:"text,omitempty" bson:"text,omitempty"`
	Reply                []*Reply             `protobuf:"bytes,5,rep,name=reply" json:"reply,omitempty" bson:"reply,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime" json:"create_time,omitempty" bson:"create_time,omitempty"`
	LastEditTime         *timestamp.Timestamp `protobuf:"bytes,7,opt,name=last_edit_time,json=lastEditTime" json:"last_edit_time,omitempty" bson:"last_edit_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{15}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetId() *ObjectID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Article) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Article) GetOwner() *ObjectID {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Article) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *Article) GetReply() []*Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *Article) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Article) GetLastEditTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastEditTime
	}
	return nil
}

type Reply struct {
	Owner                *ObjectID            `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty" bson:"owner,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,2,opt,name=create_time,json=createTime" json:"create_time,omitempty" bson:"create_time,omitempty"`
	LastEditTime         *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_edit_time,json=lastEditTime" json:"last_edit_time,omitempty" bson:"last_edit_time,omitempty"`
	Text                 *string              `protobuf:"bytes,4,opt,name=text" json:"text,omitempty" bson:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{16}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetOwner() *ObjectID {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Reply) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Reply) GetLastEditTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastEditTime
	}
	return nil
}

func (m *Reply) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

type Judger struct {
	Token                *string  `protobuf:"bytes,1,opt,name=token" json:"token,omitempty" bson:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Judger) Reset()         { *m = Judger{} }
func (m *Judger) String() string { return proto.CompactTextString(m) }
func (*Judger) ProtoMessage()    {}
func (*Judger) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{17}
}

func (m *Judger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Judger.Unmarshal(m, b)
}
func (m *Judger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Judger.Marshal(b, m, deterministic)
}
func (m *Judger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Judger.Merge(m, src)
}
func (m *Judger) XXX_Size() int {
	return xxx_messageInfo_Judger.Size(m)
}
func (m *Judger) XXX_DiscardUnknown() {
	xxx_messageInfo_Judger.DiscardUnknown(m)
}

var xxx_messageInfo_Judger proto.InternalMessageInfo

func (m *Judger) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "syzoj.server.User")
	proto.RegisterType((*UserAuth)(nil), "syzoj.server.UserAuth")
	proto.RegisterType((*Submission)(nil), "syzoj.server.Submission")
	proto.RegisterType((*JudgeQueueStatus)(nil), "syzoj.server.JudgeQueueStatus")
	proto.RegisterType((*Session)(nil), "syzoj.server.Session")
	proto.RegisterType((*Problem)(nil), "syzoj.server.Problem")
	proto.RegisterType((*ProblemStats)(nil), "syzoj.server.ProblemStats")
	proto.RegisterType((*Contest)(nil), "syzoj.server.Contest")
	proto.RegisterType((*ContestState)(nil), "syzoj.server.ContestState")
	proto.RegisterType((*ContestProblem)(nil), "syzoj.server.ContestProblem")
	proto.RegisterType((*ContestSchedule)(nil), "syzoj.server.ContestSchedule")
	proto.RegisterType((*ContestClarification)(nil), "syzoj.server.ContestClarification")
	proto.RegisterType((*ContestPlayer)(nil), "syzoj.server.ContestPlayer")
	proto.RegisterType((*ContestPlayerProblemEntry)(nil), "syzoj.server.ContestPlayerProblemEntry")
	proto.RegisterType((*ContestPlayerProblemSubmissionEntry)(nil), "syzoj.server.ContestPlayerProblemSubmissionEntry")
	proto.RegisterType((*Article)(nil), "syzoj.server.Article")
	proto.RegisterType((*Reply)(nil), "syzoj.server.Reply")
	proto.RegisterType((*Judger)(nil), "syzoj.server.Judger")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 1625 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x59, 0xcd, 0x8f, 0x14, 0x45,
	0x14, 0x4f, 0xcf, 0xf7, 0xbe, 0x9d, 0x5d, 0x48, 0x81, 0x38, 0xbb, 0xb0, 0xcb, 0xd2, 0x10, 0x58,
	0x13, 0x98, 0x0d, 0xc4, 0x84, 0x88, 0x31, 0xca, 0x2c, 0x10, 0xd7, 0x88, 0xe2, 0x2e, 0x7e, 0x61,
	0xc2, 0xd8, 0xd3, 0x53, 0xcc, 0xd6, 0xd2, 0x5f, 0x76, 0x55, 0x2f, 0x8c, 0xf1, 0x68, 0x3c, 0x7b,
	0xf0, 0xe4, 0xc1, 0xbb, 0xf1, 0x8f, 0xf0, 0x68, 0x4c, 0xd4, 0xff, 0xc1, 0xa3, 0x47, 0xcf, 0x5e,
	0x4c, 0x7d, 0xf4, 0x4c, 0xbd, 0xde, 0x81, 0x1d, 0x74, 0xd0, 0x0b, 0x61, 0xde, 0x7b, 0xbf, 0x5f,
	0x55, 0xbf, 0x7a, 0x5f, 0x55, 0x0b, 0xf3, 0x61, 0xdc, 0xa7, 0x41, 0x3b, 0x49, 0x63, 0x11, 0x93,
	0x26, 0x1f, 0x7e, 0x1e, 0xef, 0xb5, 0x39, 0x4d, 0xf7, 0x69, 0xba, 0x7c, 0x7a, 0x10, 0xc7, 0x83,
	0x80, 0x6e, 0x28, 0x5d, 0x2f, 0x7b, 0xb0, 0x21, 0x58, 0x48, 0xb9, 0xf0, 0xc2, 0x44, 0x9b, 0x2f,
	0xaf, 0x16, 0x0d, 0xfa, 0x59, 0xea, 0x09, 0x16, 0x47, 0x46, 0xdf, 0x14, 0xde, 0x60, 0x40, 0x53,
	0xf3, 0xeb, 0x48, 0x92, 0xb2, 0x90, 0x09, 0xb6, 0x4f, 0x8d, 0x60, 0x7e, 0x2f, 0xeb, 0x0f, 0xcc,
	0x0f, 0xf7, 0x8f, 0x12, 0x54, 0xde, 0xe7, 0x34, 0x25, 0x37, 0xa0, 0xc4, 0xfa, 0x2d, 0x67, 0xcd,
	0x59, 0x9f, 0xbf, 0xb2, 0xd4, 0xd6, 0x1b, 0x1a, 0x23, 0xdf, 0xed, 0xed, 0x51, 0x5f, 0x6c, 0xdd,
	0xe8, 0x2c, 0x7d, 0xfb, 0xe5, 0x77, 0xe5, 0xe3, 0x3d, 0x1e, 0x47, 0xd7, 0xdc, 0x2e, 0xeb, 0x5f,
	0x8c, 0x43, 0x26, 0x68, 0x98, 0x88, 0xa1, 0xbb, 0x5d, 0x62, 0x7d, 0x72, 0x0d, 0x1a, 0x19, 0xa7,
	0x69, 0xe4, 0x85, 0xb4, 0x55, 0x5a, 0x73, 0xd6, 0xe7, 0x3a, 0xab, 0x12, 0xb0, 0xa4, 0x01, 0xb9,
	0xca, 0x46, 0x8d, 0xec, 0xc9, 0x65, 0xa8, 0xd2, 0xd0, 0x63, 0x41, 0xab, 0xac, 0x80, 0x27, 0x25,
	0xf0, 0x84, 0x06, 0x2a, 0xb9, 0x8d, 0xd2, 0x96, 0xa4, 0x0f, 0x0b, 0x29, 0x1d, 0x30, 0x2e, 0x68,
	0xda, 0x95, 0x5e, 0x6a, 0x55, 0xd4, 0xfe, 0x97, 0xdb, 0xda, 0x43, 0xed, 0xdc, 0x43, 0xed, 0xbb,
	0xb9, 0x0b, 0x3b, 0x67, 0x25, 0xed, 0xaa, 0xa6, 0x45, 0x58, 0x9b, 0xbe, 0x99, 0x6b, 0x24, 0x8e,
	0xdc, 0x82, 0x8a, 0x97, 0x89, 0xdd, 0x56, 0x55, 0x91, 0x9f, 0x68, 0xdb, 0xa7, 0xd5, 0x96, 0xce,
	0xbb, 0x9e, 0x89, 0xdd, 0xce, 0xb2, 0x24, 0x7e, 0x41, 0x13, 0x4b, 0x73, 0x9b, 0x4f, 0xe1, 0xdd,
	0x2f, 0xa0, 0x91, 0x5b, 0x93, 0x97, 0xa1, 0x16, 0x52, 0xb1, 0x1b, 0x6b, 0x97, 0x97, 0x3b, 0xa7,
	0x24, 0xfa, 0x45, 0x8d, 0xd6, 0x0a, 0x1b, 0x6f, 0x6c, 0xa5, 0x7b, 0x13, 0x8f, 0xf3, 0x47, 0x71,
	0xda, 0x57, 0xee, 0x6d, 0x22, 0xf7, 0xe6, 0x2a, 0xe4, 0xde, 0x5c, 0xe8, 0xfe, 0x50, 0x03, 0xd8,
	0xc9, 0x7a, 0x21, 0xe3, 0x9c, 0xc5, 0xd1, 0x8c, 0xce, 0xbb, 0x0d, 0x15, 0x31, 0x4c, 0xf2, 0xb3,
	0xb6, 0x5d, 0x20, 0xc5, 0xc8, 0x05, 0x52, 0x40, 0xb6, 0xa0, 0x22, 0xcf, 0x5b, 0x1d, 0xf1, 0x53,
	0xd7, 0xb5, 0xa9, 0x24, 0x02, 0x51, 0x49, 0x01, 0x79, 0x1b, 0xaa, 0xf1, 0xa3, 0x88, 0xa6, 0xad,
	0xca, 0x5a, 0xf9, 0xe9, 0x5c, 0x76, 0x24, 0x29, 0x08, 0x8a, 0x24, 0x25, 0x21, 0xdb, 0x50, 0x4f,
	0xd2, 0xb8, 0x17, 0xd0, 0xd0, 0x1c, 0xf3, 0x53, 0xf8, 0x56, 0x24, 0x5f, 0xcb, 0xf8, 0x5c, 0x83,
	0x6c, 0xc6, 0x9c, 0x88, 0xdc, 0x87, 0x79, 0x2e, 0x1d, 0x2e, 0x74, 0x6c, 0xd6, 0x0e, 0x8d, 0xcd,
	0x33, 0x92, 0xf8, 0x94, 0x26, 0xb6, 0x90, 0x36, 0x39, 0x68, 0xb9, 0x8a, 0xcb, 0x0f, 0xa1, 0xee,
	0xc7, 0x91, 0xa0, 0x91, 0x68, 0xd5, 0x15, 0xf7, 0xaa, 0xd9, 0xb3, 0x4e, 0xf0, 0xf1, 0x61, 0x6f,
	0x6a, 0x2b, 0xb4, 0x71, 0x83, 0x44, 0x1b, 0x37, 0x32, 0xb2, 0x03, 0xb5, 0x94, 0xf2, 0x2c, 0x10,
	0xad, 0x86, 0xe2, 0x5d, 0x79, 0x02, 0xef, 0xb6, 0x32, 0x42, 0xb1, 0xab, 0x71, 0x28, 0x76, 0xb5,
	0x88, 0xec, 0x03, 0x51, 0xf8, 0xee, 0x67, 0x19, 0xcd, 0x68, 0x97, 0x0b, 0x4f, 0x64, 0xbc, 0x35,
	0x87, 0x36, 0x6e, 0x72, 0xea, 0x2d, 0x69, 0xf7, 0x9e, 0x34, 0xdb, 0x51, 0x56, 0x9d, 0x75, 0xb9,
	0xc2, 0x59, 0xbd, 0xc2, 0x41, 0x12, 0x7b, 0xb5, 0xa3, 0x7b, 0x05, 0xac, 0xcc, 0xb4, 0x24, 0xeb,
	0x05, 0xcc, 0x6f, 0xc1, 0x9a, 0xb3, 0xde, 0x40, 0xbb, 0xd5, 0x0a, 0xb4, 0x5b, 0x2d, 0x72, 0x6f,
	0xc3, 0xd1, 0xe2, 0x2e, 0xc8, 0x2b, 0xd0, 0x60, 0x91, 0x5e, 0x59, 0x25, 0x4e, 0x03, 0x65, 0x5f,
	0xae, 0x42, 0x1e, 0x65, 0x91, 0x22, 0x70, 0xff, 0x72, 0xa0, 0xbe, 0x43, 0x67, 0x99, 0x79, 0x6f,
	0xc2, 0x02, 0xd7, 0x84, 0x5d, 0x11, 0x3f, 0xa4, 0x91, 0x49, 0x41, 0xbb, 0xbc, 0x21, 0x3d, 0x2a,
	0x6f, 0x46, 0x73, 0x57, 0x2a, 0xc8, 0xa7, 0x90, 0xff, 0xee, 0x4e, 0x97, 0x9b, 0xae, 0x5c, 0x63,
	0x05, 0xaf, 0x51, 0xcc, 0xd1, 0x79, 0xa3, 0x90, 0x05, 0xcf, 0xfd, 0xb9, 0x02, 0xf5, 0x3b, 0x26,
	0x29, 0x66, 0xf3, 0xf5, 0x97, 0xa1, 0x2a, 0x98, 0x08, 0xf2, 0xc2, 0x63, 0x67, 0xb8, 0x92, 0xa3,
	0x0c, 0x57, 0x12, 0xf2, 0x1a, 0xcc, 0xc9, 0x70, 0xa1, 0xa1, 0xcc, 0x17, 0xdd, 0x62, 0x4e, 0x4b,
	0xd8, 0xb2, 0xf9, 0x90, 0x5c, 0x67, 0x43, 0xc7, 0x88, 0x19, 0x97, 0x9b, 0xfb, 0x30, 0xef, 0xa7,
	0xd4, 0x13, 0x54, 0x97, 0x86, 0xea, 0x33, 0x95, 0x06, 0x0b, 0x89, 0x4a, 0x83, 0x96, 0xab, 0xd2,
	0xf0, 0x3a, 0x00, 0xdf, 0x8d, 0x53, 0xd1, 0x55, 0x9d, 0xb8, 0xa6, 0xbe, 0x76, 0x4d, 0x52, 0x9c,
	0x34, 0x5f, 0x3b, 0x52, 0xe2, 0xcf, 0x95, 0xe2, 0x77, 0x64, 0x33, 0x1e, 0x67, 0x4d, 0x7d, 0xfa,
	0xac, 0x21, 0x1e, 0x34, 0xf5, 0xff, 0x54, 0x66, 0x72, 0x53, 0x3e, 0x96, 0x71, 0x76, 0x9b, 0x48,
	0x90, 0x49, 0xc5, 0x51, 0x2c, 0xd9, 0x50, 0x14, 0x4b, 0x5a, 0xa1, 0x00, 0xee, 0x57, 0x0e, 0x34,
	0x6d, 0x06, 0xb9, 0x53, 0xcf, 0xf7, 0x69, 0x22, 0x26, 0x74, 0x52, 0xad, 0x40, 0x3b, 0xd5, 0x22,
	0xf2, 0x06, 0xe8, 0x4a, 0xaa, 0x82, 0x54, 0x45, 0x51, 0x19, 0x3b, 0x68, 0xa4, 0x3c, 0x58, 0x7d,
	0x95, 0xd8, 0xfd, 0xbd, 0x04, 0x75, 0x55, 0x58, 0xb9, 0x98, 0x5d, 0x33, 0xb5, 0x06, 0x27, 0xbb,
	0x03, 0x16, 0x0f, 0x4a, 0xd9, 0x91, 0x4d, 0x98, 0xef, 0x53, 0xee, 0xa7, 0x2c, 0x91, 0xc3, 0x9f,
	0x89, 0x69, 0x3b, 0x50, 0x2c, 0x2d, 0xf2, 0xa7, 0x25, 0xb7, 0xe3, 0xda, 0xf9, 0xf7, 0x71, 0x7d,
	0x1b, 0xaa, 0x2a, 0x65, 0x46, 0x11, 0x8d, 0x4e, 0xde, 0xb8, 0x4b, 0x9e, 0x1b, 0x45, 0x74, 0x0a,
	0x83, 0xe8, 0x94, 0xc4, 0xfd, 0xb3, 0x06, 0x4d, 0x1b, 0x44, 0xae, 0x42, 0x3d, 0xcd, 0xa2, 0x88,
	0x45, 0x03, 0x53, 0x81, 0xed, 0x96, 0x66, 0x34, 0xa8, 0x00, 0x1b, 0x19, 0xf9, 0x04, 0x80, 0x0b,
	0x2f, 0x35, 0xad, 0xb8, 0x74, 0x68, 0xbe, 0xa1, 0x58, 0x18, 0x01, 0x8b, 0xb5, 0x21, 0xd5, 0x8d,
	0xf8, 0x23, 0x68, 0x98, 0x9e, 0xcf, 0x5b, 0x65, 0x55, 0x1e, 0x4e, 0x4d, 0xfc, 0x70, 0x13, 0xb7,
	0x78, 0x68, 0x33, 0x40, 0x3c, 0xb4, 0x19, 0x21, 0xf9, 0x18, 0x1a, 0xdc, 0xdf, 0xa5, 0xfd, 0x2c,
	0xa0, 0xa6, 0xf0, 0xac, 0x4c, 0x76, 0xa9, 0x31, 0x42, 0xd4, 0x39, 0x12, 0x51, 0xe7, 0x42, 0xd9,
	0x40, 0x52, 0x2f, 0x7a, 0x18, 0x30, 0x2e, 0xba, 0x6a, 0x86, 0xab, 0x1e, 0x68, 0x20, 0x48, 0x8f,
	0xe7, 0x63, 0xa3, 0xb9, 0x2b, 0x87, 0x3a, 0x9b, 0xc9, 0x8f, 0xc3, 0xc4, 0xd4, 0x9b, 0x89, 0x4c,
	0x52, 0x3f, 0x91, 0x69, 0x33, 0x0e, 0x13, 0x72, 0x0f, 0x8e, 0x8d, 0x2c, 0xf7, 0x19, 0x67, 0x3d,
	0x16, 0x30, 0x31, 0x54, 0x25, 0x68, 0xae, 0xf3, 0x92, 0xe4, 0x3b, 0x57, 0xe0, 0x1b, 0x5b, 0xd9,
	0xac, 0x24, 0xd7, 0x7f, 0x30, 0x52, 0x93, 0x3b, 0xa0, 0x67, 0x83, 0x2e, 0x8b, 0xba, 0xbe, 0xf6,
	0x9a, 0xaa, 0x4f, 0x8d, 0xce, 0x79, 0x49, 0x7c, 0xc6, 0x9e, 0x2e, 0xc6, 0x26, 0x36, 0xeb, 0xa2,
	0x52, 0x6e, 0x45, 0x79, 0xd6, 0xf7, 0xe0, 0xc4, 0xb8, 0x1e, 0x74, 0x13, 0x9a, 0x76, 0xf3, 0x11,
	0x52, 0x4e, 0x35, 0xd5, 0xce, 0x45, 0xc9, 0x7b, 0xa1, 0x58, 0x4f, 0x6c, 0x43, 0x9b, 0xfd, 0xf8,
	0xd8, 0xe4, 0x0e, 0x4d, 0xf3, 0x76, 0x99, 0xc0, 0xa2, 0x1f, 0x78, 0x29, 0x7b, 0xc0, 0x7c, 0x75,
	0xc5, 0xe3, 0x2d, 0x50, 0x61, 0xe0, 0x4e, 0x0c, 0x83, 0x4d, 0xdb, 0xb4, 0x73, 0x4e, 0xae, 0x7f,
	0xda, 0xf4, 0x0c, 0x44, 0x82, 0xbe, 0x0a, 0xab, 0xdc, 0x6f, 0x1c, 0x58, 0xc4, 0xf1, 0x3a, 0x2a,
	0x4c, 0xce, 0x94, 0x85, 0xc9, 0x1a, 0xa6, 0x4b, 0x33, 0x1a, 0xa6, 0xdd, 0xdf, 0x1c, 0x38, 0x52,
	0x08, 0xf6, 0xd1, 0xed, 0xc3, 0x99, 0xf2, 0xf6, 0xd1, 0x86, 0x4a, 0x3f, 0x8e, 0x74, 0xfa, 0x37,
	0x90, 0xbd, 0x14, 0x23, 0x7b, 0x29, 0x28, 0x14, 0x8d, 0xf2, 0x4c, 0x8b, 0x86, 0xfb, 0x7d, 0x09,
	0x8e, 0x4f, 0x3a, 0xb6, 0xe2, 0x6c, 0xe0, 0xcc, 0x7a, 0x36, 0xf8, 0x07, 0xb3, 0xd3, 0x4d, 0x68,
	0x9a, 0x73, 0xd0, 0x03, 0x85, 0x6e, 0x35, 0xa8, 0x77, 0x5b, 0x6a, 0xdc, 0xbb, 0xb5, 0x42, 0x0d,
	0x15, 0x57, 0xc7, 0x17, 0x96, 0x8a, 0x62, 0x98, 0xf2, 0x42, 0xe2, 0xfe, 0x58, 0x86, 0x85, 0x3c,
	0x26, 0x03, 0x6f, 0x38, 0xb3, 0xe7, 0x8a, 0x6d, 0xb3, 0x21, 0x2e, 0x9e, 0x2d, 0x50, 0x27, 0x14,
	0x87, 0x9c, 0x68, 0x96, 0x57, 0xdc, 0xff, 0xe6, 0x79, 0xc3, 0xb7, 0xba, 0x57, 0x55, 0x15, 0x97,
	0x0b, 0x93, 0xbb, 0x97, 0xf2, 0xbc, 0xa9, 0x09, 0x37, 0x23, 0x91, 0x0e, 0xa7, 0x6f, 0x64, 0xee,
	0x4f, 0x0e, 0x2c, 0x3d, 0x91, 0x87, 0x5c, 0x31, 0x05, 0xa6, 0x7a, 0xe0, 0xc9, 0x68, 0x12, 0xab,
	0x2e, 0x32, 0xfb, 0xe6, 0x76, 0xad, 0x2a, 0x26, 0x6f, 0x39, 0x6a, 0xe7, 0x97, 0x0f, 0xdf, 0xf9,
	0xf8, 0xfa, 0xaa, 0xbf, 0xe1, 0xc0, 0xa5, 0x5b, 0x13, 0xe2, 0xcb, 0xcc, 0x58, 0xee, 0xfe, 0x52,
	0x82, 0xb3, 0x53, 0xf0, 0x12, 0x1f, 0x16, 0xac, 0xa2, 0x3f, 0x4d, 0xb0, 0xa2, 0xbb, 0x9b, 0x0d,
	0xc5, 0x77, 0xb7, 0x91, 0x66, 0xab, 0x2f, 0xef, 0x6e, 0x09, 0x8d, 0xbc, 0x40, 0x0c, 0xed, 0xc1,
	0x66, 0xe9, 0x40, 0x80, 0xdc, 0x30, 0x2f, 0x84, 0x38, 0x67, 0x2d, 0x24, 0xce, 0x59, 0xad, 0x50,
	0xd1, 0x51, 0x78, 0xc4, 0x28, 0xcf, 0xf8, 0x11, 0xc3, 0xfd, 0xba, 0x02, 0xf5, 0xeb, 0xa9, 0x60,
	0x7e, 0x40, 0xff, 0xbf, 0xbb, 0xe1, 0x68, 0x08, 0x2e, 0xcf, 0x62, 0x08, 0x96, 0x6d, 0x89, 0x3e,
	0xce, 0x6b, 0x1c, 0x6a, 0x4b, 0xf4, 0xb1, 0xc0, 0x6d, 0x89, 0x3e, 0x16, 0xe4, 0x16, 0x54, 0x53,
	0x9a, 0x04, 0x43, 0x93, 0x7d, 0xc7, 0x70, 0x0c, 0x6f, 0x4b, 0x15, 0x5a, 0x57, 0x19, 0xa3, 0x75,
	0x95, 0xa4, 0xd8, 0x38, 0x6a, 0xb3, 0x6e, 0x1c, 0x0f, 0x60, 0x31, 0xf0, 0xb8, 0xe8, 0xd2, 0x7e,
	0x1e, 0x0d, 0xf5, 0x43, 0x97, 0xb0, 0x67, 0x10, 0x0c, 0x46, 0x41, 0x2d, 0x55, 0x37, 0xfb, 0x26,
	0x24, 0x7e, 0x2d, 0x41, 0x55, 0x7d, 0xf5, 0xf8, 0x5c, 0x9c, 0x59, 0x9c, 0x4b, 0xc1, 0x3f, 0xa5,
	0xe7, 0xef, 0x9f, 0xf2, 0xf3, 0xf0, 0xcf, 0xb3, 0xc6, 0x97, 0xfb, 0x2a, 0xd4, 0xd4, 0x5b, 0x56,
	0xaa, 0x52, 0x43, 0x3d, 0x16, 0x39, 0x07, 0x53, 0xa3, 0xf8, 0x48, 0xa4, 0x2d, 0x3b, 0xeb, 0xf7,
	0xce, 0x0f, 0x98, 0xd8, 0xcd, 0x7a, 0x6d, 0x3f, 0x0e, 0x37, 0x94, 0xff, 0xf5, 0xbf, 0x97, 0xa2,
	0xc1, 0xa5, 0x41, 0xbc, 0xe1, 0x25, 0xc9, 0x86, 0xfa, 0x5b, 0xc6, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xc1, 0xd6, 0x4d, 0x20, 0xd3, 0x18, 0x00, 0x00,
}
