// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testContestRanklists(t *testing.T) {
	t.Parallel()

	query := ContestRanklists()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testContestRanklistsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContestRanklist{}
	if err = randomize.Struct(seed, o, contestRanklistDBTypes, true, contestRanklistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ContestRanklists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testContestRanklistsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContestRanklist{}
	if err = randomize.Struct(seed, o, contestRanklistDBTypes, true, contestRanklistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ContestRanklists().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ContestRanklists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testContestRanklistsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContestRanklist{}
	if err = randomize.Struct(seed, o, contestRanklistDBTypes, true, contestRanklistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ContestRanklistSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ContestRanklists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testContestRanklistsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContestRanklist{}
	if err = randomize.Struct(seed, o, contestRanklistDBTypes, true, contestRanklistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ContestRanklistExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ContestRanklist exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ContestRanklistExists to return true, but got false.")
	}
}

func testContestRanklistsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContestRanklist{}
	if err = randomize.Struct(seed, o, contestRanklistDBTypes, true, contestRanklistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	contestRanklistFound, err := FindContestRanklist(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if contestRanklistFound == nil {
		t.Error("want a record, got nil")
	}
}

func testContestRanklistsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContestRanklist{}
	if err = randomize.Struct(seed, o, contestRanklistDBTypes, true, contestRanklistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ContestRanklists().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testContestRanklistsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContestRanklist{}
	if err = randomize.Struct(seed, o, contestRanklistDBTypes, true, contestRanklistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ContestRanklists().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testContestRanklistsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	contestRanklistOne := &ContestRanklist{}
	contestRanklistTwo := &ContestRanklist{}
	if err = randomize.Struct(seed, contestRanklistOne, contestRanklistDBTypes, false, contestRanklistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}
	if err = randomize.Struct(seed, contestRanklistTwo, contestRanklistDBTypes, false, contestRanklistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = contestRanklistOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = contestRanklistTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ContestRanklists().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testContestRanklistsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	contestRanklistOne := &ContestRanklist{}
	contestRanklistTwo := &ContestRanklist{}
	if err = randomize.Struct(seed, contestRanklistOne, contestRanklistDBTypes, false, contestRanklistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}
	if err = randomize.Struct(seed, contestRanklistTwo, contestRanklistDBTypes, false, contestRanklistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = contestRanklistOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = contestRanklistTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ContestRanklists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func contestRanklistBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ContestRanklist) error {
	*o = ContestRanklist{}
	return nil
}

func contestRanklistAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ContestRanklist) error {
	*o = ContestRanklist{}
	return nil
}

func contestRanklistAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ContestRanklist) error {
	*o = ContestRanklist{}
	return nil
}

func contestRanklistBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ContestRanklist) error {
	*o = ContestRanklist{}
	return nil
}

func contestRanklistAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ContestRanklist) error {
	*o = ContestRanklist{}
	return nil
}

func contestRanklistBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ContestRanklist) error {
	*o = ContestRanklist{}
	return nil
}

func contestRanklistAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ContestRanklist) error {
	*o = ContestRanklist{}
	return nil
}

func contestRanklistBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ContestRanklist) error {
	*o = ContestRanklist{}
	return nil
}

func contestRanklistAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ContestRanklist) error {
	*o = ContestRanklist{}
	return nil
}

func testContestRanklistsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ContestRanklist{}
	o := &ContestRanklist{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, contestRanklistDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ContestRanklist object: %s", err)
	}

	AddContestRanklistHook(boil.BeforeInsertHook, contestRanklistBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	contestRanklistBeforeInsertHooks = []ContestRanklistHook{}

	AddContestRanklistHook(boil.AfterInsertHook, contestRanklistAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	contestRanklistAfterInsertHooks = []ContestRanklistHook{}

	AddContestRanklistHook(boil.AfterSelectHook, contestRanklistAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	contestRanklistAfterSelectHooks = []ContestRanklistHook{}

	AddContestRanklistHook(boil.BeforeUpdateHook, contestRanklistBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	contestRanklistBeforeUpdateHooks = []ContestRanklistHook{}

	AddContestRanklistHook(boil.AfterUpdateHook, contestRanklistAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	contestRanklistAfterUpdateHooks = []ContestRanklistHook{}

	AddContestRanklistHook(boil.BeforeDeleteHook, contestRanklistBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	contestRanklistBeforeDeleteHooks = []ContestRanklistHook{}

	AddContestRanklistHook(boil.AfterDeleteHook, contestRanklistAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	contestRanklistAfterDeleteHooks = []ContestRanklistHook{}

	AddContestRanklistHook(boil.BeforeUpsertHook, contestRanklistBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	contestRanklistBeforeUpsertHooks = []ContestRanklistHook{}

	AddContestRanklistHook(boil.AfterUpsertHook, contestRanklistAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	contestRanklistAfterUpsertHooks = []ContestRanklistHook{}
}

func testContestRanklistsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContestRanklist{}
	if err = randomize.Struct(seed, o, contestRanklistDBTypes, true, contestRanklistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ContestRanklists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testContestRanklistsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContestRanklist{}
	if err = randomize.Struct(seed, o, contestRanklistDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(contestRanklistColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := ContestRanklists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testContestRanklistsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContestRanklist{}
	if err = randomize.Struct(seed, o, contestRanklistDBTypes, true, contestRanklistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testContestRanklistsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContestRanklist{}
	if err = randomize.Struct(seed, o, contestRanklistDBTypes, true, contestRanklistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ContestRanklistSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testContestRanklistsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ContestRanklist{}
	if err = randomize.Struct(seed, o, contestRanklistDBTypes, true, contestRanklistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ContestRanklists().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	contestRanklistDBTypes = map[string]string{`ID`: `int`, `RankingParams`: `longtext`, `Ranklist`: `longtext`}
	_                      = bytes.MinRead
)

func testContestRanklistsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(contestRanklistPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(contestRanklistAllColumns) == len(contestRanklistPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ContestRanklist{}
	if err = randomize.Struct(seed, o, contestRanklistDBTypes, true, contestRanklistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ContestRanklists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, contestRanklistDBTypes, true, contestRanklistPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testContestRanklistsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(contestRanklistAllColumns) == len(contestRanklistPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ContestRanklist{}
	if err = randomize.Struct(seed, o, contestRanklistDBTypes, true, contestRanklistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ContestRanklists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, contestRanklistDBTypes, true, contestRanklistPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(contestRanklistAllColumns, contestRanklistPrimaryKeyColumns) {
		fields = contestRanklistAllColumns
	} else {
		fields = strmangle.SetComplement(
			contestRanklistAllColumns,
			contestRanklistPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ContestRanklistSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testContestRanklistsUpsert(t *testing.T) {
	t.Parallel()

	if len(contestRanklistAllColumns) == len(contestRanklistPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLContestRanklistUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ContestRanklist{}
	if err = randomize.Struct(seed, &o, contestRanklistDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ContestRanklist: %s", err)
	}

	count, err := ContestRanklists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, contestRanklistDBTypes, false, contestRanklistPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ContestRanklist struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ContestRanklist: %s", err)
	}

	count, err = ContestRanklists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
