// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package legacy

import (
	fmt "fmt"
	_ "github.com/amsokol/protoc-gen-gotag/tagger"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProblemData struct {
	TimeLimit            *int64   `protobuf:"varint,1,opt,name=time_limit,json=timeLimit" json:"time_limit,omitempty" bson:"time_limit,omitempty"`
	MemoryLimit          *int64   `protobuf:"varint,2,opt,name=memory_limit,json=memoryLimit" json:"memory_limit,omitempty" bson:"memory_limit,omitempty"`
	FileIo               *bool    `protobuf:"varint,3,opt,name=file_io,json=fileIo" json:"file_io,omitempty" bson:"file_io,omitempty"`
	FileIoInputName      *string  `protobuf:"bytes,4,opt,name=file_io_input_name,json=fileIoInputName" json:"file_io_input_name,omitempty" bson:"file_io_input_name,omitempty"`
	FileIoOutputName     *string  `protobuf:"bytes,5,opt,name=file_io_output_name,json=fileIoOutputName" json:"file_io_output_name,omitempty" bson:"file_io_output_name,omitempty"`
	Type                 *int32   `protobuf:"varint,6,opt,name=type" json:"type,omitempty" bson:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ProblemData) Reset()         { *m = ProblemData{} }
func (m *ProblemData) String() string { return proto.CompactTextString(m) }
func (*ProblemData) ProtoMessage()    {}
func (*ProblemData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *ProblemData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemData.Unmarshal(m, b)
}
func (m *ProblemData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemData.Marshal(b, m, deterministic)
}
func (m *ProblemData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemData.Merge(m, src)
}
func (m *ProblemData) XXX_Size() int {
	return xxx_messageInfo_ProblemData.Size(m)
}
func (m *ProblemData) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemData.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemData proto.InternalMessageInfo

func (m *ProblemData) GetTimeLimit() int64 {
	if m != nil && m.TimeLimit != nil {
		return *m.TimeLimit
	}
	return 0
}

func (m *ProblemData) GetMemoryLimit() int64 {
	if m != nil && m.MemoryLimit != nil {
		return *m.MemoryLimit
	}
	return 0
}

func (m *ProblemData) GetFileIo() bool {
	if m != nil && m.FileIo != nil {
		return *m.FileIo
	}
	return false
}

func (m *ProblemData) GetFileIoInputName() string {
	if m != nil && m.FileIoInputName != nil {
		return *m.FileIoInputName
	}
	return ""
}

func (m *ProblemData) GetFileIoOutputName() string {
	if m != nil && m.FileIoOutputName != nil {
		return *m.FileIoOutputName
	}
	return ""
}

func (m *ProblemData) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

type SubmissionContent struct {
	Language             *string  `protobuf:"bytes,1,opt,name=language" json:"language,omitempty" bson:"language,omitempty"`
	Code                 *string  `protobuf:"bytes,2,opt,name=code" json:"code,omitempty" bson:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *SubmissionContent) Reset()         { *m = SubmissionContent{} }
func (m *SubmissionContent) String() string { return proto.CompactTextString(m) }
func (*SubmissionContent) ProtoMessage()    {}
func (*SubmissionContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *SubmissionContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionContent.Unmarshal(m, b)
}
func (m *SubmissionContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionContent.Marshal(b, m, deterministic)
}
func (m *SubmissionContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionContent.Merge(m, src)
}
func (m *SubmissionContent) XXX_Size() int {
	return xxx_messageInfo_SubmissionContent.Size(m)
}
func (m *SubmissionContent) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionContent.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionContent proto.InternalMessageInfo

func (m *SubmissionContent) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

func (m *SubmissionContent) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

type SubmissionResult struct {
	Time                 *duration.Duration `protobuf:"bytes,1,opt,name=time" json:"time,omitempty" bson:"time,omitempty"`
	Memory               *int64             `protobuf:"varint,2,opt,name=memory" json:"memory,omitempty" bson:"memory,omitempty"`
	Message              *string            `protobuf:"bytes,3,opt,name=message" json:"message,omitempty" bson:"message,omitempty"`
	Score                *float64           `protobuf:"fixed64,4,opt,name=score" json:"score,omitempty" bson:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-" bson:"-"`
	XXX_unrecognized     []byte             `json:"-" bson:"-"`
	XXX_sizecache        int32              `json:"-" bson:"-"`
}

func (m *SubmissionResult) Reset()         { *m = SubmissionResult{} }
func (m *SubmissionResult) String() string { return proto.CompactTextString(m) }
func (*SubmissionResult) ProtoMessage()    {}
func (*SubmissionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *SubmissionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionResult.Unmarshal(m, b)
}
func (m *SubmissionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionResult.Marshal(b, m, deterministic)
}
func (m *SubmissionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionResult.Merge(m, src)
}
func (m *SubmissionResult) XXX_Size() int {
	return xxx_messageInfo_SubmissionResult.Size(m)
}
func (m *SubmissionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionResult.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionResult proto.InternalMessageInfo

func (m *SubmissionResult) GetTime() *duration.Duration {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *SubmissionResult) GetMemory() int64 {
	if m != nil && m.Memory != nil {
		return *m.Memory
	}
	return 0
}

func (m *SubmissionResult) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *SubmissionResult) GetScore() float64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

type SubmissionResultTestcase struct {
	Score                *float64 `protobuf:"fixed64,1,opt,name=score" json:"score,omitempty" bson:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *SubmissionResultTestcase) Reset()         { *m = SubmissionResultTestcase{} }
func (m *SubmissionResultTestcase) String() string { return proto.CompactTextString(m) }
func (*SubmissionResultTestcase) ProtoMessage()    {}
func (*SubmissionResultTestcase) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

func (m *SubmissionResultTestcase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmissionResultTestcase.Unmarshal(m, b)
}
func (m *SubmissionResultTestcase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmissionResultTestcase.Marshal(b, m, deterministic)
}
func (m *SubmissionResultTestcase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmissionResultTestcase.Merge(m, src)
}
func (m *SubmissionResultTestcase) XXX_Size() int {
	return xxx_messageInfo_SubmissionResultTestcase.Size(m)
}
func (m *SubmissionResultTestcase) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmissionResultTestcase.DiscardUnknown(m)
}

var xxx_messageInfo_SubmissionResultTestcase proto.InternalMessageInfo

func (m *SubmissionResultTestcase) GetScore() float64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func init() {
	proto.RegisterType((*ProblemData)(nil), "syzoj.judge.legacy.ProblemData")
	proto.RegisterType((*SubmissionContent)(nil), "syzoj.judge.legacy.SubmissionContent")
	proto.RegisterType((*SubmissionResult)(nil), "syzoj.judge.legacy.SubmissionResult")
	proto.RegisterType((*SubmissionResultTestcase)(nil), "syzoj.judge.legacy.SubmissionResultTestcase")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 523 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcb, 0x6e, 0xd4, 0x3e,
	0x18, 0xc5, 0x95, 0xff, 0x5c, 0xda, 0xf1, 0x54, 0xfa, 0x17, 0x23, 0x20, 0x9d, 0xd2, 0x6a, 0x14,
	0x58, 0x0c, 0x12, 0x4d, 0x44, 0x55, 0x81, 0xd4, 0x0d, 0x52, 0x28, 0x8b, 0x91, 0xb8, 0xa9, 0x80,
	0x84, 0xd8, 0x8c, 0x9c, 0xcc, 0x57, 0xe3, 0x12, 0xe7, 0x8b, 0x62, 0x67, 0x11, 0x36, 0x6c, 0x78,
	0x0a, 0x16, 0x3c, 0x02, 0xaf, 0x08, 0xb2, 0x9d, 0x69, 0x9d, 0xae, 0xd8, 0x8c, 0x34, 0xdf, 0x39,
	0xe7, 0x17, 0x5f, 0x8e, 0xc9, 0x54, 0xe2, 0x1a, 0x8a, 0xb8, 0xaa, 0x51, 0x23, 0xa5, 0xaa, 0xfd,
	0x86, 0x97, 0xf1, 0x65, 0xb3, 0xe6, 0x10, 0x17, 0xc0, 0x59, 0xde, 0xce, 0x0e, 0x39, 0x22, 0x2f,
	0x20, 0xb1, 0x8e, 0xac, 0xb9, 0x48, 0xd6, 0x4d, 0xcd, 0xb4, 0xc0, 0xd2, 0x65, 0x66, 0x3b, 0x9a,
	0x71, 0x0e, 0xb5, 0xfb, 0x17, 0xfd, 0x1e, 0x90, 0xe9, 0xbb, 0x1a, 0xb3, 0x02, 0xe4, 0x19, 0xd3,
	0x8c, 0x3e, 0x27, 0x44, 0x0b, 0x09, 0xab, 0x42, 0x48, 0xa1, 0xc3, 0x60, 0x1e, 0x2c, 0x06, 0xe9,
	0xfc, 0xe7, 0x8f, 0x5f, 0x83, 0xfd, 0x4c, 0x61, 0x79, 0x1a, 0x5d, 0x8b, 0x8f, 0x51, 0x0a, 0x0d,
	0xb2, 0xd2, 0x6d, 0x74, 0x3e, 0x31, 0xe3, 0x57, 0x66, 0x4a, 0x5f, 0x92, 0x1d, 0x09, 0x12, 0xeb,
	0xb6, 0x43, 0xfc, 0x67, 0x11, 0x91, 0x41, 0x1c, 0x38, 0x84, 0x2f, 0xfb, 0x90, 0xa9, 0x13, 0x1c,
	0xe6, 0x29, 0xd9, 0xba, 0x10, 0x05, 0xac, 0x04, 0x86, 0x83, 0x79, 0xb0, 0xd8, 0x4e, 0x0f, 0x0c,
	0x21, 0x74, 0x84, 0x4e, 0xf1, 0xc3, 0x63, 0x33, 0x5b, 0x22, 0xfd, 0x48, 0x68, 0xa7, 0xae, 0x44,
	0x59, 0x35, 0x7a, 0x55, 0x32, 0x09, 0xe1, 0x70, 0x1e, 0x2c, 0x26, 0xe9, 0xc2, 0x20, 0x1e, 0xf4,
	0x10, 0x9e, 0xc9, 0xa7, 0xfd, 0xef, 0x68, 0x4b, 0x23, 0xbe, 0x61, 0x12, 0xe8, 0x27, 0x72, 0x7b,
	0x93, 0xc0, 0x46, 0x5f, 0x71, 0x47, 0x96, 0xfb, 0xc8, 0x70, 0x1f, 0xf6, 0xb9, 0x9e, 0xcb, 0x07,
	0xef, 0x3a, 0xf0, 0x5b, 0xab, 0x5a, 0x72, 0x4c, 0x86, 0xba, 0xad, 0x20, 0x1c, 0xcf, 0x83, 0xc5,
	0x28, 0x9d, 0x19, 0xd4, 0x9d, 0xee, 0xa8, 0xdb, 0xaa, 0x97, 0xb5, 0xbe, 0xe8, 0x3b, 0xb9, 0xf5,
	0xbe, 0xc9, 0xa4, 0x50, 0x4a, 0x60, 0xf9, 0x02, 0x4b, 0x0d, 0xa5, 0xa6, 0xa7, 0x64, 0xbb, 0x60,
	0x25, 0x6f, 0x18, 0x07, 0x7b, 0x67, 0x93, 0xf4, 0xd0, 0x80, 0xf6, 0x1c, 0x68, 0x23, 0xf9, 0xb0,
	0x2b, 0xbf, 0x59, 0x40, 0x8e, 0x6b, 0xb0, 0x17, 0x35, 0xe9, 0x2d, 0xc0, 0x8c, 0x7b, 0x0b, 0x30,
	0x83, 0xe8, 0x4f, 0x40, 0x76, 0xaf, 0x57, 0x70, 0x0e, 0xaa, 0x29, 0x34, 0x5d, 0x92, 0xa1, 0xa9,
	0x80, 0xfd, 0xf8, 0xf4, 0x78, 0x2f, 0x76, 0x1d, 0x8c, 0x37, 0x1d, 0x8c, 0xcf, 0xba, 0x0e, 0xf6,
	0x37, 0x28, 0xe4, 0x8d, 0x0d, 0x0a, 0x09, 0xf4, 0x84, 0x8c, 0x5d, 0x11, 0xba, 0xea, 0xdc, 0x37,
	0x89, 0x7b, 0x7e, 0x75, 0x7a, 0xf7, 0xee, 0x46, 0xf4, 0x19, 0xd9, 0x92, 0xa0, 0x94, 0x39, 0x80,
	0x81, 0xdd, 0x88, 0xdf, 0x97, 0x4e, 0xf1, 0x73, 0x1b, 0x37, 0x7d, 0x42, 0x46, 0x2a, 0xc7, 0xda,
	0x75, 0x24, 0x48, 0xf7, 0x4d, 0xec, 0xae, 0x8b, 0xd9, 0xb9, 0x1f, 0x72, 0xce, 0xe8, 0x35, 0x09,
	0x6f, 0x1e, 0xc0, 0x07, 0x50, 0x3a, 0x67, 0xca, 0xc3, 0x05, 0xff, 0x8a, 0x4b, 0x4f, 0x3e, 0x1f,
	0x73, 0xa1, 0xbf, 0x34, 0x59, 0x9c, 0xa3, 0x4c, 0xec, 0x8b, 0x76, 0xbf, 0x47, 0x25, 0x3f, 0xe2,
	0x98, 0xd8, 0xd7, 0x5d, 0x27, 0x19, 0xcb, 0xbf, 0x42, 0xb9, 0x4e, 0xdc, 0x33, 0xff, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0xf5, 0x45, 0x8e, 0x51, 0x08, 0x04, 0x00, 0x00,
}
