// Code generated by protoc-gen-go. DO NOT EDIT.
// source: judge_rpc.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	model "github.com/syzoj/syzoj-ng-go/app/model"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JudgeRequest struct {
	JudgerId             *model.ObjectID `protobuf:"bytes,3,opt,name=judger_id,json=judgerId" json:"judger_id,omitempty"`
	JudgerToken          *string         `protobuf:"bytes,2,opt,name=judger_token,json=judgerToken" json:"judger_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *JudgeRequest) Reset()         { *m = JudgeRequest{} }
func (m *JudgeRequest) String() string { return proto.CompactTextString(m) }
func (*JudgeRequest) ProtoMessage()    {}
func (*JudgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc5778a58ecdd11e, []int{0}
}

func (m *JudgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeRequest.Unmarshal(m, b)
}
func (m *JudgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeRequest.Marshal(b, m, deterministic)
}
func (m *JudgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeRequest.Merge(m, src)
}
func (m *JudgeRequest) XXX_Size() int {
	return xxx_messageInfo_JudgeRequest.Size(m)
}
func (m *JudgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeRequest proto.InternalMessageInfo

func (m *JudgeRequest) GetJudgerId() *model.ObjectID {
	if m != nil {
		return m.JudgerId
	}
	return nil
}

func (m *JudgeRequest) GetJudgerToken() string {
	if m != nil && m.JudgerToken != nil {
		return *m.JudgerToken
	}
	return ""
}

type FetchTaskResult struct {
	Success              *bool    `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Task                 *Task    `protobuf:"bytes,2,opt,name=task" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchTaskResult) Reset()         { *m = FetchTaskResult{} }
func (m *FetchTaskResult) String() string { return proto.CompactTextString(m) }
func (*FetchTaskResult) ProtoMessage()    {}
func (*FetchTaskResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc5778a58ecdd11e, []int{1}
}

func (m *FetchTaskResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchTaskResult.Unmarshal(m, b)
}
func (m *FetchTaskResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchTaskResult.Marshal(b, m, deterministic)
}
func (m *FetchTaskResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchTaskResult.Merge(m, src)
}
func (m *FetchTaskResult) XXX_Size() int {
	return xxx_messageInfo_FetchTaskResult.Size(m)
}
func (m *FetchTaskResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchTaskResult.DiscardUnknown(m)
}

var xxx_messageInfo_FetchTaskResult proto.InternalMessageInfo

func (m *FetchTaskResult) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *FetchTaskResult) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type Task struct {
	TaskTag              *int64                   `protobuf:"varint,1,opt,name=task_tag,json=taskTag" json:"task_tag,omitempty"`
	ProblemId            *model.ObjectID          `protobuf:"bytes,5,opt,name=problem_id,json=problemId" json:"problem_id,omitempty"`
	Content              *model.SubmissionContent `protobuf:"bytes,6,opt,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc5778a58ecdd11e, []int{2}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetTaskTag() int64 {
	if m != nil && m.TaskTag != nil {
		return *m.TaskTag
	}
	return 0
}

func (m *Task) GetProblemId() *model.ObjectID {
	if m != nil {
		return m.ProblemId
	}
	return nil
}

func (m *Task) GetContent() *model.SubmissionContent {
	if m != nil {
		return m.Content
	}
	return nil
}

type TaskProgress struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskProgress) Reset()         { *m = TaskProgress{} }
func (m *TaskProgress) String() string { return proto.CompactTextString(m) }
func (*TaskProgress) ProtoMessage()    {}
func (*TaskProgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc5778a58ecdd11e, []int{3}
}

func (m *TaskProgress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskProgress.Unmarshal(m, b)
}
func (m *TaskProgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskProgress.Marshal(b, m, deterministic)
}
func (m *TaskProgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskProgress.Merge(m, src)
}
func (m *TaskProgress) XXX_Size() int {
	return xxx_messageInfo_TaskProgress.Size(m)
}
func (m *TaskProgress) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskProgress.DiscardUnknown(m)
}

var xxx_messageInfo_TaskProgress proto.InternalMessageInfo

type SetTaskResultMessage struct {
	JudgerId             *model.ObjectID         `protobuf:"bytes,5,opt,name=judger_id,json=judgerId" json:"judger_id,omitempty"`
	JudgerToken          *string                 `protobuf:"bytes,2,opt,name=judger_token,json=judgerToken" json:"judger_token,omitempty"`
	TaskTag              *int64                  `protobuf:"varint,3,opt,name=task_tag,json=taskTag" json:"task_tag,omitempty"`
	Result               *model.SubmissionResult `protobuf:"bytes,6,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SetTaskResultMessage) Reset()         { *m = SetTaskResultMessage{} }
func (m *SetTaskResultMessage) String() string { return proto.CompactTextString(m) }
func (*SetTaskResultMessage) ProtoMessage()    {}
func (*SetTaskResultMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc5778a58ecdd11e, []int{4}
}

func (m *SetTaskResultMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTaskResultMessage.Unmarshal(m, b)
}
func (m *SetTaskResultMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTaskResultMessage.Marshal(b, m, deterministic)
}
func (m *SetTaskResultMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTaskResultMessage.Merge(m, src)
}
func (m *SetTaskResultMessage) XXX_Size() int {
	return xxx_messageInfo_SetTaskResultMessage.Size(m)
}
func (m *SetTaskResultMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTaskResultMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SetTaskResultMessage proto.InternalMessageInfo

func (m *SetTaskResultMessage) GetJudgerId() *model.ObjectID {
	if m != nil {
		return m.JudgerId
	}
	return nil
}

func (m *SetTaskResultMessage) GetJudgerToken() string {
	if m != nil && m.JudgerToken != nil {
		return *m.JudgerToken
	}
	return ""
}

func (m *SetTaskResultMessage) GetTaskTag() int64 {
	if m != nil && m.TaskTag != nil {
		return *m.TaskTag
	}
	return 0
}

func (m *SetTaskResultMessage) GetResult() *model.SubmissionResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*JudgeRequest)(nil), "syzoj.judge.rpc.JudgeRequest")
	proto.RegisterType((*FetchTaskResult)(nil), "syzoj.judge.rpc.FetchTaskResult")
	proto.RegisterType((*Task)(nil), "syzoj.judge.rpc.Task")
	proto.RegisterType((*TaskProgress)(nil), "syzoj.judge.rpc.TaskProgress")
	proto.RegisterType((*SetTaskResultMessage)(nil), "syzoj.judge.rpc.SetTaskResultMessage")
}

func init() { proto.RegisterFile("judge_rpc.proto", fileDescriptor_dc5778a58ecdd11e) }

var fileDescriptor_dc5778a58ecdd11e = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x5d, 0xe8, 0xba, 0xb6, 0xb7, 0x85, 0x48, 0x16, 0xa0, 0xac, 0x68, 0xa8, 0x44, 0x42, 0x2a,
	0x12, 0x73, 0xa4, 0x4a, 0xa0, 0x3d, 0xf3, 0x25, 0x15, 0xf1, 0x31, 0x65, 0x15, 0x0f, 0xbc, 0x54,
	0x89, 0x7b, 0xf1, 0xd2, 0x36, 0x71, 0xb0, 0x1d, 0xa4, 0xf1, 0x3f, 0xf8, 0x45, 0xfc, 0x28, 0x5e,
	0x91, 0xed, 0x94, 0x2d, 0xeb, 0x2a, 0x5e, 0xf6, 0x12, 0xe9, 0xde, 0x7b, 0x7c, 0x7c, 0xcf, 0xf1,
	0x09, 0xf8, 0xcb, 0x6a, 0xc1, 0x71, 0x2e, 0x4b, 0x46, 0x4b, 0x29, 0xb4, 0x20, 0xbe, 0xba, 0xf8,
	0x29, 0x96, 0xd4, 0xb6, 0xa9, 0x2c, 0xd9, 0xf0, 0x11, 0x17, 0x82, 0xaf, 0x31, 0xb2, 0xe3, 0xb4,
	0xfa, 0x16, 0x61, 0x5e, 0xea, 0x0b, 0x87, 0x1e, 0xfa, 0xa5, 0xcc, 0xf2, 0x4c, 0x67, 0x3f, 0xb0,
	0x6e, 0xf4, 0xdd, 0x41, 0x5b, 0x84, 0x19, 0x0c, 0xde, 0x9b, 0x32, 0xc6, 0xef, 0x15, 0x2a, 0x4d,
	0x5e, 0x42, 0xcf, 0x8e, 0xe5, 0x3c, 0x5b, 0x04, 0xad, 0x91, 0x37, 0xee, 0x4f, 0x0e, 0xa9, 0xbb,
	0xef, 0x92, 0xe7, 0x73, 0xba, 0x44, 0xa6, 0xa7, 0x6f, 0xe2, 0xae, 0xc3, 0x4e, 0x17, 0xe4, 0x09,
	0x0c, 0xea, 0x73, 0x5a, 0xac, 0xb0, 0x08, 0xee, 0x8c, 0xbc, 0x71, 0x2f, 0x76, 0x57, 0xc9, 0x99,
	0x69, 0x85, 0x5f, 0xc0, 0x7f, 0x87, 0x9a, 0x9d, 0xcf, 0x12, 0xb5, 0x8a, 0x51, 0x55, 0x6b, 0x4d,
	0x02, 0xe8, 0xa8, 0x8a, 0x31, 0x54, 0x2a, 0xf0, 0x46, 0xde, 0xb8, 0x1b, 0x6f, 0x4a, 0xf2, 0x0c,
	0xf6, 0x75, 0xa2, 0x56, 0x96, 0xa7, 0x3f, 0x79, 0x40, 0xaf, 0x49, 0xa6, 0x96, 0xc4, 0x42, 0xc2,
	0x5f, 0x1e, 0xec, 0x9b, 0x92, 0x1c, 0x42, 0xd7, 0x34, 0xe6, 0x3a, 0xe1, 0x96, 0xae, 0x15, 0x77,
	0x4c, 0x3d, 0x4b, 0x38, 0x39, 0x01, 0x28, 0xa5, 0x48, 0xd7, 0x98, 0x1b, 0x5d, 0xed, 0xff, 0xe9,
	0xea, 0xd5, 0xe0, 0xe9, 0x82, 0x9c, 0x40, 0x87, 0x89, 0x42, 0x63, 0xa1, 0x83, 0x03, 0x7b, 0xec,
	0x71, 0x63, 0x97, 0xb3, 0x2a, 0xcd, 0x33, 0xa5, 0x32, 0x51, 0xbc, 0x76, 0xa8, 0x78, 0x03, 0x0f,
	0xef, 0xc1, 0xc0, 0xac, 0x75, 0x2a, 0x05, 0x97, 0xa8, 0x54, 0xf8, 0xdb, 0x83, 0xfb, 0x67, 0xa8,
	0x2f, 0xe5, 0x7f, 0x44, 0xa5, 0x12, 0x8e, 0x4d, 0xcf, 0xdb, 0xb7, 0xe9, 0x79, 0xc3, 0x92, 0x56,
	0xd3, 0x92, 0x17, 0x70, 0x20, 0xed, 0x1a, 0xb5, 0xae, 0xa3, 0x1d, 0xba, 0xdc, 0xae, 0x71, 0x0d,
	0x9e, 0xfc, 0xf1, 0xa0, 0x6d, 0x13, 0x43, 0x3e, 0x41, 0xef, 0xdf, 0x7b, 0x92, 0xa3, 0xad, 0x17,
	0xba, 0x1a, 0xab, 0xe1, 0x68, 0x6b, 0x7c, 0x2d, 0x0a, 0xe1, 0x1e, 0xf9, 0x00, 0x7e, 0x6d, 0xcf,
	0xc6, 0xb2, 0x1b, 0x58, 0xaf, 0x8e, 0x87, 0x0f, 0xa9, 0x0b, 0x3e, 0xdd, 0x04, 0x9f, 0xbe, 0x35,
	0xc1, 0x0f, 0xf7, 0xc6, 0x1e, 0x39, 0x85, 0xbb, 0x0d, 0xb3, 0xc9, 0xd3, 0x2d, 0xae, 0x9b, 0x1e,
	0x63, 0x37, 0xe7, 0x2b, 0xfa, 0xf5, 0x39, 0xcf, 0xf4, 0x79, 0x95, 0x52, 0x26, 0xf2, 0xc8, 0x92,
	0xb9, 0xef, 0x71, 0xc1, 0x8f, 0xb9, 0x88, 0x92, 0xb2, 0x8c, 0x98, 0x90, 0xf5, 0x6f, 0xa8, 0xfe,
	0x06, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x8a, 0x6d, 0x55, 0xb8, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JudgeClient is the client API for Judge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JudgeClient interface {
	FetchTask(ctx context.Context, in *JudgeRequest, opts ...grpc.CallOption) (*FetchTaskResult, error)
	SetTaskProgress(ctx context.Context, opts ...grpc.CallOption) (Judge_SetTaskProgressClient, error)
	SetTaskResult(ctx context.Context, in *SetTaskResultMessage, opts ...grpc.CallOption) (*empty.Empty, error)
}

type judgeClient struct {
	cc *grpc.ClientConn
}

func NewJudgeClient(cc *grpc.ClientConn) JudgeClient {
	return &judgeClient{cc}
}

func (c *judgeClient) FetchTask(ctx context.Context, in *JudgeRequest, opts ...grpc.CallOption) (*FetchTaskResult, error) {
	out := new(FetchTaskResult)
	err := c.cc.Invoke(ctx, "/syzoj.judge.rpc.Judge/FetchTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgeClient) SetTaskProgress(ctx context.Context, opts ...grpc.CallOption) (Judge_SetTaskProgressClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Judge_serviceDesc.Streams[0], "/syzoj.judge.rpc.Judge/SetTaskProgress", opts...)
	if err != nil {
		return nil, err
	}
	x := &judgeSetTaskProgressClient{stream}
	return x, nil
}

type Judge_SetTaskProgressClient interface {
	Send(*TaskProgress) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type judgeSetTaskProgressClient struct {
	grpc.ClientStream
}

func (x *judgeSetTaskProgressClient) Send(m *TaskProgress) error {
	return x.ClientStream.SendMsg(m)
}

func (x *judgeSetTaskProgressClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *judgeClient) SetTaskResult(ctx context.Context, in *SetTaskResultMessage, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/syzoj.judge.rpc.Judge/SetTaskResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JudgeServer is the server API for Judge service.
type JudgeServer interface {
	FetchTask(context.Context, *JudgeRequest) (*FetchTaskResult, error)
	SetTaskProgress(Judge_SetTaskProgressServer) error
	SetTaskResult(context.Context, *SetTaskResultMessage) (*empty.Empty, error)
}

func RegisterJudgeServer(s *grpc.Server, srv JudgeServer) {
	s.RegisterService(&_Judge_serviceDesc, srv)
}

func _Judge_FetchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JudgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServer).FetchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syzoj.judge.rpc.Judge/FetchTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServer).FetchTask(ctx, req.(*JudgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Judge_SetTaskProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(JudgeServer).SetTaskProgress(&judgeSetTaskProgressServer{stream})
}

type Judge_SetTaskProgressServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*TaskProgress, error)
	grpc.ServerStream
}

type judgeSetTaskProgressServer struct {
	grpc.ServerStream
}

func (x *judgeSetTaskProgressServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *judgeSetTaskProgressServer) Recv() (*TaskProgress, error) {
	m := new(TaskProgress)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Judge_SetTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTaskResultMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServer).SetTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syzoj.judge.rpc.Judge/SetTaskResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServer).SetTaskResult(ctx, req.(*SetTaskResultMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Judge_serviceDesc = grpc.ServiceDesc{
	ServiceName: "syzoj.judge.rpc.Judge",
	HandlerType: (*JudgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchTask",
			Handler:    _Judge_FetchTask_Handler,
		},
		{
			MethodName: "SetTaskResult",
			Handler:    _Judge_SetTaskResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SetTaskProgress",
			Handler:       _Judge_SetTaskProgress_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "judge_rpc.proto",
}
