// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Article              string
	ArticleComment       string
	Contest              string
	ContestPlayer        string
	ContestRanklist      string
	File                 string
	FormattedCode        string
	JudgeState           string
	Problem              string
	ProblemTag           string
	ProblemTagMap        string
	RatingCalculation    string
	RatingHistory        string
	SubmissionStatistics string
	User                 string
	UserPrivilege        string
}{
	Article:              "article",
	ArticleComment:       "article_comment",
	Contest:              "contest",
	ContestPlayer:        "contest_player",
	ContestRanklist:      "contest_ranklist",
	File:                 "file",
	FormattedCode:        "formatted_code",
	JudgeState:           "judge_state",
	Problem:              "problem",
	ProblemTag:           "problem_tag",
	ProblemTagMap:        "problem_tag_map",
	RatingCalculation:    "rating_calculation",
	RatingHistory:        "rating_history",
	SubmissionStatistics: "submission_statistics",
	User:                 "user",
	UserPrivilege:        "user_privilege",
}
